// ______________________________________________________
// Generated by sql2java - http://sql2java.sourceforge.net/
// jdbc driver used at code generation time: com.mysql.jdbc.Driver
//
// Please help us improve this tool by reporting:
// - problems and suggestions to
//   http://sourceforge.net/tracker/?group_id=54687
// - feedbacks and ideas on
//   http://sourceforge.net/forum/forum.php?forum_id=182208
// ______________________________________________________

package com.gwt.hris.client.service.bean;

public class TbCompanyPropertyBeanService
{
	private static final long serialVersionUID = -3572683760511939709L;
	
    private String tbcpNama;

    private Integer tbeId;

    private Integer tbcpId;

	
	private TbCompanyPropertyBeanService beanServices[];
	
	public TbCompanyPropertyBeanService[] getServices() {
		return beanServices;
	}

	public void setServices(TbCompanyPropertyBeanService[] _beanServices) {
		this.beanServices = _beanServices;
	}

    public String getTbcpNama()
    {
		return tbcpNama;
    }

    public void setTbcpNama(String newVal)
    {
		this.tbcpNama = newVal;
    }


    public Integer getTbeId()
    {
		return tbeId;
    }

    public void setTbeId(Integer newVal)
    {
		this.tbeId = newVal;
    }

    public void setTbeId(int newVal)
    {
        setTbeId(new Integer(newVal));
    }

    public Integer getTbcpId()
    {
		return tbcpId;
    }

    public void setTbcpId(Integer newVal)
    {
		this.tbcpId = newVal;
    }

    public void setTbcpId(int newVal)
    {
        setTbcpId(new Integer(newVal));
    }

}
