// ______________________________________________________
// Generated by sql2java - http://sql2java.sourceforge.net/
// jdbc driver used at code generation time: com.mysql.jdbc.Driver
//
// Please help us improve this tool by reporting:
// - problems and suggestions to
//   http://sourceforge.net/tracker/?group_id=54687
// - feedbacks and ideas on
//   http://sourceforge.net/forum/forum.php?forum_id=182208
// ______________________________________________________

package com.gwt.hris.client.service.bean;

import java.io.Serializable;

public class TbDependentsBeanModel extends ReturnBean implements Serializable
{
	private static final long serialVersionUID = -3090814852926664733L;
	
	private TbDependentsBeanModel beanModels[];
	
	public TbDependentsBeanModel[] getModels() {
		return beanModels;
	}

	public void setModels(TbDependentsBeanModel[] _beanModels) {
		this.beanModels = _beanModels;
	}

    public String getTbdRelationship()
    {
		return (String) get("tbdRelationship");
    }

    public void setTbdRelationship(String newVal)
    {
		set("tbdRelationship", newVal);
    }


    public Integer getTbdDependentsType()
    {
		return (Integer) get("tbdDependentsType");
    }

    public void setTbdDependentsType(Integer newVal)
    {
		set("tbdDependentsType", newVal);
    }

    public void setTbdDependentsType(int newVal)
    {
        setTbdDependentsType(new Integer(newVal));
    }

    public java.sql.Timestamp getTbdDob()
    {
		return (java.sql.Timestamp) get("tbdDob");
    }

    public void setTbdDob(java.sql.Timestamp newVal)
    {
		set("tbdDob", newVal);
    }

    public void setTbdDob(long newVal)
    {
        setTbdDob(new java.sql.Timestamp(newVal));
    }

    public String getTbdName()
    {
		return (String) get("tbdName");
    }

    public void setTbdName(String newVal)
    {
		set("tbdName", newVal);
    }


    public Integer getTbeId()
    {
		return (Integer) get("tbeId");
    }

    public void setTbeId(Integer newVal)
    {
		set("tbeId", newVal);
    }

    public void setTbeId(int newVal)
    {
        setTbeId(new Integer(newVal));
    }

    public Integer getTbdId()
    {
		return (Integer) get("tbdId");
    }

    public void setTbdId(Integer newVal)
    {
		set("tbdId", newVal);
    }

    public void setTbdId(int newVal)
    {
        setTbdId(new Integer(newVal));
    }

}
