// ______________________________________________________
// Generated by sql2java - http://sql2java.sourceforge.net/
// jdbc driver used at code generation time: com.mysql.jdbc.Driver
//
// Please help us improve this tool by reporting:
// - problems and suggestions to
//   http://sourceforge.net/tracker/?group_id=54687
// - feedbacks and ideas on
//   http://sourceforge.net/forum/forum.php?forum_id=182208
// ______________________________________________________

package com.gwt.hris.client.service.bean;

import java.io.Serializable;

public class TbEeoJobCategoryBeanModel extends ReturnBean implements Serializable
{
	private static final long serialVersionUID = 8013564664271135912L;
	
	private TbEeoJobCategoryBeanModel beanModels[];
	
	public TbEeoJobCategoryBeanModel[] getModels() {
		return beanModels;
	}

	public void setModels(TbEeoJobCategoryBeanModel[] _beanModels) {
		this.beanModels = _beanModels;
	}

    public String getTbejcTitle()
    {
		return (String) get("tbejcTitle");
    }

    public void setTbejcTitle(String newVal)
    {
		set("tbejcTitle", newVal);
    }


    public String getTbejcEeoJobCategoryId()
    {
		return (String) get("tbejcEeoJobCategoryId");
    }

    public void setTbejcEeoJobCategoryId(String newVal)
    {
		set("tbejcEeoJobCategoryId", newVal);
    }


    public Integer getTbejcId()
    {
		return (Integer) get("tbejcId");
    }

    public void setTbejcId(Integer newVal)
    {
		set("tbejcId", newVal);
    }

    public void setTbejcId(int newVal)
    {
        setTbejcId(new Integer(newVal));
    }

}
