// ______________________________________________________
// Generated by sql2java - http://sql2java.sourceforge.net/
// jdbc driver used at code generation time: com.mysql.jdbc.Driver
//
// Please help us improve this tool by reporting:
// - problems and suggestions to
//   http://sourceforge.net/tracker/?group_id=54687
// - feedbacks and ideas on
//   http://sourceforge.net/forum/forum.php?forum_id=182208
// ______________________________________________________

package com.gwt.hris.client.service.bean;

import java.io.Serializable;

public class TbEmployeeBeanModel extends ReturnBean implements Serializable
{
	private static final long serialVersionUID = 8013564664271135912L;
	
	private TbEmployeeBeanModel beanModels[];
	
	public TbEmployeeBeanModel[] getModels() {
		return beanModels;
	}

	public void setModels(TbEmployeeBeanModel[] _beanModels) {
		this.beanModels = _beanModels;
	}

    public Integer getTbptkpId()
    {
		return (Integer) get("tbptkpId");
    }

    public void setTbptkpId(Integer newVal)
    {
		set("tbptkpId", newVal);
    }

    public void setTbptkpId(int newVal)
    {
        setTbptkpId(new Integer(newVal));
    }

    public Integer getTberId()
    {
		return (Integer) get("tberId");
    }

    public void setTberId(Integer newVal)
    {
		set("tberId", newVal);
    }

    public void setTberId(int newVal)
    {
        setTberId(new Integer(newVal));
    }

    public Integer getTbnId()
    {
		return (Integer) get("tbnId");
    }

    public void setTbnId(Integer newVal)
    {
		set("tbnId", newVal);
    }

    public void setTbnId(int newVal)
    {
        setTbnId(new Integer(newVal));
    }

    public java.sql.Timestamp getTbeJoinedDate()
    {
		return (java.sql.Timestamp) get("tbeJoinedDate");
    }

    public void setTbeJoinedDate(java.sql.Timestamp newVal)
    {
		set("tbeJoinedDate", newVal);
    }

    public void setTbeJoinedDate(long newVal)
    {
        setTbeJoinedDate(new java.sql.Timestamp(newVal));
    }

    public Integer getTbeStatus()
    {
		return (Integer) get("tbeStatus");
    }

    public void setTbeStatus(Integer newVal)
    {
		set("tbeStatus", newVal);
    }

    public void setTbeStatus(int newVal)
    {
        setTbeStatus(new Integer(newVal));
    }

    public java.sql.Timestamp getTbeDriverLicenseExpiry()
    {
		return (java.sql.Timestamp) get("tbeDriverLicenseExpiry");
    }

    public void setTbeDriverLicenseExpiry(java.sql.Timestamp newVal)
    {
		set("tbeDriverLicenseExpiry", newVal);
    }

    public void setTbeDriverLicenseExpiry(long newVal)
    {
        setTbeDriverLicenseExpiry(new java.sql.Timestamp(newVal));
    }

    public String getTbePhone()
    {
		return (String) get("tbePhone");
    }

    public void setTbePhone(String newVal)
    {
		set("tbePhone", newVal);
    }


    public String getTbeMobile()
    {
		return (String) get("tbeMobile");
    }

    public void setTbeMobile(String newVal)
    {
		set("tbeMobile", newVal);
    }


    public String getTbeDriverLicenseNo()
    {
		return (String) get("tbeDriverLicenseNo");
    }

    public void setTbeDriverLicenseNo(String newVal)
    {
		set("tbeDriverLicenseNo", newVal);
    }


    public Integer getTbeGender()
    {
		return (Integer) get("tbeGender");
    }

    public void setTbeGender(Integer newVal)
    {
		set("tbeGender", newVal);
    }

    public void setTbeGender(int newVal)
    {
        setTbeGender(new Integer(newVal));
    }

    public Integer getTbeSmoker()
    {
		return (Integer) get("tbeSmoker");
    }

    public void setTbeSmoker(Integer newVal)
    {
		set("tbeSmoker", newVal);
    }

    public void setTbeSmoker(int newVal)
    {
        setTbeSmoker(new Integer(newVal));
    }

    public Integer getTbeMaritalStatus()
    {
		return (Integer) get("tbeMaritalStatus");
    }

    public void setTbeMaritalStatus(Integer newVal)
    {
		set("tbeMaritalStatus", newVal);
    }

    public void setTbeMaritalStatus(int newVal)
    {
        setTbeMaritalStatus(new Integer(newVal));
    }

    public java.sql.Timestamp getTbeDob()
    {
		return (java.sql.Timestamp) get("tbeDob");
    }

    public void setTbeDob(java.sql.Timestamp newVal)
    {
		set("tbeDob", newVal);
    }

    public void setTbeDob(long newVal)
    {
        setTbeDob(new java.sql.Timestamp(newVal));
    }

    public java.sql.Timestamp getTbeTaxNoDate()
    {
		return (java.sql.Timestamp) get("tbeTaxNoDate");
    }

    public void setTbeTaxNoDate(java.sql.Timestamp newVal)
    {
		set("tbeTaxNoDate", newVal);
    }

    public void setTbeTaxNoDate(long newVal)
    {
        setTbeTaxNoDate(new java.sql.Timestamp(newVal));
    }

    public String getTbeTaxNo()
    {
		return (String) get("tbeTaxNo");
    }

    public void setTbeTaxNo(String newVal)
    {
		set("tbeTaxNo", newVal);
    }


    public String getTbeIdNo()
    {
		return (String) get("tbeIdNo");
    }

    public void setTbeIdNo(String newVal)
    {
		set("tbeIdNo", newVal);
    }


    public String getTbePhotoFileName()
    {
		return (String) get("tbePhotoFileName");
    }

    public void setTbePhotoFileName(String newVal)
    {
		set("tbePhotoFileName", newVal);
    }


    public String getTbeName()
    {
		return (String) get("tbeName");
    }

    public void setTbeName(String newVal)
    {
		set("tbeName", newVal);
    }


    public String getTbeNickName()
    {
		return (String) get("tbeNickName");
    }

    public void setTbeNickName(String newVal)
    {
		set("tbeNickName", newVal);
    }


    public String getTbeLastName()
    {
		return (String) get("tbeLastName");
    }

    public void setTbeLastName(String newVal)
    {
		set("tbeLastName", newVal);
    }


    public String getTbeMiddleName()
    {
		return (String) get("tbeMiddleName");
    }

    public void setTbeMiddleName(String newVal)
    {
		set("tbeMiddleName", newVal);
    }


    public String getTbeFirstName()
    {
		return (String) get("tbeFirstName");
    }

    public void setTbeFirstName(String newVal)
    {
		set("tbeFirstName", newVal);
    }


    public String getTbeEmail()
    {
		return (String) get("tbeEmail");
    }

    public void setTbeEmail(String newVal)
    {
		set("tbeEmail", newVal);
    }


    public String getTbeEmployeeId()
    {
		return (String) get("tbeEmployeeId");
    }

    public void setTbeEmployeeId(String newVal)
    {
		set("tbeEmployeeId", newVal);
    }


    public Integer getTbeId()
    {
		return (Integer) get("tbeId");
    }

    public void setTbeId(Integer newVal)
    {
		set("tbeId", newVal);
    }

    public void setTbeId(int newVal)
    {
        setTbeId(new Integer(newVal));
    }

}
