// ______________________________________________________
// Generated by sql2java - http://sql2java.sourceforge.net/
// jdbc driver used at code generation time: com.mysql.jdbc.Driver
//
// Please help us improve this tool by reporting:
// - problems and suggestions to
//   http://sourceforge.net/tracker/?group_id=54687
// - feedbacks and ideas on
//   http://sourceforge.net/forum/forum.php?forum_id=182208
// ______________________________________________________

package com.gwt.hris.client.service.bean;

import java.io.Serializable;

public class TbNotificationUiBeanModel extends ReturnBean implements Serializable
{
	private static final long serialVersionUID = 5273985348790964280L;
	
	private TbNotificationUiBeanModel beanModels[];
	
	public TbNotificationUiBeanModel[] getModels() {
		return beanModels;
	}

	public void setModels(TbNotificationUiBeanModel[] _beanModels) {
		this.beanModels = _beanModels;
	}

    public String getTbnuName()
    {
		return (String) get("tbnuName");
    }

    public void setTbnuName(String newVal)
    {
		set("tbnuName", newVal);
    }


    public Integer getTbnuId()
    {
		return (Integer) get("tbnuId");
    }

    public void setTbnuId(Integer newVal)
    {
		set("tbnuId", newVal);
    }

    public void setTbnuId(int newVal)
    {
        setTbnuId(new Integer(newVal));
    }

}
