// ______________________________________________________
// Generated by sql2java - http://sql2java.sourceforge.net/
// jdbc driver used at code generation time: com.mysql.jdbc.Driver
//
// Please help us improve this tool by reporting:
// - problems and suggestions to
//   http://sourceforge.net/tracker/?group_id=54687
// - feedbacks and ideas on
//   http://sourceforge.net/forum/forum.php?forum_id=182208
// ______________________________________________________

package com.gwt.hris.client.service.bean;

import java.io.Serializable;

public class TbTarifPajakBeanModel extends ReturnBean implements Serializable
{
	private static final long serialVersionUID = 2680468258523135691L;
	
	private TbTarifPajakBeanModel beanModels[];
	
	public TbTarifPajakBeanModel[] getModels() {
		return beanModels;
	}

	public void setModels(TbTarifPajakBeanModel[] _beanModels) {
		this.beanModels = _beanModels;
	}

    public Integer getTbtpNonNpwp()
    {
		return (Integer) get("tbtpNonNpwp");
    }

    public void setTbtpNonNpwp(Integer newVal)
    {
		set("tbtpNonNpwp", newVal);
    }

    public void setTbtpNonNpwp(int newVal)
    {
        setTbtpNonNpwp(new Integer(newVal));
    }

    public Integer getTbtpNpwp()
    {
		return (Integer) get("tbtpNpwp");
    }

    public void setTbtpNpwp(Integer newVal)
    {
		set("tbtpNpwp", newVal);
    }

    public void setTbtpNpwp(int newVal)
    {
        setTbtpNpwp(new Integer(newVal));
    }

    public Double getTbtpPkpSampai()
    {
		return (Double) get("tbtpPkpSampai");
    }

    public void setTbtpPkpSampai(Double newVal)
    {
		set("tbtpPkpSampai", newVal);
    }

    public void setTbtpPkpSampai(double newVal)
    {
        setTbtpPkpSampai(new Double(newVal));
    }

    public Double getTbtpPkpDari()
    {
		return (Double) get("tbtpPkpDari");
    }

    public void setTbtpPkpDari(Double newVal)
    {
		set("tbtpPkpDari", newVal);
    }

    public void setTbtpPkpDari(double newVal)
    {
        setTbtpPkpDari(new Double(newVal));
    }

    public Integer getTbtpId()
    {
		return (Integer) get("tbtpId");
    }

    public void setTbtpId(Integer newVal)
    {
		set("tbtpId", newVal);
    }

    public void setTbtpId(int newVal)
    {
        setTbtpId(new Integer(newVal));
    }

}
