// ______________________________________________________
// Generated by sql2java - http://sql2java.sourceforge.net/
// jdbc driver used at code generation time: com.mysql.jdbc.Driver
//
// Please help us improve this tool by reporting:
// - problems and suggestions to
//   http://sourceforge.net/tracker/?group_id=54687
// - feedbacks and ideas on
//   http://sourceforge.net/forum/forum.php?forum_id=182208
// ______________________________________________________

package com.gwt.hris.client.service.bean;

import java.io.Serializable;

public class ViewReportEmployeeInformation3BeanModel extends ReturnBean implements Serializable
{
	private static final long serialVersionUID = -5392207471294970754L;
	
	private ViewReportEmployeeInformation3BeanModel beanModels[];
	
	public ViewReportEmployeeInformation3BeanModel[] getModels() {
		return beanModels;
	}

	public void setModels(ViewReportEmployeeInformation3BeanModel[] _beanModels) {
		this.beanModels = _beanModels;
	}

    public String getTblName()
    {
		return (String) get("tblName");
    }

    public void setTblName(String newVal)
    {
		set("tblName", newVal);
    }


    public String getTbeName()
    {
		return (String) get("tbeName");
    }

    public void setTbeName(String newVal)
    {
		set("tbeName", newVal);
    }


    public Integer getTbeId()
    {
		return (Integer) get("tbeId");
    }

    public void setTbeId(Integer newVal)
    {
		set("tbeId", newVal);
    }

    public void setTbeId(int newVal)
    {
        setTbeId(new Integer(newVal));
    }

}
