// ______________________________________________________
// Generated by sql2java - http://sql2java.sourceforge.net/
// jdbc driver used at code generation time: com.mysql.jdbc.Driver
//
// Please help us improve this tool by reporting:
// - problems and suggestions to
//   http://sourceforge.net/tracker/?group_id=54687
// - feedbacks and ideas on
//   http://sourceforge.net/forum/forum.php?forum_id=182208
// ______________________________________________________

package com.gwt.hris.client.service.bean;

public class ViewJobTitleLeaveBeanService
{
	private static final long serialVersionUID = -3547896499376775900L;
	
    private Integer tbjtlPriorDate;

    private Integer tbjtlMin;

    private Integer tbjtlId;

    private Integer tbltReduction;

    private String tbltName;

    private String tbltLeaveTypesId;

    private Integer tbltId;

    private String tbjtName;

    private String tbjtJobTitleId;

    private Integer tbjtId;

	
	private ViewJobTitleLeaveBeanService beanServices[];
	
	public ViewJobTitleLeaveBeanService[] getServices() {
		return beanServices;
	}

	public void setServices(ViewJobTitleLeaveBeanService[] _beanServices) {
		this.beanServices = _beanServices;
	}

    public Integer getTbjtlPriorDate()
    {
		return tbjtlPriorDate;
    }

    public void setTbjtlPriorDate(Integer newVal)
    {
		this.tbjtlPriorDate = newVal;
    }

    public void setTbjtlPriorDate(int newVal)
    {
        setTbjtlPriorDate(new Integer(newVal));
    }

    public Integer getTbjtlMin()
    {
		return tbjtlMin;
    }

    public void setTbjtlMin(Integer newVal)
    {
		this.tbjtlMin = newVal;
    }

    public void setTbjtlMin(int newVal)
    {
        setTbjtlMin(new Integer(newVal));
    }

    public Integer getTbjtlId()
    {
		return tbjtlId;
    }

    public void setTbjtlId(Integer newVal)
    {
		this.tbjtlId = newVal;
    }

    public void setTbjtlId(int newVal)
    {
        setTbjtlId(new Integer(newVal));
    }

    public Integer getTbltReduction()
    {
		return tbltReduction;
    }

    public void setTbltReduction(Integer newVal)
    {
		this.tbltReduction = newVal;
    }

    public void setTbltReduction(int newVal)
    {
        setTbltReduction(new Integer(newVal));
    }

    public String getTbltName()
    {
		return tbltName;
    }

    public void setTbltName(String newVal)
    {
		this.tbltName = newVal;
    }


    public String getTbltLeaveTypesId()
    {
		return tbltLeaveTypesId;
    }

    public void setTbltLeaveTypesId(String newVal)
    {
		this.tbltLeaveTypesId = newVal;
    }


    public Integer getTbltId()
    {
		return tbltId;
    }

    public void setTbltId(Integer newVal)
    {
		this.tbltId = newVal;
    }

    public void setTbltId(int newVal)
    {
        setTbltId(new Integer(newVal));
    }

    public String getTbjtName()
    {
		return tbjtName;
    }

    public void setTbjtName(String newVal)
    {
		this.tbjtName = newVal;
    }


    public String getTbjtJobTitleId()
    {
		return tbjtJobTitleId;
    }

    public void setTbjtJobTitleId(String newVal)
    {
		this.tbjtJobTitleId = newVal;
    }


    public Integer getTbjtId()
    {
		return tbjtId;
    }

    public void setTbjtId(Integer newVal)
    {
		this.tbjtId = newVal;
    }

    public void setTbjtId(int newVal)
    {
        setTbjtId(new Integer(newVal));
    }

}
