// ______________________________________________________
// Generated by sql2java - http://sql2java.sourceforge.net/
// jdbc driver used at code generation time: com.mysql.jdbc.Driver
//
// Please help us improve this tool by reporting:
// - problems and suggestions to
//   http://sourceforge.net/tracker/?group_id=54687
// - feedbacks and ideas on
//   http://sourceforge.net/forum/forum.php?forum_id=182208
// ______________________________________________________

package com.gwt.hris.db;

import java.util.Comparator;


/**
 * Comparator class is used to sort the TbCustomerBean objects.
 * @author sql2java
 */
public class TbCustomerComparator implements Comparator
{
    /**
     * Holds the field on which the comparison is performed.
     */
    private int iType;
    /**
     * Value that will contain the information about the order of the sort: normal or reversal.
     */
    private boolean bReverse;

    /**
     * Constructor class for TbCustomerComparator.
     * <br>
     * Example:
     * <br>
     * <code>Arrays.sort(pArray, new TbCustomerComparator(TbCustomerManager.ID_TBC_DESCRIPTION, bReverse));<code>
     *
     * @param iType the field from which you want to sort
     * <br>
     * Possible values are:
     * <ul>
     *   <li>TbCustomerManager.ID_TBC_DESCRIPTION
     *   <li>TbCustomerManager.ID_TBC_NAME
     *   <li>TbCustomerManager.ID_TBC_CUSTOMER_ID
     *   <li>TbCustomerManager.ID_TBC_ID
     * </ul>
     */
    public TbCustomerComparator(int iType)
    {
        this(iType, false);
    }

    /**
     * Constructor class for TbCustomerComparator.
     * <br>
     * Example:
     * <br>
     * <code>Arrays.sort(pArray, new TbCustomerComparator(TbCustomerManager.ID_TBC_DESCRIPTION, bReverse));<code>
     *
     * @param iType the field from which you want to sort.
     * <br>
     * Possible values are:
     * <ul>
     *   <li>TbCustomerManager.ID_TBC_DESCRIPTION
     *   <li>TbCustomerManager.ID_TBC_NAME
     *   <li>TbCustomerManager.ID_TBC_CUSTOMER_ID
     *   <li>TbCustomerManager.ID_TBC_ID
     * </ul>
     *
     * @param bReverse set this value to true, if you want to reverse the sorting results
     */
    public TbCustomerComparator(int iType, boolean bReverse)
    {
        this.iType = iType;
        this.bReverse = bReverse;
    }

    /**
     * Implementation of the compare method.
     */
    public int compare(Object pObj1, Object pObj2)
    {
        TbCustomerBean b1 = (TbCustomerBean)pObj1;
        TbCustomerBean b2 = (TbCustomerBean)pObj2;
        int iReturn = 0;
        switch(iType)
        {
            case TbCustomerManager.ID_TBC_DESCRIPTION:
                if (b1.getTbcDescription() == null && b2.getTbcDescription() != null) {
                    iReturn = -1;
                } else if (b1.getTbcDescription() == null && b2.getTbcDescription() == null) {
                    iReturn = 0;
                } else if (b1.getTbcDescription() != null && b2.getTbcDescription() == null) {
                    iReturn = 1;
                } else {
                    iReturn = b1.getTbcDescription().compareTo(b2.getTbcDescription());
                }
                break;
            case TbCustomerManager.ID_TBC_NAME:
                if (b1.getTbcName() == null && b2.getTbcName() != null) {
                    iReturn = -1;
                } else if (b1.getTbcName() == null && b2.getTbcName() == null) {
                    iReturn = 0;
                } else if (b1.getTbcName() != null && b2.getTbcName() == null) {
                    iReturn = 1;
                } else {
                    iReturn = b1.getTbcName().compareTo(b2.getTbcName());
                }
                break;
            case TbCustomerManager.ID_TBC_CUSTOMER_ID:
                if (b1.getTbcCustomerId() == null && b2.getTbcCustomerId() != null) {
                    iReturn = -1;
                } else if (b1.getTbcCustomerId() == null && b2.getTbcCustomerId() == null) {
                    iReturn = 0;
                } else if (b1.getTbcCustomerId() != null && b2.getTbcCustomerId() == null) {
                    iReturn = 1;
                } else {
                    iReturn = b1.getTbcCustomerId().compareTo(b2.getTbcCustomerId());
                }
                break;
            case TbCustomerManager.ID_TBC_ID:
                if (b1.getTbcId() == null && b2.getTbcId() != null) {
                    iReturn = -1;
                } else if (b1.getTbcId() == null && b2.getTbcId() == null) {
                    iReturn = 0;
                } else if (b1.getTbcId() != null && b2.getTbcId() == null) {
                    iReturn = 1;
                } else {
                    iReturn = b1.getTbcId().compareTo(b2.getTbcId());
                }
                break;
            default:
                throw new IllegalArgumentException("Type passed for the field is not supported");
        }

        return bReverse ? (-1 * iReturn) : iReturn;
    }}
