// ______________________________________________________
// Generated by sql2java - http://sql2java.sourceforge.net/
// jdbc driver used at code generation time: com.mysql.jdbc.Driver
//
// Please help us improve this tool by reporting:
// - problems and suggestions to
//   http://sourceforge.net/tracker/?group_id=54687
// - feedbacks and ideas on
//   http://sourceforge.net/forum/forum.php?forum_id=182208
// ______________________________________________________

package com.gwt.hris.db;

import com.gwt.hris.db.exception.DAOException;

/**
 * Listener that is notified of tb_kpi_group table changes.
 * @author sql2java
 */
public interface TbKpiGroupListener
{
    /**
     * Invoked just before inserting a TbKpiGroupBean record into the database.
     *
     * @param bean the TbKpiGroupBean that is about to be inserted
     */
    public void beforeInsert(TbKpiGroupBean bean) throws DAOException;


    /**
     * Invoked just after a TbKpiGroupBean record is inserted in the database.
     *
     * @param bean the TbKpiGroupBean that was just inserted
     */
    public void afterInsert(TbKpiGroupBean bean) throws DAOException;


    /**
     * Invoked just before updating a TbKpiGroupBean record in the database.
     *
     * @param bean the TbKpiGroupBean that is about to be updated
     */
    public void beforeUpdate(TbKpiGroupBean bean) throws DAOException;


    /**
     * Invoked just after updating a TbKpiGroupBean record in the database.
     *
     * @param bean the TbKpiGroupBean that was just updated
     */
    public void afterUpdate(TbKpiGroupBean bean) throws DAOException;


    /**
     * Invoked just before deleting a TbKpiGroupBean record in the database.
     *
     * @param bean the TbKpiGroupBean that is about to be deleted
     */
    public void beforeDelete(TbKpiGroupBean bean) throws DAOException;


    /**
     * Invoked just after deleting a TbKpiGroupBean record in the database.
     *
     * @param bean the TbKpiGroupBean that was just deleted
     */
    public void afterDelete(TbKpiGroupBean bean) throws DAOException;

}
