// ______________________________________________________
// Generated by sql2java - http://sql2java.sourceforge.net/
// jdbc driver used at code generation time: com.mysql.jdbc.Driver
//
// Please help us improve this tool by reporting:
// - problems and suggestions to
//   http://sourceforge.net/tracker/?group_id=54687
// - feedbacks and ideas on
//   http://sourceforge.net/forum/forum.php?forum_id=182208
// ______________________________________________________

package com.gwt.hris.db;

import java.util.Comparator;


/**
 * Comparator class is used to sort the TbLoginBean objects.
 * @author sql2java
 */
public class TbLoginComparator implements Comparator
{
    /**
     * Holds the field on which the comparison is performed.
     */
    private int iType;
    /**
     * Value that will contain the information about the order of the sort: normal or reversal.
     */
    private boolean bReverse;

    /**
     * Constructor class for TbLoginComparator.
     * <br>
     * Example:
     * <br>
     * <code>Arrays.sort(pArray, new TbLoginComparator(TbLoginManager.ID_TBE_ID, bReverse));<code>
     *
     * @param iType the field from which you want to sort
     * <br>
     * Possible values are:
     * <ul>
     *   <li>TbLoginManager.ID_TBE_ID
     *   <li>TbLoginManager.ID_TBAUG_ID
     *   <li>TbLoginManager.ID_TBL_STATUS
     *   <li>TbLoginManager.ID_TBL_PASSWORD
     *   <li>TbLoginManager.ID_TBL_USERNAME
     *   <li>TbLoginManager.ID_TBL_LOGIN_ID
     *   <li>TbLoginManager.ID_TBL_ID
     * </ul>
     */
    public TbLoginComparator(int iType)
    {
        this(iType, false);
    }

    /**
     * Constructor class for TbLoginComparator.
     * <br>
     * Example:
     * <br>
     * <code>Arrays.sort(pArray, new TbLoginComparator(TbLoginManager.ID_TBE_ID, bReverse));<code>
     *
     * @param iType the field from which you want to sort.
     * <br>
     * Possible values are:
     * <ul>
     *   <li>TbLoginManager.ID_TBE_ID
     *   <li>TbLoginManager.ID_TBAUG_ID
     *   <li>TbLoginManager.ID_TBL_STATUS
     *   <li>TbLoginManager.ID_TBL_PASSWORD
     *   <li>TbLoginManager.ID_TBL_USERNAME
     *   <li>TbLoginManager.ID_TBL_LOGIN_ID
     *   <li>TbLoginManager.ID_TBL_ID
     * </ul>
     *
     * @param bReverse set this value to true, if you want to reverse the sorting results
     */
    public TbLoginComparator(int iType, boolean bReverse)
    {
        this.iType = iType;
        this.bReverse = bReverse;
    }

    /**
     * Implementation of the compare method.
     */
    public int compare(Object pObj1, Object pObj2)
    {
        TbLoginBean b1 = (TbLoginBean)pObj1;
        TbLoginBean b2 = (TbLoginBean)pObj2;
        int iReturn = 0;
        switch(iType)
        {
            case TbLoginManager.ID_TBE_ID:
                if (b1.getTbeId() == null && b2.getTbeId() != null) {
                    iReturn = -1;
                } else if (b1.getTbeId() == null && b2.getTbeId() == null) {
                    iReturn = 0;
                } else if (b1.getTbeId() != null && b2.getTbeId() == null) {
                    iReturn = 1;
                } else {
                    iReturn = b1.getTbeId().compareTo(b2.getTbeId());
                }
                break;
            case TbLoginManager.ID_TBAUG_ID:
                if (b1.getTbaugId() == null && b2.getTbaugId() != null) {
                    iReturn = -1;
                } else if (b1.getTbaugId() == null && b2.getTbaugId() == null) {
                    iReturn = 0;
                } else if (b1.getTbaugId() != null && b2.getTbaugId() == null) {
                    iReturn = 1;
                } else {
                    iReturn = b1.getTbaugId().compareTo(b2.getTbaugId());
                }
                break;
            case TbLoginManager.ID_TBL_STATUS:
                if (b1.getTblStatus() == null && b2.getTblStatus() != null) {
                    iReturn = -1;
                } else if (b1.getTblStatus() == null && b2.getTblStatus() == null) {
                    iReturn = 0;
                } else if (b1.getTblStatus() != null && b2.getTblStatus() == null) {
                    iReturn = 1;
                } else {
                    iReturn = b1.getTblStatus().compareTo(b2.getTblStatus());
                }
                break;
            case TbLoginManager.ID_TBL_PASSWORD:
                if (b1.getTblPassword() == null && b2.getTblPassword() != null) {
                    iReturn = -1;
                } else if (b1.getTblPassword() == null && b2.getTblPassword() == null) {
                    iReturn = 0;
                } else if (b1.getTblPassword() != null && b2.getTblPassword() == null) {
                    iReturn = 1;
                } else {
                    iReturn = b1.getTblPassword().compareTo(b2.getTblPassword());
                }
                break;
            case TbLoginManager.ID_TBL_USERNAME:
                if (b1.getTblUsername() == null && b2.getTblUsername() != null) {
                    iReturn = -1;
                } else if (b1.getTblUsername() == null && b2.getTblUsername() == null) {
                    iReturn = 0;
                } else if (b1.getTblUsername() != null && b2.getTblUsername() == null) {
                    iReturn = 1;
                } else {
                    iReturn = b1.getTblUsername().compareTo(b2.getTblUsername());
                }
                break;
            case TbLoginManager.ID_TBL_LOGIN_ID:
                if (b1.getTblLoginId() == null && b2.getTblLoginId() != null) {
                    iReturn = -1;
                } else if (b1.getTblLoginId() == null && b2.getTblLoginId() == null) {
                    iReturn = 0;
                } else if (b1.getTblLoginId() != null && b2.getTblLoginId() == null) {
                    iReturn = 1;
                } else {
                    iReturn = b1.getTblLoginId().compareTo(b2.getTblLoginId());
                }
                break;
            case TbLoginManager.ID_TBL_ID:
                if (b1.getTblId() == null && b2.getTblId() != null) {
                    iReturn = -1;
                } else if (b1.getTblId() == null && b2.getTblId() == null) {
                    iReturn = 0;
                } else if (b1.getTblId() != null && b2.getTblId() == null) {
                    iReturn = 1;
                } else {
                    iReturn = b1.getTblId().compareTo(b2.getTblId());
                }
                break;
            default:
                throw new IllegalArgumentException("Type passed for the field is not supported");
        }

        return bReverse ? (-1 * iReturn) : iReturn;
    }}
