// ______________________________________________________
// Generated by sql2java - http://sql2java.sourceforge.net/
// jdbc driver used at code generation time: com.mysql.jdbc.Driver
//
// Please help us improve this tool by reporting:
// - problems and suggestions to
//   http://sourceforge.net/tracker/?group_id=54687
// - feedbacks and ideas on
//   http://sourceforge.net/forum/forum.php?forum_id=182208
// ______________________________________________________

package com.gwt.hris.db;

import com.gwt.hris.db.exception.DAOException;

/**
 * Listener that is notified of tb_negara table changes.
 * @author sql2java
 */
public interface TbNegaraListener
{
    /**
     * Invoked just before inserting a TbNegaraBean record into the database.
     *
     * @param bean the TbNegaraBean that is about to be inserted
     */
    public void beforeInsert(TbNegaraBean bean) throws DAOException;


    /**
     * Invoked just after a TbNegaraBean record is inserted in the database.
     *
     * @param bean the TbNegaraBean that was just inserted
     */
    public void afterInsert(TbNegaraBean bean) throws DAOException;


    /**
     * Invoked just before updating a TbNegaraBean record in the database.
     *
     * @param bean the TbNegaraBean that is about to be updated
     */
    public void beforeUpdate(TbNegaraBean bean) throws DAOException;


    /**
     * Invoked just after updating a TbNegaraBean record in the database.
     *
     * @param bean the TbNegaraBean that was just updated
     */
    public void afterUpdate(TbNegaraBean bean) throws DAOException;


    /**
     * Invoked just before deleting a TbNegaraBean record in the database.
     *
     * @param bean the TbNegaraBean that is about to be deleted
     */
    public void beforeDelete(TbNegaraBean bean) throws DAOException;


    /**
     * Invoked just after deleting a TbNegaraBean record in the database.
     *
     * @param bean the TbNegaraBean that was just deleted
     */
    public void afterDelete(TbNegaraBean bean) throws DAOException;

}
