// ______________________________________________________
// Generated by sql2java - http://sql2java.sourceforge.net/
// jdbc driver used at code generation time: com.mysql.jdbc.Driver
//
// Please help us improve this tool by reporting:
// - problems and suggestions to
//   http://sourceforge.net/tracker/?group_id=54687
// - feedbacks and ideas on
//   http://sourceforge.net/forum/forum.php?forum_id=182208
// ______________________________________________________

package com.gwt.hris.db;

import java.util.Comparator;


/**
 * Comparator class is used to sort the TbOrganizationBean objects.
 * @author sql2java
 */
public class TbOrganizationComparator implements Comparator
{
    /**
     * Holds the field on which the comparison is performed.
     */
    private int iType;
    /**
     * Value that will contain the information about the order of the sort: normal or reversal.
     */
    private boolean bReverse;

    /**
     * Constructor class for TbOrganizationComparator.
     * <br>
     * Example:
     * <br>
     * <code>Arrays.sort(pArray, new TbOrganizationComparator(TbOrganizationManager.ID_TBO_NAMA, bReverse));<code>
     *
     * @param iType the field from which you want to sort
     * <br>
     * Possible values are:
     * <ul>
     *   <li>TbOrganizationManager.ID_TBO_NAMA
     *   <li>TbOrganizationManager.ID_TBO_PARENT_ID
     *   <li>TbOrganizationManager.ID_TBP_ID
     *   <li>TbOrganizationManager.ID_TBO_ID
     * </ul>
     */
    public TbOrganizationComparator(int iType)
    {
        this(iType, false);
    }

    /**
     * Constructor class for TbOrganizationComparator.
     * <br>
     * Example:
     * <br>
     * <code>Arrays.sort(pArray, new TbOrganizationComparator(TbOrganizationManager.ID_TBO_NAMA, bReverse));<code>
     *
     * @param iType the field from which you want to sort.
     * <br>
     * Possible values are:
     * <ul>
     *   <li>TbOrganizationManager.ID_TBO_NAMA
     *   <li>TbOrganizationManager.ID_TBO_PARENT_ID
     *   <li>TbOrganizationManager.ID_TBP_ID
     *   <li>TbOrganizationManager.ID_TBO_ID
     * </ul>
     *
     * @param bReverse set this value to true, if you want to reverse the sorting results
     */
    public TbOrganizationComparator(int iType, boolean bReverse)
    {
        this.iType = iType;
        this.bReverse = bReverse;
    }

    /**
     * Implementation of the compare method.
     */
    public int compare(Object pObj1, Object pObj2)
    {
        TbOrganizationBean b1 = (TbOrganizationBean)pObj1;
        TbOrganizationBean b2 = (TbOrganizationBean)pObj2;
        int iReturn = 0;
        switch(iType)
        {
            case TbOrganizationManager.ID_TBO_NAMA:
                if (b1.getTboNama() == null && b2.getTboNama() != null) {
                    iReturn = -1;
                } else if (b1.getTboNama() == null && b2.getTboNama() == null) {
                    iReturn = 0;
                } else if (b1.getTboNama() != null && b2.getTboNama() == null) {
                    iReturn = 1;
                } else {
                    iReturn = b1.getTboNama().compareTo(b2.getTboNama());
                }
                break;
            case TbOrganizationManager.ID_TBO_PARENT_ID:
                if (b1.getTboParentId() == null && b2.getTboParentId() != null) {
                    iReturn = -1;
                } else if (b1.getTboParentId() == null && b2.getTboParentId() == null) {
                    iReturn = 0;
                } else if (b1.getTboParentId() != null && b2.getTboParentId() == null) {
                    iReturn = 1;
                } else {
                    iReturn = b1.getTboParentId().compareTo(b2.getTboParentId());
                }
                break;
            case TbOrganizationManager.ID_TBP_ID:
                if (b1.getTbpId() == null && b2.getTbpId() != null) {
                    iReturn = -1;
                } else if (b1.getTbpId() == null && b2.getTbpId() == null) {
                    iReturn = 0;
                } else if (b1.getTbpId() != null && b2.getTbpId() == null) {
                    iReturn = 1;
                } else {
                    iReturn = b1.getTbpId().compareTo(b2.getTbpId());
                }
                break;
            case TbOrganizationManager.ID_TBO_ID:
                if (b1.getTboId() == null && b2.getTboId() != null) {
                    iReturn = -1;
                } else if (b1.getTboId() == null && b2.getTboId() == null) {
                    iReturn = 0;
                } else if (b1.getTboId() != null && b2.getTboId() == null) {
                    iReturn = 1;
                } else {
                    iReturn = b1.getTboId().compareTo(b2.getTboId());
                }
                break;
            default:
                throw new IllegalArgumentException("Type passed for the field is not supported");
        }

        return bReverse ? (-1 * iReturn) : iReturn;
    }}
