// ______________________________________________________
// Generated by sql2java - http://sql2java.sourceforge.net/
// jdbc driver used at code generation time: com.mysql.jdbc.Driver
//
// Please help us improve this tool by reporting:
// - problems and suggestions to
//   http://sourceforge.net/tracker/?group_id=54687
// - feedbacks and ideas on
//   http://sourceforge.net/forum/forum.php?forum_id=182208
// ______________________________________________________

package com.gwt.hris.db;

import java.util.Comparator;


/**
 * Comparator class is used to sort the ViewEmployeeShiftBean objects.
 * @author sql2java
 */
public class ViewEmployeeShiftComparator implements Comparator
{
    /**
     * Holds the field on which the comparison is performed.
     */
    private int iType;
    /**
     * Value that will contain the information about the order of the sort: normal or reversal.
     */
    private boolean bReverse;

    /**
     * Constructor class for ViewEmployeeShiftComparator.
     * <br>
     * Example:
     * <br>
     * <code>Arrays.sort(pArray, new ViewEmployeeShiftComparator(ViewEmployeeShiftManager.ID_TBS_DEFAULT, bReverse));<code>
     *
     * @param iType the field from which you want to sort
     * <br>
     * Possible values are:
     * <ul>
     *   <li>ViewEmployeeShiftManager.ID_TBS_DEFAULT
     *   <li>ViewEmployeeShiftManager.ID_TBS_OUT_TIME
     *   <li>ViewEmployeeShiftManager.ID_TBS_IN_TIME
     *   <li>ViewEmployeeShiftManager.ID_TBS_NAME
     *   <li>ViewEmployeeShiftManager.ID_TBS_SHIFT_ID
     *   <li>ViewEmployeeShiftManager.ID_TBS_ID
     *   <li>ViewEmployeeShiftManager.ID_TBES_DATE
     *   <li>ViewEmployeeShiftManager.ID_TBE_NAME
     *   <li>ViewEmployeeShiftManager.ID_TBE_ID
     * </ul>
     */
    public ViewEmployeeShiftComparator(int iType)
    {
        this(iType, false);
    }

    /**
     * Constructor class for ViewEmployeeShiftComparator.
     * <br>
     * Example:
     * <br>
     * <code>Arrays.sort(pArray, new ViewEmployeeShiftComparator(ViewEmployeeShiftManager.ID_TBS_DEFAULT, bReverse));<code>
     *
     * @param iType the field from which you want to sort.
     * <br>
     * Possible values are:
     * <ul>
     *   <li>ViewEmployeeShiftManager.ID_TBS_DEFAULT
     *   <li>ViewEmployeeShiftManager.ID_TBS_OUT_TIME
     *   <li>ViewEmployeeShiftManager.ID_TBS_IN_TIME
     *   <li>ViewEmployeeShiftManager.ID_TBS_NAME
     *   <li>ViewEmployeeShiftManager.ID_TBS_SHIFT_ID
     *   <li>ViewEmployeeShiftManager.ID_TBS_ID
     *   <li>ViewEmployeeShiftManager.ID_TBES_DATE
     *   <li>ViewEmployeeShiftManager.ID_TBE_NAME
     *   <li>ViewEmployeeShiftManager.ID_TBE_ID
     * </ul>
     *
     * @param bReverse set this value to true, if you want to reverse the sorting results
     */
    public ViewEmployeeShiftComparator(int iType, boolean bReverse)
    {
        this.iType = iType;
        this.bReverse = bReverse;
    }

    /**
     * Implementation of the compare method.
     */
    public int compare(Object pObj1, Object pObj2)
    {
        ViewEmployeeShiftBean b1 = (ViewEmployeeShiftBean)pObj1;
        ViewEmployeeShiftBean b2 = (ViewEmployeeShiftBean)pObj2;
        int iReturn = 0;
        switch(iType)
        {
            case ViewEmployeeShiftManager.ID_TBS_DEFAULT:
                if (b1.getTbsDefault() == null && b2.getTbsDefault() != null) {
                    iReturn = -1;
                } else if (b1.getTbsDefault() == null && b2.getTbsDefault() == null) {
                    iReturn = 0;
                } else if (b1.getTbsDefault() != null && b2.getTbsDefault() == null) {
                    iReturn = 1;
                } else {
                    iReturn = b1.getTbsDefault().compareTo(b2.getTbsDefault());
                }
                break;
            case ViewEmployeeShiftManager.ID_TBS_OUT_TIME:
                if (b1.getTbsOutTime() == null && b2.getTbsOutTime() != null) {
                    iReturn = -1;
                } else if (b1.getTbsOutTime() == null && b2.getTbsOutTime() == null) {
                    iReturn = 0;
                } else if (b1.getTbsOutTime() != null && b2.getTbsOutTime() == null) {
                    iReturn = 1;
                } else {
                    iReturn = b1.getTbsOutTime().compareTo(b2.getTbsOutTime());
                }
                break;
            case ViewEmployeeShiftManager.ID_TBS_IN_TIME:
                if (b1.getTbsInTime() == null && b2.getTbsInTime() != null) {
                    iReturn = -1;
                } else if (b1.getTbsInTime() == null && b2.getTbsInTime() == null) {
                    iReturn = 0;
                } else if (b1.getTbsInTime() != null && b2.getTbsInTime() == null) {
                    iReturn = 1;
                } else {
                    iReturn = b1.getTbsInTime().compareTo(b2.getTbsInTime());
                }
                break;
            case ViewEmployeeShiftManager.ID_TBS_NAME:
                if (b1.getTbsName() == null && b2.getTbsName() != null) {
                    iReturn = -1;
                } else if (b1.getTbsName() == null && b2.getTbsName() == null) {
                    iReturn = 0;
                } else if (b1.getTbsName() != null && b2.getTbsName() == null) {
                    iReturn = 1;
                } else {
                    iReturn = b1.getTbsName().compareTo(b2.getTbsName());
                }
                break;
            case ViewEmployeeShiftManager.ID_TBS_SHIFT_ID:
                if (b1.getTbsShiftId() == null && b2.getTbsShiftId() != null) {
                    iReturn = -1;
                } else if (b1.getTbsShiftId() == null && b2.getTbsShiftId() == null) {
                    iReturn = 0;
                } else if (b1.getTbsShiftId() != null && b2.getTbsShiftId() == null) {
                    iReturn = 1;
                } else {
                    iReturn = b1.getTbsShiftId().compareTo(b2.getTbsShiftId());
                }
                break;
            case ViewEmployeeShiftManager.ID_TBS_ID:
                if (b1.getTbsId() == null && b2.getTbsId() != null) {
                    iReturn = -1;
                } else if (b1.getTbsId() == null && b2.getTbsId() == null) {
                    iReturn = 0;
                } else if (b1.getTbsId() != null && b2.getTbsId() == null) {
                    iReturn = 1;
                } else {
                    iReturn = b1.getTbsId().compareTo(b2.getTbsId());
                }
                break;
            case ViewEmployeeShiftManager.ID_TBES_DATE:
                if (b1.getTbesDate() == null && b2.getTbesDate() != null) {
                    iReturn = -1;
                } else if (b1.getTbesDate() == null && b2.getTbesDate() == null) {
                    iReturn = 0;
                } else if (b1.getTbesDate() != null && b2.getTbesDate() == null) {
                    iReturn = 1;
                } else {
                    iReturn = b1.getTbesDate().compareTo(b2.getTbesDate());
                }
                break;
            case ViewEmployeeShiftManager.ID_TBE_NAME:
                if (b1.getTbeName() == null && b2.getTbeName() != null) {
                    iReturn = -1;
                } else if (b1.getTbeName() == null && b2.getTbeName() == null) {
                    iReturn = 0;
                } else if (b1.getTbeName() != null && b2.getTbeName() == null) {
                    iReturn = 1;
                } else {
                    iReturn = b1.getTbeName().compareTo(b2.getTbeName());
                }
                break;
            case ViewEmployeeShiftManager.ID_TBE_ID:
                if (b1.getTbeId() == null && b2.getTbeId() != null) {
                    iReturn = -1;
                } else if (b1.getTbeId() == null && b2.getTbeId() == null) {
                    iReturn = 0;
                } else if (b1.getTbeId() != null && b2.getTbeId() == null) {
                    iReturn = 1;
                } else {
                    iReturn = b1.getTbeId().compareTo(b2.getTbeId());
                }
                break;
            default:
                throw new IllegalArgumentException("Type passed for the field is not supported");
        }

        return bReverse ? (-1 * iReturn) : iReturn;
    }}
