// ______________________________________________________
// Generated by sql2java - http://sql2java.sourceforge.net/
// jdbc driver used at code generation time: com.mysql.jdbc.Driver
//
// Please help us improve this tool by reporting:
// - problems and suggestions to
//   http://sourceforge.net/tracker/?group_id=54687
// - feedbacks and ideas on
//   http://sourceforge.net/forum/forum.php?forum_id=182208
// ______________________________________________________

package com.gwt.hris.db;

import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.sql.Types;
import java.util.ArrayList;
import java.util.List;

import org.slf4j.Logger;
import org.slf4j.LoggerFactory;

import com.gwt.hris.client.service.bean.ViewKpiBeanModel;
import com.gwt.hris.db.exception.DAOException;
import com.gwt.hris.db.exception.DataAccessException;
import com.gwt.hris.db.exception.ObjectRetrievalException;

/**
 * Handles database calls (save, load, count, etc...) for the view_kpi table.
 * @author sql2java
 */
public class ViewKpiManager 
{
	private Logger log = LoggerFactory.getLogger(this.getClass());

    /* set =QUERY for loadUsingTemplate */
    public static final int SEARCH_EXACT = 0;
    /* set %QUERY% for loadLikeTemplate */
    public static final int SEARCH_LIKE = 1;
    /* set %QUERY for loadLikeTemplate */
    public static final int SEARCH_STARTING_LIKE = 2;
    /* set QUERY% for loadLikeTemplate */
    public static final int SEARCH_ENDING_LIKE = 3;

    /**
     * Identify the tbe_id field.
     */
    public static final int ID_TBE_ID = 0;

    /**
     * Identify the tbk_bobot field.
     */
    public static final int ID_TBK_BOBOT = 1;

    /**
     * Identify the tbk_target_nilai_5 field.
     */
    public static final int ID_TBK_TARGET_NILAI_5 = 2;

    /**
     * Identify the tbk_target_nilai_4 field.
     */
    public static final int ID_TBK_TARGET_NILAI_4 = 3;

    /**
     * Identify the tbk_target_nilai_3 field.
     */
    public static final int ID_TBK_TARGET_NILAI_3 = 4;

    /**
     * Identify the tbk_target_nilai_2 field.
     */
    public static final int ID_TBK_TARGET_NILAI_2 = 5;

    /**
     * Identify the tbk_target_nilai_1 field.
     */
    public static final int ID_TBK_TARGET_NILAI_1 = 6;

    /**
     * Identify the tbk_description field.
     */
    public static final int ID_TBK_DESCRIPTION = 7;

    /**
     * Identify the tbk_id field.
     */
    public static final int ID_TBK_ID = 8;

    /**
     * Identify the tbe_name field.
     */
    public static final int ID_TBE_NAME = 9;

    /**
     * Identify the tbkg_name field.
     */
    public static final int ID_TBKG_NAME = 10;

    /**
     * Identify the tbkg_kpi_group_id field.
     */
    public static final int ID_TBKG_KPI_GROUP_ID = 11;

    /**
     * Identify the tbkg_id field.
     */
    public static final int ID_TBKG_ID = 12;

    /**
     * Contains all the full fields of the view_kpi table.
     */
    private static final String[] FULL_FIELD_NAMES =
    {
        "view_kpi.tbe_id"
        ,"view_kpi.tbk_bobot"
        ,"view_kpi.tbk_target_nilai_5"
        ,"view_kpi.tbk_target_nilai_4"
        ,"view_kpi.tbk_target_nilai_3"
        ,"view_kpi.tbk_target_nilai_2"
        ,"view_kpi.tbk_target_nilai_1"
        ,"view_kpi.tbk_description"
        ,"view_kpi.tbk_id"
        ,"view_kpi.tbe_name"
        ,"view_kpi.tbkg_name"
        ,"view_kpi.tbkg_kpi_group_id"
        ,"view_kpi.tbkg_id"
    };

    /**
     * Contains all the fields of the view_kpi table.
     */
    public static final String[] FIELD_NAMES =
    {
        "tbe_id"
        ,"tbk_bobot"
        ,"tbk_target_nilai_5"
        ,"tbk_target_nilai_4"
        ,"tbk_target_nilai_3"
        ,"tbk_target_nilai_2"
        ,"tbk_target_nilai_1"
        ,"tbk_description"
        ,"tbk_id"
        ,"tbe_name"
        ,"tbkg_name"
        ,"tbkg_kpi_group_id"
        ,"tbkg_id"
    };

    /**
     * Field that contains the comma separated fields of the view_kpi table.
     */
    public static final String ALL_FULL_FIELDS = "view_kpi.tbe_id"
                            + ",view_kpi.tbk_bobot"
                            + ",view_kpi.tbk_target_nilai_5"
                            + ",view_kpi.tbk_target_nilai_4"
                            + ",view_kpi.tbk_target_nilai_3"
                            + ",view_kpi.tbk_target_nilai_2"
                            + ",view_kpi.tbk_target_nilai_1"
                            + ",view_kpi.tbk_description"
                            + ",view_kpi.tbk_id"
                            + ",view_kpi.tbe_name"
                            + ",view_kpi.tbkg_name"
                            + ",view_kpi.tbkg_kpi_group_id"
                            + ",view_kpi.tbkg_id";

    /**
     * Field that contains the comma separated fields of the view_kpi table.
     */
    public static final String ALL_FIELDS = "tbe_id"
                            + ",tbk_bobot"
                            + ",tbk_target_nilai_5"
                            + ",tbk_target_nilai_4"
                            + ",tbk_target_nilai_3"
                            + ",tbk_target_nilai_2"
                            + ",tbk_target_nilai_1"
                            + ",tbk_description"
                            + ",tbk_id"
                            + ",tbe_name"
                            + ",tbkg_name"
                            + ",tbkg_kpi_group_id"
                            + ",tbkg_id";

    private static ViewKpiManager singleton = new ViewKpiManager();

    /**
     * Get the ViewKpiManager singleton.
     *
     * @return ViewKpiManager
     */
    public static ViewKpiManager getInstance()
    {
        return singleton;
    }


    /**
     * Creates a new ViewKpiBean instance.
     *
     * @return the new ViewKpiBean
     */
    public ViewKpiBean createViewKpiBean()
    {
        return new ViewKpiBean();
    }




    //////////////////////////////////////
    // LOAD ALL
    //////////////////////////////////////

    /**
     * Loads all the rows from view_kpi.
     *
     * @return an array of ViewKpiManager bean
     * @throws DAOException
     */
    //5
    public ViewKpiBean[] loadAll() throws DAOException
    {
        return this.loadUsingTemplate(null);
    }


    /**
     * Loads the given number of rows from view_kpi, given the start row.
     *
     * @param startRow the start row to be used (first row = 1, last row = -1)
     * @param numRows the number of rows to be retrieved (all rows = a negative number)
     * @return an array of ViewKpiManager bean
     * @throws DAOException
     */
    //6
    public ViewKpiBean[] loadAll(int startRow, int numRows) throws DAOException
    {
        return this.loadUsingTemplate(null, startRow, numRows);
    }

    //////////////////////////////////////
    // SQL 'WHERE' METHOD
    //////////////////////////////////////
    /**
     * Retrieves an array of ViewKpiBean given a sql 'where' clause.
     *
     * @param where the sql 'where' clause
     * @return the resulting ViewKpiBean table
     * @throws DAOException
     */
    //7
    public ViewKpiBean[] loadByWhere(String where) throws DAOException
    {
        return this.loadByWhere(where, null);
    }

    /**
     * Retrieves an array of ViewKpiBean given a sql where clause, and a list of fields.
     * It is up to you to pass the 'WHERE' in your where clausis.
     *
     * @param where the sql 'WHERE' clause
     * @param fieldList array of field's ID
     * @return the resulting ViewKpiBean table
     * @throws DAOException
     */
    //8
    public ViewKpiBean[] loadByWhere(String where, int[] fieldList) throws DAOException
    {
        return this.loadByWhere(where, fieldList, 1, -1);
    }

    /**
     * Retrieves an array of ViewKpiBean given a sql where clause and a list of fields, and startRow and numRows.
     * It is up to you to pass the 'WHERE' in your where clausis.
     *
     * @param where the sql 'where' clause
     * @param startRow the start row to be used (first row = 1, last row = -1)
     * @param numRows the number of rows to be retrieved (all rows = a negative number)
     * @param fieldList table of the field's associated constants
     * @return the resulting ViewKpiBean table
     * @throws DAOException
     */
    //9
    public ViewKpiBean[] loadByWhere(String where, int[] fieldList, int startRow, int numRows) throws DAOException
    {
        StringBuffer sql = new StringBuffer(128);
        if(fieldList == null) {
            sql.append("SELECT ").append(ALL_FIELDS).append(" FROM view_kpi ").append(where);
        } else
        {
            sql.append("SELECT ");
            for(int i = 0; i < fieldList.length; i++)
            {
                if(i != 0) {
                    sql.append(",");
                }
                sql.append(FULL_FIELD_NAMES[fieldList[i]]);
            }
            sql.append(" FROM view_kpi ");
            sql.append(where);
        }
        Connection c = null;
        Statement st = null;
        ResultSet rs =  null;
        log.debug("loadByWhere: " + sql);
        try
        {
            c = this.getConnection();
            st = c.createStatement(ResultSet.TYPE_SCROLL_INSENSITIVE, ResultSet.CONCUR_READ_ONLY);
            rs = st.executeQuery(sql.toString());
            return this.decodeResultSet(rs, fieldList, startRow, numRows);
        }
        catch(SQLException e)
        {
            throw new ObjectRetrievalException(e);
        }
        finally
        {
            sql = null;
            this.getManager().close(st, rs);
            this.freeConnection(c);
        }
    }


    /**
     * Deletes all rows from view_kpi table.
     * @return the number of deleted rows.
     * @throws DAOException
     */
    //10
    public int deleteAll() throws DAOException
    {
        return this.deleteByWhere("");
    }


    /**
     * Deletes rows from the view_kpi table using a 'where' clause.
     * It is up to you to pass the 'WHERE' in your where clausis.
     * <br>Attention, if 'WHERE' is omitted it will delete all records.
     *
     * @param where the sql 'where' clause
     * @return the number of deleted rows
     * @throws DAOException
     */
    //11
    public int deleteByWhere(String where) throws DAOException
    {
        Connection c = null;
        PreparedStatement ps = null;

        try
        {
            c = this.getConnection();
            StringBuffer sql = new StringBuffer("DELETE FROM view_kpi " + where);
            log.debug("deleteByWhere: " + sql);
            ps = c.prepareStatement(sql.toString());
            return ps.executeUpdate();
        }
        catch(SQLException e)
        {
            throw new DataAccessException(e);
        }
        finally
        {
            this.getManager().close(ps);
            this.freeConnection(c);
        }
    }

    //_____________________________________________________________________
    //
    // SAVE
    //_____________________________________________________________________
    /**
     * Saves the ViewKpiBean bean into the database.
     *
     * @param bean the ViewKpiBean bean to be saved
     * @return the inserted or updated bean
     * @throws DAOException
     */
    //12
    public ViewKpiBean save(ViewKpiBean bean) throws DAOException
    {
        if (bean.isNew()) {
            return this.insert(bean);
        } else {
            return this.update(bean);
        }
    }

    /**
     * Insert the ViewKpiBean bean into the database.
     *
     * @param bean the ViewKpiBean bean to be saved
     * @return the inserted bean
     * @throws DAOException
     */
    //13
    public ViewKpiBean insert(ViewKpiBean bean) throws DAOException
    {
        // mini checks
        if (!bean.isModified()) {
            return bean; // should not we log something ?
        }
        if (!bean.isNew()){
            return this.update(bean);
        }

        Connection c = null;
        PreparedStatement ps = null;
        StringBuffer sql = null;

        try
        {
            c = this.getConnection();
            this.beforeInsert(bean); // listener callback
            int _dirtyCount = 0;
            sql = new StringBuffer("INSERT into view_kpi (");

            if (bean.isTbeIdModified()) {
                if (_dirtyCount>0) {
                    sql.append(",");
                }
                sql.append("tbe_id");
                _dirtyCount++;
            }

            if (bean.isTbkBobotModified()) {
                if (_dirtyCount>0) {
                    sql.append(",");
                }
                sql.append("tbk_bobot");
                _dirtyCount++;
            }

            if (bean.isTbkTargetNilai5Modified()) {
                if (_dirtyCount>0) {
                    sql.append(",");
                }
                sql.append("tbk_target_nilai_5");
                _dirtyCount++;
            }

            if (bean.isTbkTargetNilai4Modified()) {
                if (_dirtyCount>0) {
                    sql.append(",");
                }
                sql.append("tbk_target_nilai_4");
                _dirtyCount++;
            }

            if (bean.isTbkTargetNilai3Modified()) {
                if (_dirtyCount>0) {
                    sql.append(",");
                }
                sql.append("tbk_target_nilai_3");
                _dirtyCount++;
            }

            if (bean.isTbkTargetNilai2Modified()) {
                if (_dirtyCount>0) {
                    sql.append(",");
                }
                sql.append("tbk_target_nilai_2");
                _dirtyCount++;
            }

            if (bean.isTbkTargetNilai1Modified()) {
                if (_dirtyCount>0) {
                    sql.append(",");
                }
                sql.append("tbk_target_nilai_1");
                _dirtyCount++;
            }

            if (bean.isTbkDescriptionModified()) {
                if (_dirtyCount>0) {
                    sql.append(",");
                }
                sql.append("tbk_description");
                _dirtyCount++;
            }

            if (bean.isTbkIdModified()) {
                if (_dirtyCount>0) {
                    sql.append(",");
                }
                sql.append("tbk_id");
                _dirtyCount++;
            }

            if (bean.isTbeNameModified()) {
                if (_dirtyCount>0) {
                    sql.append(",");
                }
                sql.append("tbe_name");
                _dirtyCount++;
            }

            if (bean.isTbkgNameModified()) {
                if (_dirtyCount>0) {
                    sql.append(",");
                }
                sql.append("tbkg_name");
                _dirtyCount++;
            }

            if (bean.isTbkgKpiGroupIdModified()) {
                if (_dirtyCount>0) {
                    sql.append(",");
                }
                sql.append("tbkg_kpi_group_id");
                _dirtyCount++;
            }

            if (bean.isTbkgIdModified()) {
                if (_dirtyCount>0) {
                    sql.append(",");
                }
                sql.append("tbkg_id");
                _dirtyCount++;
            }

            sql.append(") values (");
            if(_dirtyCount > 0) {
                sql.append("?");
                for(int i = 1; i < _dirtyCount; i++) {
                    sql.append(",?");
                }
            }
            sql.append(")");


            log.debug("insert : " + sql.toString());

            ps = c.prepareStatement(sql.toString(), Statement.RETURN_GENERATED_KEYS);

            this.fillPreparedStatement(ps, bean, SEARCH_EXACT);

            ps.executeUpdate();

            bean.isNew(false);
            bean.resetIsModified();
            this.afterInsert(bean); // listener callback
            return bean;
        }
        catch(SQLException e)
        {
            throw new DataAccessException(e);
        }
        finally
        {
            sql = null;
            this.getManager().close(ps);
            this.freeConnection(c);
        }
    }

    /**
     * Update the ViewKpiBean bean record in the database according to the changes.
     *
     * @param bean the ViewKpiBean bean to be updated
     * @return the updated bean
     * @throws DAOException
     */
    //14
    public ViewKpiBean update(ViewKpiBean bean) throws DAOException
    {
        // mini checks
        if (!bean.isModified()) {
            return bean; // should not we log something ?
        }
        if (bean.isNew()){
            return this.insert(bean);
        }

        Connection c = null;
        PreparedStatement ps = null;
        StringBuffer sql = null;

        try
        {
            c = this.getConnection();


            this.beforeUpdate(bean); // listener callback
            sql = new StringBuffer("UPDATE view_kpi SET ");
            boolean useComma=false;

            if (bean.isTbeIdModified()) {
                if (useComma) {
                    sql.append(", ");
                } else {
                    useComma=true;
                }
                sql.append("tbe_id=?");
            }

            if (bean.isTbkBobotModified()) {
                if (useComma) {
                    sql.append(", ");
                } else {
                    useComma=true;
                }
                sql.append("tbk_bobot=?");
            }

            if (bean.isTbkTargetNilai5Modified()) {
                if (useComma) {
                    sql.append(", ");
                } else {
                    useComma=true;
                }
                sql.append("tbk_target_nilai_5=?");
            }

            if (bean.isTbkTargetNilai4Modified()) {
                if (useComma) {
                    sql.append(", ");
                } else {
                    useComma=true;
                }
                sql.append("tbk_target_nilai_4=?");
            }

            if (bean.isTbkTargetNilai3Modified()) {
                if (useComma) {
                    sql.append(", ");
                } else {
                    useComma=true;
                }
                sql.append("tbk_target_nilai_3=?");
            }

            if (bean.isTbkTargetNilai2Modified()) {
                if (useComma) {
                    sql.append(", ");
                } else {
                    useComma=true;
                }
                sql.append("tbk_target_nilai_2=?");
            }

            if (bean.isTbkTargetNilai1Modified()) {
                if (useComma) {
                    sql.append(", ");
                } else {
                    useComma=true;
                }
                sql.append("tbk_target_nilai_1=?");
            }

            if (bean.isTbkDescriptionModified()) {
                if (useComma) {
                    sql.append(", ");
                } else {
                    useComma=true;
                }
                sql.append("tbk_description=?");
            }

            if (bean.isTbkIdModified()) {
                if (useComma) {
                    sql.append(", ");
                } else {
                    useComma=true;
                }
                sql.append("tbk_id=?");
            }

            if (bean.isTbeNameModified()) {
                if (useComma) {
                    sql.append(", ");
                } else {
                    useComma=true;
                }
                sql.append("tbe_name=?");
            }

            if (bean.isTbkgNameModified()) {
                if (useComma) {
                    sql.append(", ");
                } else {
                    useComma=true;
                }
                sql.append("tbkg_name=?");
            }

            if (bean.isTbkgKpiGroupIdModified()) {
                if (useComma) {
                    sql.append(", ");
                } else {
                    useComma=true;
                }
                sql.append("tbkg_kpi_group_id=?");
            }

            if (bean.isTbkgIdModified()) {
                if (useComma) {
                    sql.append(", ");
                } else {
                    useComma=true;
                }
                sql.append("tbkg_id=?");
            }
            sql.append("");
            log.debug("update : " + sql.toString());
            ps = c.prepareStatement(sql.toString(),
                                    ResultSet.TYPE_SCROLL_INSENSITIVE,
                                    ResultSet.CONCUR_READ_ONLY);

            int _dirtyCount = this.fillPreparedStatement(ps, bean, SEARCH_EXACT);

            if (_dirtyCount == 0) {
                log.debug("The bean to look is not initialized... do not update.");
                return bean;
            }

            ps.executeUpdate();
            bean.resetIsModified();
            this.afterUpdate(bean); // listener callback

            return bean;
        }
        catch(SQLException e)
        {
            throw new DataAccessException(e);
        }
        finally
        {
            sql = null;
            this.getManager().close(ps);
            this.freeConnection(c);
        }
    }

    /**
     * Saves an array of ViewKpiBean beans into the database.
     *
     * @param beans the ViewKpiBean bean table to be saved
     * @return the saved ViewKpiBean array.
     * @throws DAOException
     */
    //15
    public ViewKpiBean[] save(ViewKpiBean[] beans) throws DAOException
    {
        for (int iIndex = 0; iIndex < beans.length; iIndex ++)
        {
            this.save(beans[iIndex]);
        }
        return beans;
    }

    /**
     * Insert an array of ViewKpiBean beans into the database.
     *
     * @param beans the ViewKpiBean bean table to be inserted
     * @return the saved ViewKpiBean array.
     * @throws DAOException
     */
    //16
    public ViewKpiBean[] insert(ViewKpiBean[] beans) throws DAOException
    {
        return this.save(beans);
    }

    /**
     * Updates an array of ViewKpiBean beans into the database.
     *
     * @param beans the ViewKpiBean bean table to be inserted
     * @return the saved ViewKpiBean array.
     * @throws DAOException
     */
    //17
    public ViewKpiBean[] update(ViewKpiBean[] beans) throws DAOException
    {
        return this.save(beans);
    }



    //_____________________________________________________________________
    //
    // USING TEMPLATE
    //_____________________________________________________________________
    /**
     * Loads a unique ViewKpiBean bean from a template one giving a c
     *
     * @param bean the ViewKpiBean bean to look for
     * @return the bean matching the template
     * @throws DAOException
     */
    //18
    public ViewKpiBean loadUniqueUsingTemplate(ViewKpiBean bean) throws DAOException
    {
         ViewKpiBean[] beans = this.loadUsingTemplate(bean);
         if (beans.length == 0) {
             return null;
         }
         if (beans.length > 1) {
             throw new ObjectRetrievalException("More than one element !!");
         }
         return beans[0];
     }

    /**
     * Loads an array of ViewKpiBean from a template one.
     *
     * @param bean the ViewKpiBean template to look for
     * @return all the ViewKpiBean matching the template
     * @throws DAOException
     */
    //19
    public ViewKpiBean[] loadUsingTemplate(ViewKpiBean bean) throws DAOException
    {
        return this.loadUsingTemplate(bean, 1, -1);
    }

    /**
     * Loads an array of ViewKpiBean from a template one, given the start row and number of rows.
     *
     * @param bean the ViewKpiBean template to look for
     * @param startRow the start row to be used (first row = 1, last row=-1)
     * @param numRows the number of rows to be retrieved (all rows = a negative number)
     * @return all the ViewKpiBean matching the template
     * @throws DAOException
     */
    //20
    public ViewKpiBean[] loadUsingTemplate(ViewKpiBean bean, int startRow, int numRows) throws DAOException
    {
        return this.loadUsingTemplate(bean, startRow, numRows, SEARCH_EXACT);
    }

    /**
     * Loads an array of ViewKpiBean from a template one, given the start row and number of rows.
     *
     * @param bean the ViewKpiBean template to look for
     * @param startRow the start row to be used (first row = 1, last row=-1)
     * @param numRows the number of rows to be retrieved (all rows = a negative number)
     * @param searchType exact ?  like ? starting like ?
     * @return all the ViewKpiBean matching the template
     * @throws DAOException
     */
    //20
    public ViewKpiBean[] loadUsingTemplate(ViewKpiBean bean, int startRow, int numRows, int searchType) throws DAOException
    {
        log.debug("loadUsingTemplate startRow:" + startRow + ", numRows:" + numRows + ", searchType:" + searchType);
        Connection c = null;
        PreparedStatement ps = null;
        StringBuffer sql = new StringBuffer(128);
        sql.append("SELECT ").append(ALL_FIELDS).append(" FROM view_kpi ");
        StringBuffer sqlWhere = new StringBuffer("");

        try
        {
            if (this.fillWhere(sqlWhere, bean, searchType) > 0) {
                sql.append(" WHERE ").append(sqlWhere);
            } else {
               log.debug("The bean to look is not initialized... loading all");
            }
            log.debug("loadUsingTemplate: " + sql.toString());

            c = this.getConnection();
            int scrollType = ResultSet.TYPE_SCROLL_INSENSITIVE;
            if (startRow != 1) {
                scrollType = ResultSet.TYPE_SCROLL_SENSITIVE;
            }
            ps = c.prepareStatement(sql.toString(),
                                    scrollType,
                                    ResultSet.CONCUR_READ_ONLY);
            this.fillPreparedStatement(ps, bean, searchType);

            ps.executeQuery();
            return this.loadByPreparedStatement(ps, null, startRow, numRows);
        }
        catch(SQLException e)
        {
            throw new ObjectRetrievalException(e);
        }
        finally
        {
            this.getManager().close(ps);
            this.freeConnection(c);
            sql = null;
            sqlWhere = null;
        }
    }

    /**
     * Deletes rows using a ViewKpiBean template.
     *
     * @param bean the ViewKpiBean object(s) to be deleted
     * @return the number of deleted objects
     * @throws DAOException
     */
    //21
    public int deleteUsingTemplate(ViewKpiBean bean) throws DAOException
    {
        Connection c = null;
        PreparedStatement ps = null;
        StringBuffer sql = new StringBuffer("DELETE FROM view_kpi ");
        StringBuffer sqlWhere = new StringBuffer("");

        try
        {
            this.beforeDelete(bean); // listener callback
            if (this.fillWhere(sqlWhere, bean, SEARCH_EXACT) > 0) {
                sql.append(" WHERE ").append(sqlWhere);
            } else {
               log.debug("The bean to look is not initialized... deleting all");
            }
            log.debug("deleteUsingTemplate: " + sql.toString());

            c = this.getConnection();
            ps = c.prepareStatement(sql.toString(),
                                    ResultSet.TYPE_SCROLL_INSENSITIVE,
                                    ResultSet.CONCUR_READ_ONLY);
            this.fillPreparedStatement(ps, bean, SEARCH_EXACT);

            int _rows = ps.executeUpdate();
            this.afterDelete(bean); // listener callback
            return _rows;
        }
        catch(SQLException e)
        {
            throw new DataAccessException(e);
        }
        finally
        {
            this.getManager().close(ps);
            this.freeConnection(c);
            sql = null;
            sqlWhere = null;
        }
    }



    //_____________________________________________________________________
    //
    // COUNT
    //_____________________________________________________________________

    /**
     * Retrieves the number of rows of the table view_kpi.
     *
     * @return the number of rows returned
     * @throws DAOException
     */
    //24
    public int countAll() throws DAOException
    {
        return this.countWhere("");
    }

    /**
     * Retrieves the number of rows of the table view_kpi with a 'where' clause.
     * It is up to you to pass the 'WHERE' in your where clausis.
     *
     * @param where the restriction clause
     * @return the number of rows returned
     * @throws DAOException
     */
    //25
    public int countWhere(String where) throws DAOException
    {
        String sql = "SELECT COUNT(*) AS MCOUNT FROM view_kpi " + where;
        log.debug("countWhere: " + sql);
        Connection c = null;
        Statement st = null;
        ResultSet rs =  null;
        try
        {
            int iReturn = -1;
            c = this.getConnection();
            st = c.createStatement();
            rs =  st.executeQuery(sql);
            if (rs.next())
            {
                iReturn = rs.getInt("MCOUNT");
            }
            if (iReturn != -1) {
                return iReturn;
            }
        }
        catch(SQLException e)
        {
            throw new DataAccessException(e);
        }
        finally
        {
            this.getManager().close(st, rs);
            this.freeConnection(c);
            sql = null;
        }
        throw new DataAccessException("Error in countWhere where=[" + where + "]");
    }

    /**
     * Retrieves the number of rows of the table view_kpi with a prepared statement.
     *
     * @param ps the PreparedStatement to be used
     * @return the number of rows returned
     * @throws DAOException
     */
    //26
    private int countByPreparedStatement(PreparedStatement ps) throws DAOException
    {
        ResultSet rs =  null;
        try
        {
            int iReturn = -1;
            rs = ps.executeQuery();
            if (rs.next()) {
                iReturn = rs.getInt("MCOUNT");
            }
            if (iReturn != -1) {
                return iReturn;
            }
        }
        catch(SQLException e)
        {
            throw new DataAccessException(e);
        }
        finally
        {
            this.getManager().close(rs);
        }
       throw new DataAccessException("Error in countByPreparedStatement");
    }

    /**
     * count the number of elements of a specific ViewKpiBean bean
     *
     * @param bean the ViewKpiBean bean to look for ant count
     * @return the number of rows returned
     * @throws DAOException
     */
    //27
    public int countUsingTemplate(ViewKpiBean bean) throws DAOException
    {
        return this.countUsingTemplate(bean, -1, -1);
    }

    /**
     * count the number of elements of a specific ViewKpiBean bean , given the start row and number of rows.
     *
     * @param bean the ViewKpiBean template to look for and count
     * @param startRow the start row to be used (first row = 1, last row=-1)
     * @param numRows the number of rows to be retrieved (all rows = a negative number)
     * @return the number of rows returned
     * @throws DAOException
     */
    //20
    public int countUsingTemplate(ViewKpiBean bean, int startRow, int numRows) throws DAOException
    {
        return this.countUsingTemplate(bean, startRow, numRows, SEARCH_EXACT);
    }

    /**
     * count the number of elements of a specific ViewKpiBean bean given the start row and number of rows and the search type
     *
     * @param bean the ViewKpiBean template to look for
     * @param startRow the start row to be used (first row = 1, last row=-1)
     * @param numRows the number of rows to be retrieved (all rows = a negative number)
     * @param searchType exact ?  like ? starting like ?
     * @return the number of rows returned
     * @throws DAOException
     */
    //20
    public int countUsingTemplate(ViewKpiBean bean, int startRow, int numRows, int searchType) throws DAOException
    {
        Connection c = null;
        PreparedStatement ps = null;
        StringBuffer sql = new StringBuffer("SELECT COUNT(*) AS MCOUNT FROM view_kpi");
        StringBuffer sqlWhere = new StringBuffer("");

        try
        {
            if (this.fillWhere(sqlWhere, bean, SEARCH_EXACT) > 0) {
                sql.append(" WHERE ").append(sqlWhere);
            } else {
                log.debug("The bean to look is not initialized... counting all...");
            }
            log.debug("countUsingTemplate: " + sql.toString());

            c = this.getConnection();
            ps = c.prepareStatement(sql.toString(),
                                    ResultSet.TYPE_SCROLL_INSENSITIVE,
                                    ResultSet.CONCUR_READ_ONLY);
            this.fillPreparedStatement(ps, bean, searchType);

            return this.countByPreparedStatement(ps);
        }
        catch(SQLException e)
        {
            throw new DataAccessException(e);
        }
        finally
        {
            this.getManager().close(ps);
            this.freeConnection(c);
            sql = null;
            sqlWhere = null;
        }
    }

    //


    /**
     * fills the given stringbuffer with the sql where clausis constructed using the bean and the search type
     * @param sqlWhere the stringbuffer that will be filled
     * @param bean the bean to use for creating the where clausis
     * @param searchType exact ?  like ? starting like ?
     * @return the number of clausis returned
     */
    protected int fillWhere(StringBuffer sqlWhere, ViewKpiBean bean, int searchType)
    {
        if (bean == null) {
            return 0;
        }
        int _dirtyCount = 0;
        String sqlEqualsOperation = "=";
        if (searchType != SEARCH_EXACT) {
            sqlEqualsOperation = " like ";
        }
        try
        {
            if (bean.isTbeIdModified()) {
                _dirtyCount ++;
                if (bean.getTbeId() == null) {
                    sqlWhere.append((sqlWhere.length() == 0) ? " " : " AND ").append("tbe_id IS NULL");
                } else {
                    sqlWhere.append((sqlWhere.length() == 0) ? " " : " AND ").append("tbe_id = ?");
                }
            }
            if (bean.isTbkBobotModified()) {
                _dirtyCount ++;
                if (bean.getTbkBobot() == null) {
                    sqlWhere.append((sqlWhere.length() == 0) ? " " : " AND ").append("tbk_bobot IS NULL");
                } else {
                    sqlWhere.append((sqlWhere.length() == 0) ? " " : " AND ").append("tbk_bobot = ?");
                }
            }
            if (bean.isTbkTargetNilai5Modified()) {
                _dirtyCount ++;
                if (bean.getTbkTargetNilai5() == null) {
                    sqlWhere.append((sqlWhere.length() == 0) ? " " : " AND ").append("tbk_target_nilai_5 IS NULL");
                } else {
                    sqlWhere.append((sqlWhere.length() == 0) ? " " : " AND ").append("tbk_target_nilai_5 ").append(sqlEqualsOperation).append("?");
                }
            }
            if (bean.isTbkTargetNilai4Modified()) {
                _dirtyCount ++;
                if (bean.getTbkTargetNilai4() == null) {
                    sqlWhere.append((sqlWhere.length() == 0) ? " " : " AND ").append("tbk_target_nilai_4 IS NULL");
                } else {
                    sqlWhere.append((sqlWhere.length() == 0) ? " " : " AND ").append("tbk_target_nilai_4 ").append(sqlEqualsOperation).append("?");
                }
            }
            if (bean.isTbkTargetNilai3Modified()) {
                _dirtyCount ++;
                if (bean.getTbkTargetNilai3() == null) {
                    sqlWhere.append((sqlWhere.length() == 0) ? " " : " AND ").append("tbk_target_nilai_3 IS NULL");
                } else {
                    sqlWhere.append((sqlWhere.length() == 0) ? " " : " AND ").append("tbk_target_nilai_3 ").append(sqlEqualsOperation).append("?");
                }
            }
            if (bean.isTbkTargetNilai2Modified()) {
                _dirtyCount ++;
                if (bean.getTbkTargetNilai2() == null) {
                    sqlWhere.append((sqlWhere.length() == 0) ? " " : " AND ").append("tbk_target_nilai_2 IS NULL");
                } else {
                    sqlWhere.append((sqlWhere.length() == 0) ? " " : " AND ").append("tbk_target_nilai_2 ").append(sqlEqualsOperation).append("?");
                }
            }
            if (bean.isTbkTargetNilai1Modified()) {
                _dirtyCount ++;
                if (bean.getTbkTargetNilai1() == null) {
                    sqlWhere.append((sqlWhere.length() == 0) ? " " : " AND ").append("tbk_target_nilai_1 IS NULL");
                } else {
                    sqlWhere.append((sqlWhere.length() == 0) ? " " : " AND ").append("tbk_target_nilai_1 ").append(sqlEqualsOperation).append("?");
                }
            }
            if (bean.isTbkDescriptionModified()) {
                _dirtyCount ++;
                if (bean.getTbkDescription() == null) {
                    sqlWhere.append((sqlWhere.length() == 0) ? " " : " AND ").append("tbk_description IS NULL");
                } else {
                    sqlWhere.append((sqlWhere.length() == 0) ? " " : " AND ").append("tbk_description ").append(sqlEqualsOperation).append("?");
                }
            }
            if (bean.isTbkIdModified()) {
                _dirtyCount ++;
                if (bean.getTbkId() == null) {
                    sqlWhere.append((sqlWhere.length() == 0) ? " " : " AND ").append("tbk_id IS NULL");
                } else {
                    sqlWhere.append((sqlWhere.length() == 0) ? " " : " AND ").append("tbk_id = ?");
                }
            }
            if (bean.isTbeNameModified()) {
                _dirtyCount ++;
                if (bean.getTbeName() == null) {
                    sqlWhere.append((sqlWhere.length() == 0) ? " " : " AND ").append("tbe_name IS NULL");
                } else {
                    sqlWhere.append((sqlWhere.length() == 0) ? " " : " AND ").append("tbe_name ").append(sqlEqualsOperation).append("?");
                }
            }
            if (bean.isTbkgNameModified()) {
                _dirtyCount ++;
                if (bean.getTbkgName() == null) {
                    sqlWhere.append((sqlWhere.length() == 0) ? " " : " AND ").append("tbkg_name IS NULL");
                } else {
                    sqlWhere.append((sqlWhere.length() == 0) ? " " : " AND ").append("tbkg_name ").append(sqlEqualsOperation).append("?");
                }
            }
            if (bean.isTbkgKpiGroupIdModified()) {
                _dirtyCount ++;
                if (bean.getTbkgKpiGroupId() == null) {
                    sqlWhere.append((sqlWhere.length() == 0) ? " " : " AND ").append("tbkg_kpi_group_id IS NULL");
                } else {
                    sqlWhere.append((sqlWhere.length() == 0) ? " " : " AND ").append("tbkg_kpi_group_id ").append(sqlEqualsOperation).append("?");
                }
            }
            if (bean.isTbkgIdModified()) {
                _dirtyCount ++;
                if (bean.getTbkgId() == null) {
                    sqlWhere.append((sqlWhere.length() == 0) ? " " : " AND ").append("tbkg_id IS NULL");
                } else {
                    sqlWhere.append((sqlWhere.length() == 0) ? " " : " AND ").append("tbkg_id = ?");
                }
            }
        }
        finally
        {
            sqlEqualsOperation = null;
        }
        return _dirtyCount;
    }

    /**
     * fill the given prepared statement with the bean values and a search type
     * @param ps the preparedStatement that will be filled
     * @param bean the bean to use for creating the where clausis
     * @param searchType exact ?  like ? starting like ?
     * @return the number of clausis returned
     * @throws DAOException
     */
    protected int fillPreparedStatement(PreparedStatement ps, ViewKpiBean bean, int searchType) throws DAOException
    {
        if (bean == null) {
            return 0;
        }
        int _dirtyCount = 0;
        try
        {
            if (bean.isTbeIdModified()) {
                log.debug("Setting for " + _dirtyCount + " [" + bean.getTbeId() + "]");
                if (bean.getTbeId() == null) { ps.setNull(++_dirtyCount, Types.INTEGER); } else { Manager.setInteger(ps, ++_dirtyCount, bean.getTbeId()); }
            }
            if (bean.isTbkBobotModified()) {
                log.debug("Setting for " + _dirtyCount + " [" + bean.getTbkBobot() + "]");
                if (bean.getTbkBobot() == null) { ps.setNull(++_dirtyCount, Types.INTEGER); } else { Manager.setInteger(ps, ++_dirtyCount, bean.getTbkBobot()); }
            }
            if (bean.isTbkTargetNilai5Modified()) {
                switch (searchType){
                    case SEARCH_EXACT:
                        log.debug("Setting for " + _dirtyCount + " [" + bean.getTbkTargetNilai5() + "]");
                        if (bean.getTbkTargetNilai5() == null) { ps.setNull(++_dirtyCount, Types.VARCHAR); } else { ps.setString(++_dirtyCount, bean.getTbkTargetNilai5()); }
                        break;
                    case SEARCH_LIKE:
                        log.debug("Setting for " + _dirtyCount + " [%" + bean.getTbkTargetNilai5() + "%]");
                        ps.setString(++_dirtyCount, "%" + bean.getTbkTargetNilai5() + "%");
                        break;
                    case SEARCH_STARTING_LIKE:
                        log.debug("Setting for " + _dirtyCount + " [" + bean.getTbkTargetNilai5() + "%]");
                        ps.setString(++_dirtyCount, "%" + bean.getTbkTargetNilai5());
                        break;
                    case SEARCH_ENDING_LIKE:
                        log.debug("Setting for " + _dirtyCount + " [%" + bean.getTbkTargetNilai5() + "]");
                        if (bean.getTbkTargetNilai5() + "%" == null) { ps.setNull(++_dirtyCount, Types.VARCHAR); } else { ps.setString(++_dirtyCount, bean.getTbkTargetNilai5() + "%"); }
                        break;
                    default:
                        throw new DAOException("Unknown search type " + searchType);
                }
            }
            if (bean.isTbkTargetNilai4Modified()) {
                switch (searchType){
                    case SEARCH_EXACT:
                        log.debug("Setting for " + _dirtyCount + " [" + bean.getTbkTargetNilai4() + "]");
                        if (bean.getTbkTargetNilai4() == null) { ps.setNull(++_dirtyCount, Types.VARCHAR); } else { ps.setString(++_dirtyCount, bean.getTbkTargetNilai4()); }
                        break;
                    case SEARCH_LIKE:
                        log.debug("Setting for " + _dirtyCount + " [%" + bean.getTbkTargetNilai4() + "%]");
                        ps.setString(++_dirtyCount, "%" + bean.getTbkTargetNilai4() + "%");
                        break;
                    case SEARCH_STARTING_LIKE:
                        log.debug("Setting for " + _dirtyCount + " [" + bean.getTbkTargetNilai4() + "%]");
                        ps.setString(++_dirtyCount, "%" + bean.getTbkTargetNilai4());
                        break;
                    case SEARCH_ENDING_LIKE:
                        log.debug("Setting for " + _dirtyCount + " [%" + bean.getTbkTargetNilai4() + "]");
                        if (bean.getTbkTargetNilai4() + "%" == null) { ps.setNull(++_dirtyCount, Types.VARCHAR); } else { ps.setString(++_dirtyCount, bean.getTbkTargetNilai4() + "%"); }
                        break;
                    default:
                        throw new DAOException("Unknown search type " + searchType);
                }
            }
            if (bean.isTbkTargetNilai3Modified()) {
                switch (searchType){
                    case SEARCH_EXACT:
                        log.debug("Setting for " + _dirtyCount + " [" + bean.getTbkTargetNilai3() + "]");
                        if (bean.getTbkTargetNilai3() == null) { ps.setNull(++_dirtyCount, Types.VARCHAR); } else { ps.setString(++_dirtyCount, bean.getTbkTargetNilai3()); }
                        break;
                    case SEARCH_LIKE:
                        log.debug("Setting for " + _dirtyCount + " [%" + bean.getTbkTargetNilai3() + "%]");
                        ps.setString(++_dirtyCount, "%" + bean.getTbkTargetNilai3() + "%");
                        break;
                    case SEARCH_STARTING_LIKE:
                        log.debug("Setting for " + _dirtyCount + " [" + bean.getTbkTargetNilai3() + "%]");
                        ps.setString(++_dirtyCount, "%" + bean.getTbkTargetNilai3());
                        break;
                    case SEARCH_ENDING_LIKE:
                        log.debug("Setting for " + _dirtyCount + " [%" + bean.getTbkTargetNilai3() + "]");
                        if (bean.getTbkTargetNilai3() + "%" == null) { ps.setNull(++_dirtyCount, Types.VARCHAR); } else { ps.setString(++_dirtyCount, bean.getTbkTargetNilai3() + "%"); }
                        break;
                    default:
                        throw new DAOException("Unknown search type " + searchType);
                }
            }
            if (bean.isTbkTargetNilai2Modified()) {
                switch (searchType){
                    case SEARCH_EXACT:
                        log.debug("Setting for " + _dirtyCount + " [" + bean.getTbkTargetNilai2() + "]");
                        if (bean.getTbkTargetNilai2() == null) { ps.setNull(++_dirtyCount, Types.VARCHAR); } else { ps.setString(++_dirtyCount, bean.getTbkTargetNilai2()); }
                        break;
                    case SEARCH_LIKE:
                        log.debug("Setting for " + _dirtyCount + " [%" + bean.getTbkTargetNilai2() + "%]");
                        ps.setString(++_dirtyCount, "%" + bean.getTbkTargetNilai2() + "%");
                        break;
                    case SEARCH_STARTING_LIKE:
                        log.debug("Setting for " + _dirtyCount + " [" + bean.getTbkTargetNilai2() + "%]");
                        ps.setString(++_dirtyCount, "%" + bean.getTbkTargetNilai2());
                        break;
                    case SEARCH_ENDING_LIKE:
                        log.debug("Setting for " + _dirtyCount + " [%" + bean.getTbkTargetNilai2() + "]");
                        if (bean.getTbkTargetNilai2() + "%" == null) { ps.setNull(++_dirtyCount, Types.VARCHAR); } else { ps.setString(++_dirtyCount, bean.getTbkTargetNilai2() + "%"); }
                        break;
                    default:
                        throw new DAOException("Unknown search type " + searchType);
                }
            }
            if (bean.isTbkTargetNilai1Modified()) {
                switch (searchType){
                    case SEARCH_EXACT:
                        log.debug("Setting for " + _dirtyCount + " [" + bean.getTbkTargetNilai1() + "]");
                        if (bean.getTbkTargetNilai1() == null) { ps.setNull(++_dirtyCount, Types.VARCHAR); } else { ps.setString(++_dirtyCount, bean.getTbkTargetNilai1()); }
                        break;
                    case SEARCH_LIKE:
                        log.debug("Setting for " + _dirtyCount + " [%" + bean.getTbkTargetNilai1() + "%]");
                        ps.setString(++_dirtyCount, "%" + bean.getTbkTargetNilai1() + "%");
                        break;
                    case SEARCH_STARTING_LIKE:
                        log.debug("Setting for " + _dirtyCount + " [" + bean.getTbkTargetNilai1() + "%]");
                        ps.setString(++_dirtyCount, "%" + bean.getTbkTargetNilai1());
                        break;
                    case SEARCH_ENDING_LIKE:
                        log.debug("Setting for " + _dirtyCount + " [%" + bean.getTbkTargetNilai1() + "]");
                        if (bean.getTbkTargetNilai1() + "%" == null) { ps.setNull(++_dirtyCount, Types.VARCHAR); } else { ps.setString(++_dirtyCount, bean.getTbkTargetNilai1() + "%"); }
                        break;
                    default:
                        throw new DAOException("Unknown search type " + searchType);
                }
            }
            if (bean.isTbkDescriptionModified()) {
                switch (searchType){
                    case SEARCH_EXACT:
                        log.debug("Setting for " + _dirtyCount + " [" + bean.getTbkDescription() + "]");
                        if (bean.getTbkDescription() == null) { ps.setNull(++_dirtyCount, Types.VARCHAR); } else { ps.setString(++_dirtyCount, bean.getTbkDescription()); }
                        break;
                    case SEARCH_LIKE:
                        log.debug("Setting for " + _dirtyCount + " [%" + bean.getTbkDescription() + "%]");
                        ps.setString(++_dirtyCount, "%" + bean.getTbkDescription() + "%");
                        break;
                    case SEARCH_STARTING_LIKE:
                        log.debug("Setting for " + _dirtyCount + " [" + bean.getTbkDescription() + "%]");
                        ps.setString(++_dirtyCount, "%" + bean.getTbkDescription());
                        break;
                    case SEARCH_ENDING_LIKE:
                        log.debug("Setting for " + _dirtyCount + " [%" + bean.getTbkDescription() + "]");
                        if (bean.getTbkDescription() + "%" == null) { ps.setNull(++_dirtyCount, Types.VARCHAR); } else { ps.setString(++_dirtyCount, bean.getTbkDescription() + "%"); }
                        break;
                    default:
                        throw new DAOException("Unknown search type " + searchType);
                }
            }
            if (bean.isTbkIdModified()) {
                log.debug("Setting for " + _dirtyCount + " [" + bean.getTbkId() + "]");
                if (bean.getTbkId() == null) { ps.setNull(++_dirtyCount, Types.INTEGER); } else { Manager.setInteger(ps, ++_dirtyCount, bean.getTbkId()); }
            }
            if (bean.isTbeNameModified()) {
                switch (searchType){
                    case SEARCH_EXACT:
                        log.debug("Setting for " + _dirtyCount + " [" + bean.getTbeName() + "]");
                        if (bean.getTbeName() == null) { ps.setNull(++_dirtyCount, Types.VARCHAR); } else { ps.setString(++_dirtyCount, bean.getTbeName()); }
                        break;
                    case SEARCH_LIKE:
                        log.debug("Setting for " + _dirtyCount + " [%" + bean.getTbeName() + "%]");
                        ps.setString(++_dirtyCount, "%" + bean.getTbeName() + "%");
                        break;
                    case SEARCH_STARTING_LIKE:
                        log.debug("Setting for " + _dirtyCount + " [" + bean.getTbeName() + "%]");
                        ps.setString(++_dirtyCount, "%" + bean.getTbeName());
                        break;
                    case SEARCH_ENDING_LIKE:
                        log.debug("Setting for " + _dirtyCount + " [%" + bean.getTbeName() + "]");
                        if (bean.getTbeName() + "%" == null) { ps.setNull(++_dirtyCount, Types.VARCHAR); } else { ps.setString(++_dirtyCount, bean.getTbeName() + "%"); }
                        break;
                    default:
                        throw new DAOException("Unknown search type " + searchType);
                }
            }
            if (bean.isTbkgNameModified()) {
                switch (searchType){
                    case SEARCH_EXACT:
                        log.debug("Setting for " + _dirtyCount + " [" + bean.getTbkgName() + "]");
                        if (bean.getTbkgName() == null) { ps.setNull(++_dirtyCount, Types.VARCHAR); } else { ps.setString(++_dirtyCount, bean.getTbkgName()); }
                        break;
                    case SEARCH_LIKE:
                        log.debug("Setting for " + _dirtyCount + " [%" + bean.getTbkgName() + "%]");
                        ps.setString(++_dirtyCount, "%" + bean.getTbkgName() + "%");
                        break;
                    case SEARCH_STARTING_LIKE:
                        log.debug("Setting for " + _dirtyCount + " [" + bean.getTbkgName() + "%]");
                        ps.setString(++_dirtyCount, "%" + bean.getTbkgName());
                        break;
                    case SEARCH_ENDING_LIKE:
                        log.debug("Setting for " + _dirtyCount + " [%" + bean.getTbkgName() + "]");
                        if (bean.getTbkgName() + "%" == null) { ps.setNull(++_dirtyCount, Types.VARCHAR); } else { ps.setString(++_dirtyCount, bean.getTbkgName() + "%"); }
                        break;
                    default:
                        throw new DAOException("Unknown search type " + searchType);
                }
            }
            if (bean.isTbkgKpiGroupIdModified()) {
                switch (searchType){
                    case SEARCH_EXACT:
                        log.debug("Setting for " + _dirtyCount + " [" + bean.getTbkgKpiGroupId() + "]");
                        if (bean.getTbkgKpiGroupId() == null) { ps.setNull(++_dirtyCount, Types.VARCHAR); } else { ps.setString(++_dirtyCount, bean.getTbkgKpiGroupId()); }
                        break;
                    case SEARCH_LIKE:
                        log.debug("Setting for " + _dirtyCount + " [%" + bean.getTbkgKpiGroupId() + "%]");
                        ps.setString(++_dirtyCount, "%" + bean.getTbkgKpiGroupId() + "%");
                        break;
                    case SEARCH_STARTING_LIKE:
                        log.debug("Setting for " + _dirtyCount + " [" + bean.getTbkgKpiGroupId() + "%]");
                        ps.setString(++_dirtyCount, "%" + bean.getTbkgKpiGroupId());
                        break;
                    case SEARCH_ENDING_LIKE:
                        log.debug("Setting for " + _dirtyCount + " [%" + bean.getTbkgKpiGroupId() + "]");
                        if (bean.getTbkgKpiGroupId() + "%" == null) { ps.setNull(++_dirtyCount, Types.VARCHAR); } else { ps.setString(++_dirtyCount, bean.getTbkgKpiGroupId() + "%"); }
                        break;
                    default:
                        throw new DAOException("Unknown search type " + searchType);
                }
            }
            if (bean.isTbkgIdModified()) {
                log.debug("Setting for " + _dirtyCount + " [" + bean.getTbkgId() + "]");
                if (bean.getTbkgId() == null) { ps.setNull(++_dirtyCount, Types.INTEGER); } else { Manager.setInteger(ps, ++_dirtyCount, bean.getTbkgId()); }
            }
        }
        catch(SQLException e)
        {
            throw new DataAccessException(e);
        }
        return _dirtyCount;
    }


    //_____________________________________________________________________
    //
    // DECODE RESULT SET
    //_____________________________________________________________________

    /**
     * decode a resultset in an array of ViewKpiBean objects
     *
     * @param rs the resultset to decode
     * @param fieldList table of the field's associated constants
     * @param startRow the start row to be used (first row = 1, last row = -1)
     * @param numRows the number of rows to be retrieved (all rows = a negative number)
     * @return the resulting ViewKpiBean table
     * @throws DAOException
     */
    //28
    public ViewKpiBean[] decodeResultSet(ResultSet rs, int[] fieldList, int startRow, int numRows) throws DAOException
    {
        List v = new ArrayList();
        try
        {
            if (rs.absolute(startRow) && numRows!=0)
            {
                int count = 0;
                if(fieldList == null) {
                    do
                    {
                        v.add(decodeRow(rs));
                        count++;
                    } while ( (count<numRows||numRows<0) && rs.next() );
                }
                else {
                    do
                    {
                        v.add(decodeRow(rs, fieldList));
                        count++;
                    } while ( (count<numRows||numRows<0) && rs.next() );
                }
            }
            return (ViewKpiBean[])v.toArray(new ViewKpiBean[v.size()]);
        }
        catch(SQLException e)
        {
            throw new DataAccessException(e);
        }
        finally
        {
            if (v != null) { v.clear(); v = null;}
        }
    }

    /**
     * Transforms a ResultSet iterating on the view_kpi on a ViewKpiBean bean.
     *
     * @param rs the ResultSet to be transformed
     * @return bean resulting ViewKpiBean bean
     * @throws DAOException
     */
    //29
    public ViewKpiBean decodeRow(ResultSet rs) throws DAOException
    {
        ViewKpiBean bean = this.createViewKpiBean();
        try
        {
            bean.setTbeId(Manager.getInteger(rs, 1));
            bean.setTbkBobot(Manager.getInteger(rs, 2));
            bean.setTbkTargetNilai5(rs.getString(3));
            bean.setTbkTargetNilai4(rs.getString(4));
            bean.setTbkTargetNilai3(rs.getString(5));
            bean.setTbkTargetNilai2(rs.getString(6));
            bean.setTbkTargetNilai1(rs.getString(7));
            bean.setTbkDescription(rs.getString(8));
            bean.setTbkId(Manager.getInteger(rs, 9));
            bean.setTbeName(rs.getString(10));
            bean.setTbkgName(rs.getString(11));
            bean.setTbkgKpiGroupId(rs.getString(12));
            bean.setTbkgId(Manager.getInteger(rs, 13));
        }
        catch(SQLException e)
        {
            throw new DataAccessException(e);
        }
        bean.isNew(false);
        bean.resetIsModified();

        return bean;
    }
	
    //29A
    public ViewKpiBean toBean(ViewKpiBeanModel beanModel, ViewKpiBean bean)
    {
		if (beanModel.getTbeId() != null)
			bean.setTbeId(beanModel.getTbeId());

		if (bean.getTbeId() != null)
		if ("java.sql.Timestamp".equals(bean.getTbeId().getClass().getName()))
			bean.setTbeId(beanModel.getTbeId());
		
		if (beanModel.getTbkBobot() != null)
			bean.setTbkBobot(beanModel.getTbkBobot());

		if (bean.getTbkBobot() != null)
		if ("java.sql.Timestamp".equals(bean.getTbkBobot().getClass().getName()))
			bean.setTbkBobot(beanModel.getTbkBobot());
		
		if (beanModel.getTbkTargetNilai5() != null)
			bean.setTbkTargetNilai5(beanModel.getTbkTargetNilai5());

		if (bean.getTbkTargetNilai5() != null)
		if ("java.sql.Timestamp".equals(bean.getTbkTargetNilai5().getClass().getName()))
			bean.setTbkTargetNilai5(beanModel.getTbkTargetNilai5());
		
		if (beanModel.getTbkTargetNilai4() != null)
			bean.setTbkTargetNilai4(beanModel.getTbkTargetNilai4());

		if (bean.getTbkTargetNilai4() != null)
		if ("java.sql.Timestamp".equals(bean.getTbkTargetNilai4().getClass().getName()))
			bean.setTbkTargetNilai4(beanModel.getTbkTargetNilai4());
		
		if (beanModel.getTbkTargetNilai3() != null)
			bean.setTbkTargetNilai3(beanModel.getTbkTargetNilai3());

		if (bean.getTbkTargetNilai3() != null)
		if ("java.sql.Timestamp".equals(bean.getTbkTargetNilai3().getClass().getName()))
			bean.setTbkTargetNilai3(beanModel.getTbkTargetNilai3());
		
		if (beanModel.getTbkTargetNilai2() != null)
			bean.setTbkTargetNilai2(beanModel.getTbkTargetNilai2());

		if (bean.getTbkTargetNilai2() != null)
		if ("java.sql.Timestamp".equals(bean.getTbkTargetNilai2().getClass().getName()))
			bean.setTbkTargetNilai2(beanModel.getTbkTargetNilai2());
		
		if (beanModel.getTbkTargetNilai1() != null)
			bean.setTbkTargetNilai1(beanModel.getTbkTargetNilai1());

		if (bean.getTbkTargetNilai1() != null)
		if ("java.sql.Timestamp".equals(bean.getTbkTargetNilai1().getClass().getName()))
			bean.setTbkTargetNilai1(beanModel.getTbkTargetNilai1());
		
		if (beanModel.getTbkDescription() != null)
			bean.setTbkDescription(beanModel.getTbkDescription());

		if (bean.getTbkDescription() != null)
		if ("java.sql.Timestamp".equals(bean.getTbkDescription().getClass().getName()))
			bean.setTbkDescription(beanModel.getTbkDescription());
		
		if (beanModel.getTbkId() != null)
			bean.setTbkId(beanModel.getTbkId());

		if (bean.getTbkId() != null)
		if ("java.sql.Timestamp".equals(bean.getTbkId().getClass().getName()))
			bean.setTbkId(beanModel.getTbkId());
		
		if (beanModel.getTbeName() != null)
			bean.setTbeName(beanModel.getTbeName());

		if (bean.getTbeName() != null)
		if ("java.sql.Timestamp".equals(bean.getTbeName().getClass().getName()))
			bean.setTbeName(beanModel.getTbeName());
		
		if (beanModel.getTbkgName() != null)
			bean.setTbkgName(beanModel.getTbkgName());

		if (bean.getTbkgName() != null)
		if ("java.sql.Timestamp".equals(bean.getTbkgName().getClass().getName()))
			bean.setTbkgName(beanModel.getTbkgName());
		
		if (beanModel.getTbkgKpiGroupId() != null)
			bean.setTbkgKpiGroupId(beanModel.getTbkgKpiGroupId());

		if (bean.getTbkgKpiGroupId() != null)
		if ("java.sql.Timestamp".equals(bean.getTbkgKpiGroupId().getClass().getName()))
			bean.setTbkgKpiGroupId(beanModel.getTbkgKpiGroupId());
		
		if (beanModel.getTbkgId() != null)
			bean.setTbkgId(beanModel.getTbkgId());

		if (bean.getTbkgId() != null)
		if ("java.sql.Timestamp".equals(bean.getTbkgId().getClass().getName()))
			bean.setTbkgId(beanModel.getTbkgId());
		
		return bean;
    }
	
    //29AA
    public ViewKpiBean[] toBeans(ViewKpiBeanModel beanModels[])
    {
		int beanModelsCount = beanModels.length;
		ViewKpiBean beans[] = new ViewKpiBean[beanModelsCount];
		
		for (int i = 0; i < beanModelsCount; i++) {
			beans[i] = toBean(beanModels[i], beans[i]);
		}
		
		return beans;
    }
	
    //29C
    public ViewKpiBeanModel toBeanModel(ViewKpiBean bean)
    {
		ViewKpiBeanModel beanModel = new ViewKpiBeanModel();
		beanModel.setTbeId(bean.getTbeId());
		beanModel.setTbkBobot(bean.getTbkBobot());
		beanModel.setTbkTargetNilai5(bean.getTbkTargetNilai5());
		beanModel.setTbkTargetNilai4(bean.getTbkTargetNilai4());
		beanModel.setTbkTargetNilai3(bean.getTbkTargetNilai3());
		beanModel.setTbkTargetNilai2(bean.getTbkTargetNilai2());
		beanModel.setTbkTargetNilai1(bean.getTbkTargetNilai1());
		beanModel.setTbkDescription(bean.getTbkDescription());
		beanModel.setTbkId(bean.getTbkId());
		beanModel.setTbeName(bean.getTbeName());
		beanModel.setTbkgName(bean.getTbkgName());
		beanModel.setTbkgKpiGroupId(bean.getTbkgKpiGroupId());
		beanModel.setTbkgId(bean.getTbkgId());
		return beanModel;
    }
	
    //29CC
    public ViewKpiBeanModel[] toBeanModels(ViewKpiBean beans[])
    {
		int beansCount = beans.length;
		ViewKpiBeanModel beanModels[] = new ViewKpiBeanModel[beansCount];
		
		for (int i = 0; i < beansCount; i++) {
			beanModels[i] = toBeanModel(beans[i]);
		}
		
		return beanModels;
    }	
	
    /**
     * Transforms a ResultSet iterating on the view_kpi table on a ViewKpiBean bean according to a list of fields.
     *
     * @param rs the ResultSet to be transformed
     * @param fieldList table of the field's associated constants
     * @return bean resulting ViewKpiBean bean
     * @throws DAOException
     */
    //30
    public ViewKpiBean decodeRow(ResultSet rs, int[] fieldList) throws DAOException
    {
        ViewKpiBean bean = this.createViewKpiBean();
        int pos = 0;
        try
        {
            for(int i = 0; i < fieldList.length; i++)
            {
                switch(fieldList[i])
                {
                    case ID_TBE_ID:
                        ++pos;
                        bean.setTbeId(Manager.getInteger(rs, pos));
                        break;
                    case ID_TBK_BOBOT:
                        ++pos;
                        bean.setTbkBobot(Manager.getInteger(rs, pos));
                        break;
                    case ID_TBK_TARGET_NILAI_5:
                        ++pos;
                        bean.setTbkTargetNilai5(rs.getString(pos));
                        break;
                    case ID_TBK_TARGET_NILAI_4:
                        ++pos;
                        bean.setTbkTargetNilai4(rs.getString(pos));
                        break;
                    case ID_TBK_TARGET_NILAI_3:
                        ++pos;
                        bean.setTbkTargetNilai3(rs.getString(pos));
                        break;
                    case ID_TBK_TARGET_NILAI_2:
                        ++pos;
                        bean.setTbkTargetNilai2(rs.getString(pos));
                        break;
                    case ID_TBK_TARGET_NILAI_1:
                        ++pos;
                        bean.setTbkTargetNilai1(rs.getString(pos));
                        break;
                    case ID_TBK_DESCRIPTION:
                        ++pos;
                        bean.setTbkDescription(rs.getString(pos));
                        break;
                    case ID_TBK_ID:
                        ++pos;
                        bean.setTbkId(Manager.getInteger(rs, pos));
                        break;
                    case ID_TBE_NAME:
                        ++pos;
                        bean.setTbeName(rs.getString(pos));
                        break;
                    case ID_TBKG_NAME:
                        ++pos;
                        bean.setTbkgName(rs.getString(pos));
                        break;
                    case ID_TBKG_KPI_GROUP_ID:
                        ++pos;
                        bean.setTbkgKpiGroupId(rs.getString(pos));
                        break;
                    case ID_TBKG_ID:
                        ++pos;
                        bean.setTbkgId(Manager.getInteger(rs, pos));
                        break;
                    default:
                        throw new DAOException("Unknown field id " + fieldList[i]);
                }
            }
        }
        catch(SQLException e)
        {
            throw new DataAccessException(e);
        }
        bean.isNew(false);
        bean.resetIsModified();

        return bean;
    }

    /**
     * Transforms a ResultSet iterating on the view_kpi on a ViewKpiBean bean using the names of the columns
     *
     * @param rs the ResultSet to be transformed
     * @return bean resulting ViewKpiBean bean
     * @throws DAOException
     */
    //31
    public ViewKpiBean metaDataDecodeRow(ResultSet rs) throws DAOException
    {
        ViewKpiBean bean = this.createViewKpiBean();
        try
        {
            bean.setTbeId(Manager.getInteger(rs, "tbe_id"));
            bean.setTbkBobot(Manager.getInteger(rs, "tbk_bobot"));
            bean.setTbkTargetNilai5(rs.getString("tbk_target_nilai_5"));
            bean.setTbkTargetNilai4(rs.getString("tbk_target_nilai_4"));
            bean.setTbkTargetNilai3(rs.getString("tbk_target_nilai_3"));
            bean.setTbkTargetNilai2(rs.getString("tbk_target_nilai_2"));
            bean.setTbkTargetNilai1(rs.getString("tbk_target_nilai_1"));
            bean.setTbkDescription(rs.getString("tbk_description"));
            bean.setTbkId(Manager.getInteger(rs, "tbk_id"));
            bean.setTbeName(rs.getString("tbe_name"));
            bean.setTbkgName(rs.getString("tbkg_name"));
            bean.setTbkgKpiGroupId(rs.getString("tbkg_kpi_group_id"));
            bean.setTbkgId(Manager.getInteger(rs, "tbkg_id"));
        }
        catch(SQLException e)
        {
            throw new DataAccessException(e);
        }

        bean.isNew(false);
        bean.resetIsModified();

        return bean;
    }

    //////////////////////////////////////
    // PREPARED STATEMENT LOADER
    //////////////////////////////////////

    /**
     * Loads all the elements using a prepared statement.
     *
     * @param ps the PreparedStatement to be used
     * @return an array of ViewKpiBean
     * @throws DAOException
     */
    //32
    public ViewKpiBean[] loadByPreparedStatement(PreparedStatement ps) throws DAOException
    {
        return this.loadByPreparedStatement(ps, null);
    }

    /**
     * Loads all the elements using a prepared statement specifying a list of fields to be retrieved.
     *
     * @param ps the PreparedStatement to be used
     * @param fieldList table of the field's associated constants
     * @return an array of ViewKpiBean
     * @throws DAOException
     */
    //33
    public ViewKpiBean[] loadByPreparedStatement(PreparedStatement ps, int[] fieldList) throws DAOException
    {
        ResultSet rs =  null;
		List v =  null;
		try
		{
		    rs =  ps.executeQuery();
		    v = new ArrayList();
			if(fieldList == null) {
				while(rs.next()) {
					v.add(decodeRow(rs));
				}
			}
			else {
				while(rs.next()) {
					v.add(decodeRow(rs, fieldList));
				}
			}

			return (ViewKpiBean[])v.toArray(new ViewKpiBean[0]);
        }
        catch(SQLException e)
        {
            throw new DataAccessException(e);
        }
        finally
        {
            if (v != null) { v.clear(); v = null;}
            getManager().close(rs);
        }
    }

    /**
     * Loads all the elements using a prepared statement specifying a list of fields to be retrieved,
     * and specifying the start row and the number of rows.
     *
     * @param ps the PreparedStatement to be used
     * @param startRow the start row to be used (first row = 1, last row = -1)
     * @param numRows the number of rows to be retrieved (all rows = a negative number)
     * @param fieldList table of the field's associated constants
     * @return an array of ViewKpiBean
     * @throws DAOException
     */
    //34
    public ViewKpiBean[] loadByPreparedStatement(PreparedStatement ps, int[] fieldList, int startRow, int numRows) throws DAOException
    {
        ResultSet rs =  null;
        try
        {
            rs = ps.executeQuery();
            return this.decodeResultSet(rs, fieldList, startRow, numRows);
        }
        catch(SQLException e)
        {
            throw new DataAccessException(e);
        }
        finally
        {
            this.getManager().close(rs);
        }
    }

    //_____________________________________________________________________
    //
    // LISTENER
    //_____________________________________________________________________
    private ViewKpiListener listener = null;

    /**
     * Registers a unique ViewKpiListener listener.
     */
    //35
    public void registerListener(ViewKpiListener listener)
    {
        this.listener = listener;
    }

    /**
     * Before the save of the ViewKpiBean bean.
     *
     * @param bean the ViewKpiBean bean to be saved
     */
    //36
    private void beforeInsert(ViewKpiBean bean) throws DAOException
    {
        if (listener != null) {
            listener.beforeInsert(bean);
        }
    }

    /**
     * After the save of the ViewKpiBean bean.
     *
     * @param bean the ViewKpiBean bean to be saved
     */
    //37
    private void afterInsert(ViewKpiBean bean) throws DAOException
    {
        if (listener != null) {
            listener.afterInsert(bean);
        }
    }

    /**
     * Before the update of the ViewKpiBean bean.
     *
     * @param bean the ViewKpiBean bean to be updated
     */
    //38
    private void beforeUpdate(ViewKpiBean bean) throws DAOException
    {
        if (listener != null) {
            listener.beforeUpdate(bean);
        }
    }

    /**
     * After the update of the ViewKpiBean bean.
     *
     * @param bean the ViewKpiBean bean to be updated
     */
    //39
    private void afterUpdate(ViewKpiBean bean) throws DAOException
    {
        if (listener != null) {
            listener.afterUpdate(bean);
        }
    }

    /**
     * Before the delete of the ViewKpiBean bean.
     *
     * @param bean the ViewKpiBean bean to be deleted
     */
    private void beforeDelete(ViewKpiBean bean) throws DAOException
    {
        if (listener != null) {
            listener.beforeDelete(bean);
        }
    }

    /**
     * After the delete of the ViewKpiBean bean.
     *
     * @param bean the ViewKpiBean bean to be deleted
     */
    private void afterDelete(ViewKpiBean bean) throws DAOException
    {
        if (listener != null) {
            listener.afterDelete(bean);
        }
    }

    //_____________________________________________________________________
    //
    // UTILS
    //_____________________________________________________________________

    /**
     * Retrieves the manager object used to get connections.
     *
     * @return the manager used
     */
    //40
    public Manager getManager()
    {
        return Manager.getInstance();
    }

    /**
     * Frees the connection.
     *
     * @param c the connection to release
     */
    //41
    public void freeConnection(Connection c)
    {
        this.getManager().releaseConnection(c); // back to pool
    }

    /**
     * Gets the connection.
     */
    //42
    public Connection getConnection() throws DAOException
    {
        try
        {
            return this.getManager().getConnection();
        }
        catch(SQLException e)
        {
            throw new DataAccessException(e);
        }
    }
}
