// ______________________________________________________
// Generated by sql2java - http://sql2java.sourceforge.net/
// jdbc driver used at code generation time: com.mysql.jdbc.Driver
//
// Please help us improve this tool by reporting:
// - problems and suggestions to
//   http://sourceforge.net/tracker/?group_id=54687
// - feedbacks and ideas on
//   http://sourceforge.net/forum/forum.php?forum_id=182208
// ______________________________________________________

package com.gwt.hris.db;

import java.util.Comparator;


/**
 * Comparator class is used to sort the ViewReportEmployeeInformation3Bean objects.
 * @author sql2java
 */
public class ViewReportEmployeeInformation3Comparator implements Comparator
{
    /**
     * Holds the field on which the comparison is performed.
     */
    private int iType;
    /**
     * Value that will contain the information about the order of the sort: normal or reversal.
     */
    private boolean bReverse;

    /**
     * Constructor class for ViewReportEmployeeInformation3Comparator.
     * <br>
     * Example:
     * <br>
     * <code>Arrays.sort(pArray, new ViewReportEmployeeInformation3Comparator(ViewReportEmployeeInformation3Manager.ID_TBL_NAME, bReverse));<code>
     *
     * @param iType the field from which you want to sort
     * <br>
     * Possible values are:
     * <ul>
     *   <li>ViewReportEmployeeInformation3Manager.ID_TBL_NAME
     *   <li>ViewReportEmployeeInformation3Manager.ID_TBE_NAME
     *   <li>ViewReportEmployeeInformation3Manager.ID_TBE_ID
     * </ul>
     */
    public ViewReportEmployeeInformation3Comparator(int iType)
    {
        this(iType, false);
    }

    /**
     * Constructor class for ViewReportEmployeeInformation3Comparator.
     * <br>
     * Example:
     * <br>
     * <code>Arrays.sort(pArray, new ViewReportEmployeeInformation3Comparator(ViewReportEmployeeInformation3Manager.ID_TBL_NAME, bReverse));<code>
     *
     * @param iType the field from which you want to sort.
     * <br>
     * Possible values are:
     * <ul>
     *   <li>ViewReportEmployeeInformation3Manager.ID_TBL_NAME
     *   <li>ViewReportEmployeeInformation3Manager.ID_TBE_NAME
     *   <li>ViewReportEmployeeInformation3Manager.ID_TBE_ID
     * </ul>
     *
     * @param bReverse set this value to true, if you want to reverse the sorting results
     */
    public ViewReportEmployeeInformation3Comparator(int iType, boolean bReverse)
    {
        this.iType = iType;
        this.bReverse = bReverse;
    }

    /**
     * Implementation of the compare method.
     */
    public int compare(Object pObj1, Object pObj2)
    {
        ViewReportEmployeeInformation3Bean b1 = (ViewReportEmployeeInformation3Bean)pObj1;
        ViewReportEmployeeInformation3Bean b2 = (ViewReportEmployeeInformation3Bean)pObj2;
        int iReturn = 0;
        switch(iType)
        {
            case ViewReportEmployeeInformation3Manager.ID_TBL_NAME:
                if (b1.getTblName() == null && b2.getTblName() != null) {
                    iReturn = -1;
                } else if (b1.getTblName() == null && b2.getTblName() == null) {
                    iReturn = 0;
                } else if (b1.getTblName() != null && b2.getTblName() == null) {
                    iReturn = 1;
                } else {
                    iReturn = b1.getTblName().compareTo(b2.getTblName());
                }
                break;
            case ViewReportEmployeeInformation3Manager.ID_TBE_NAME:
                if (b1.getTbeName() == null && b2.getTbeName() != null) {
                    iReturn = -1;
                } else if (b1.getTbeName() == null && b2.getTbeName() == null) {
                    iReturn = 0;
                } else if (b1.getTbeName() != null && b2.getTbeName() == null) {
                    iReturn = 1;
                } else {
                    iReturn = b1.getTbeName().compareTo(b2.getTbeName());
                }
                break;
            case ViewReportEmployeeInformation3Manager.ID_TBE_ID:
                if (b1.getTbeId() == null && b2.getTbeId() != null) {
                    iReturn = -1;
                } else if (b1.getTbeId() == null && b2.getTbeId() == null) {
                    iReturn = 0;
                } else if (b1.getTbeId() != null && b2.getTbeId() == null) {
                    iReturn = 1;
                } else {
                    iReturn = b1.getTbeId().compareTo(b2.getTbeId());
                }
                break;
            default:
                throw new IllegalArgumentException("Type passed for the field is not supported");
        }

        return bReverse ? (-1 * iReturn) : iReturn;
    }}
