// ______________________________________________________
// Generated by sql2java - http://sql2java.sourceforge.net/
// jdbc driver used at code generation time: com.mysql.jdbc.Driver
//
// Please help us improve this tool by reporting:
// - problems and suggestions to
//   http://sourceforge.net/tracker/?group_id=54687
// - feedbacks and ideas on
//   http://sourceforge.net/forum/forum.php?forum_id=182208
// ______________________________________________________

package com.gwt.hris.db;

import com.gwt.hris.db.exception.DAOException;

/**
 * Listener that is notified of view_property_employee table changes.
 * @author sql2java
 */
public interface ViewPropertyEmployeeListener
{
    /**
     * Invoked just before inserting a ViewPropertyEmployeeBean record into the database.
     *
     * @param bean the ViewPropertyEmployeeBean that is about to be inserted
     */
    public void beforeInsert(ViewPropertyEmployeeBean bean) throws DAOException;


    /**
     * Invoked just after a ViewPropertyEmployeeBean record is inserted in the database.
     *
     * @param bean the ViewPropertyEmployeeBean that was just inserted
     */
    public void afterInsert(ViewPropertyEmployeeBean bean) throws DAOException;


    /**
     * Invoked just before updating a ViewPropertyEmployeeBean record in the database.
     *
     * @param bean the ViewPropertyEmployeeBean that is about to be updated
     */
    public void beforeUpdate(ViewPropertyEmployeeBean bean) throws DAOException;


    /**
     * Invoked just after updating a ViewPropertyEmployeeBean record in the database.
     *
     * @param bean the ViewPropertyEmployeeBean that was just updated
     */
    public void afterUpdate(ViewPropertyEmployeeBean bean) throws DAOException;


    /**
     * Invoked just before deleting a ViewPropertyEmployeeBean record in the database.
     *
     * @param bean the ViewPropertyEmployeeBean that is about to be deleted
     */
    public void beforeDelete(ViewPropertyEmployeeBean bean) throws DAOException;


    /**
     * Invoked just after deleting a ViewPropertyEmployeeBean record in the database.
     *
     * @param bean the ViewPropertyEmployeeBean that was just deleted
     */
    public void afterDelete(ViewPropertyEmployeeBean bean) throws DAOException;

}
