USE hrm;

CREATE TABLE `tb_currency` (
  `tbc_id` int(11) NOT NULL AUTO_INCREMENT,
  `tbc_currency_id` varchar(45) DEFAULT NULL COMMENT 'NAME+ID',
  `tbc_name` varchar(45) DEFAULT NULL,
  `tbc_local_currency_kurs` double DEFAULT NULL,
  PRIMARY KEY (`tbc_id`)
) ENGINE=InnoDB AUTO_INCREMENT=160 DEFAULT CHARSET=latin1;


insert into `hrm`.`tb_currency`(`tbc_id`,`tbc_currency_id`,`tbc_name`,`tbc_local_currency_kurs`) values (1,'AED','Utd. Arab Emir. Dirham',1);
insert into `hrm`.`tb_currency`(`tbc_id`,`tbc_currency_id`,`tbc_name`,`tbc_local_currency_kurs`) values (2,'AFN','Afghanistan Afghani',1);
insert into `hrm`.`tb_currency`(`tbc_id`,`tbc_currency_id`,`tbc_name`,`tbc_local_currency_kurs`) values (3,'ALL','Albanian Lek',1);
insert into `hrm`.`tb_currency`(`tbc_id`,`tbc_currency_id`,`tbc_name`,`tbc_local_currency_kurs`) values (4,'ANG','NL Antillian Guilder',1);
insert into `hrm`.`tb_currency`(`tbc_id`,`tbc_currency_id`,`tbc_name`,`tbc_local_currency_kurs`) values (5,'AOR','Angolan New Kwanza',1);
insert into `hrm`.`tb_currency`(`tbc_id`,`tbc_currency_id`,`tbc_name`,`tbc_local_currency_kurs`) values (6,'ARP','Argentina Pesos',1);
insert into `hrm`.`tb_currency`(`tbc_id`,`tbc_currency_id`,`tbc_name`,`tbc_local_currency_kurs`) values (7,'ARS','Argentine Peso',1);
insert into `hrm`.`tb_currency`(`tbc_id`,`tbc_currency_id`,`tbc_name`,`tbc_local_currency_kurs`) values (8,'AUD','Australian Dollar',1);
insert into `hrm`.`tb_currency`(`tbc_id`,`tbc_currency_id`,`tbc_name`,`tbc_local_currency_kurs`) values (9,'AWG','Aruban Florin',1);
insert into `hrm`.`tb_currency`(`tbc_id`,`tbc_currency_id`,`tbc_name`,`tbc_local_currency_kurs`) values (10,'BBD','Barbados Dollar',1);
insert into `hrm`.`tb_currency`(`tbc_id`,`tbc_currency_id`,`tbc_name`,`tbc_local_currency_kurs`) values (11,'BDT','Bangladeshi Taka',1);
insert into `hrm`.`tb_currency`(`tbc_id`,`tbc_currency_id`,`tbc_name`,`tbc_local_currency_kurs`) values (12,'BGL','Bulgarian Lev',1);
insert into `hrm`.`tb_currency`(`tbc_id`,`tbc_currency_id`,`tbc_name`,`tbc_local_currency_kurs`) values (13,'BHD','Bahraini Dinar',1);
insert into `hrm`.`tb_currency`(`tbc_id`,`tbc_currency_id`,`tbc_name`,`tbc_local_currency_kurs`) values (14,'BIF','Burundi Franc',1);
insert into `hrm`.`tb_currency`(`tbc_id`,`tbc_currency_id`,`tbc_name`,`tbc_local_currency_kurs`) values (15,'BMD','Bermudian Dollar',1);
insert into `hrm`.`tb_currency`(`tbc_id`,`tbc_currency_id`,`tbc_name`,`tbc_local_currency_kurs`) values (16,'BND','Brunei Dollar',1);
insert into `hrm`.`tb_currency`(`tbc_id`,`tbc_currency_id`,`tbc_name`,`tbc_local_currency_kurs`) values (17,'BOB','Bolivian Boliviano',1);
insert into `hrm`.`tb_currency`(`tbc_id`,`tbc_currency_id`,`tbc_name`,`tbc_local_currency_kurs`) values (18,'BRL','Brazilian Real',1);
insert into `hrm`.`tb_currency`(`tbc_id`,`tbc_currency_id`,`tbc_name`,`tbc_local_currency_kurs`) values (19,'BSD','Bahamian Dollar',1);
insert into `hrm`.`tb_currency`(`tbc_id`,`tbc_currency_id`,`tbc_name`,`tbc_local_currency_kurs`) values (20,'BTN','Bhutan Ngultrum',1);
insert into `hrm`.`tb_currency`(`tbc_id`,`tbc_currency_id`,`tbc_name`,`tbc_local_currency_kurs`) values (21,'BWP','Botswana Pula',1);
insert into `hrm`.`tb_currency`(`tbc_id`,`tbc_currency_id`,`tbc_name`,`tbc_local_currency_kurs`) values (22,'BZD','Belize Dollar',1);
insert into `hrm`.`tb_currency`(`tbc_id`,`tbc_currency_id`,`tbc_name`,`tbc_local_currency_kurs`) values (23,'CAD','Canadian Dollar',1);
insert into `hrm`.`tb_currency`(`tbc_id`,`tbc_currency_id`,`tbc_name`,`tbc_local_currency_kurs`) values (24,'CHF','Swiss Franc',1);
insert into `hrm`.`tb_currency`(`tbc_id`,`tbc_currency_id`,`tbc_name`,`tbc_local_currency_kurs`) values (25,'CLP','Chilean Peso',1);
insert into `hrm`.`tb_currency`(`tbc_id`,`tbc_currency_id`,`tbc_name`,`tbc_local_currency_kurs`) values (26,'CNY','Chinese Yuan Renminbi',1);
insert into `hrm`.`tb_currency`(`tbc_id`,`tbc_currency_id`,`tbc_name`,`tbc_local_currency_kurs`) values (27,'COP','Colombian Peso',1);
insert into `hrm`.`tb_currency`(`tbc_id`,`tbc_currency_id`,`tbc_name`,`tbc_local_currency_kurs`) values (28,'CRC','Costa Rican Colon',1);
insert into `hrm`.`tb_currency`(`tbc_id`,`tbc_currency_id`,`tbc_name`,`tbc_local_currency_kurs`) values (29,'CUP','Cuban Peso',1);
insert into `hrm`.`tb_currency`(`tbc_id`,`tbc_currency_id`,`tbc_name`,`tbc_local_currency_kurs`) values (30,'CVE','Cape Verde Escudo',1);
insert into `hrm`.`tb_currency`(`tbc_id`,`tbc_currency_id`,`tbc_name`,`tbc_local_currency_kurs`) values (31,'CYP','Cyprus Pound',1);
insert into `hrm`.`tb_currency`(`tbc_id`,`tbc_currency_id`,`tbc_name`,`tbc_local_currency_kurs`) values (32,'CZK','Czech Koruna',1);
insert into `hrm`.`tb_currency`(`tbc_id`,`tbc_currency_id`,`tbc_name`,`tbc_local_currency_kurs`) values (33,'DJF','Djibouti Franc',1);
insert into `hrm`.`tb_currency`(`tbc_id`,`tbc_currency_id`,`tbc_name`,`tbc_local_currency_kurs`) values (34,'DKK','Danish Krona',1);
insert into `hrm`.`tb_currency`(`tbc_id`,`tbc_currency_id`,`tbc_name`,`tbc_local_currency_kurs`) values (35,'DOP','Dominican Peso',1);
insert into `hrm`.`tb_currency`(`tbc_id`,`tbc_currency_id`,`tbc_name`,`tbc_local_currency_kurs`) values (36,'DZD','Algerian Dinar',1);
insert into `hrm`.`tb_currency`(`tbc_id`,`tbc_currency_id`,`tbc_name`,`tbc_local_currency_kurs`) values (37,'ECS','Ecuador Sucre',1);
insert into `hrm`.`tb_currency`(`tbc_id`,`tbc_currency_id`,`tbc_name`,`tbc_local_currency_kurs`) values (38,'EEK','Estonian Krona',1);
insert into `hrm`.`tb_currency`(`tbc_id`,`tbc_currency_id`,`tbc_name`,`tbc_local_currency_kurs`) values (39,'EGP','Egyptian Pound',1);
insert into `hrm`.`tb_currency`(`tbc_id`,`tbc_currency_id`,`tbc_name`,`tbc_local_currency_kurs`) values (40,'ETB','Ethiopian Birr',1);
insert into `hrm`.`tb_currency`(`tbc_id`,`tbc_currency_id`,`tbc_name`,`tbc_local_currency_kurs`) values (41,'EUR','Euro',1);
insert into `hrm`.`tb_currency`(`tbc_id`,`tbc_currency_id`,`tbc_name`,`tbc_local_currency_kurs`) values (42,'FJD','Fiji Dollar',1);
insert into `hrm`.`tb_currency`(`tbc_id`,`tbc_currency_id`,`tbc_name`,`tbc_local_currency_kurs`) values (43,'FKP','Falkland Islands Pound',1);
insert into `hrm`.`tb_currency`(`tbc_id`,`tbc_currency_id`,`tbc_name`,`tbc_local_currency_kurs`) values (44,'GBP','Pound Sterling',1);
insert into `hrm`.`tb_currency`(`tbc_id`,`tbc_currency_id`,`tbc_name`,`tbc_local_currency_kurs`) values (45,'GHC','Ghanaian Cedi',1);
insert into `hrm`.`tb_currency`(`tbc_id`,`tbc_currency_id`,`tbc_name`,`tbc_local_currency_kurs`) values (46,'GIP','Gibraltar Pound',1);
insert into `hrm`.`tb_currency`(`tbc_id`,`tbc_currency_id`,`tbc_name`,`tbc_local_currency_kurs`) values (47,'GMD','Gambian Dalasi',1);
insert into `hrm`.`tb_currency`(`tbc_id`,`tbc_currency_id`,`tbc_name`,`tbc_local_currency_kurs`) values (48,'GNF','Guinea Franc',1);
insert into `hrm`.`tb_currency`(`tbc_id`,`tbc_currency_id`,`tbc_name`,`tbc_local_currency_kurs`) values (49,'GTQ','Guatemalan Quetzal',1);
insert into `hrm`.`tb_currency`(`tbc_id`,`tbc_currency_id`,`tbc_name`,`tbc_local_currency_kurs`) values (50,'GYD','Guyanan Dollar',1);
insert into `hrm`.`tb_currency`(`tbc_id`,`tbc_currency_id`,`tbc_name`,`tbc_local_currency_kurs`) values (51,'HKD','Hong Kong Dollar',1);
insert into `hrm`.`tb_currency`(`tbc_id`,`tbc_currency_id`,`tbc_name`,`tbc_local_currency_kurs`) values (52,'HNL','Honduran Lempira',1);
insert into `hrm`.`tb_currency`(`tbc_id`,`tbc_currency_id`,`tbc_name`,`tbc_local_currency_kurs`) values (53,'HRK','Croatian Kuna',1);
insert into `hrm`.`tb_currency`(`tbc_id`,`tbc_currency_id`,`tbc_name`,`tbc_local_currency_kurs`) values (54,'HTG','Haitian Gourde',1);
insert into `hrm`.`tb_currency`(`tbc_id`,`tbc_currency_id`,`tbc_name`,`tbc_local_currency_kurs`) values (55,'HUF','Hungarian Forint',1);
insert into `hrm`.`tb_currency`(`tbc_id`,`tbc_currency_id`,`tbc_name`,`tbc_local_currency_kurs`) values (56,'IDR','Indonesian Rupiah',1);
insert into `hrm`.`tb_currency`(`tbc_id`,`tbc_currency_id`,`tbc_name`,`tbc_local_currency_kurs`) values (57,'ILS','Israeli New Shekel',1);
insert into `hrm`.`tb_currency`(`tbc_id`,`tbc_currency_id`,`tbc_name`,`tbc_local_currency_kurs`) values (58,'INR','Indian Rupee',1);
insert into `hrm`.`tb_currency`(`tbc_id`,`tbc_currency_id`,`tbc_name`,`tbc_local_currency_kurs`) values (59,'IQD','Iraqi Dinar',1);
insert into `hrm`.`tb_currency`(`tbc_id`,`tbc_currency_id`,`tbc_name`,`tbc_local_currency_kurs`) values (60,'IRR','Iranian Rial',1);
insert into `hrm`.`tb_currency`(`tbc_id`,`tbc_currency_id`,`tbc_name`,`tbc_local_currency_kurs`) values (61,'ISK','Iceland Krona',1);
insert into `hrm`.`tb_currency`(`tbc_id`,`tbc_currency_id`,`tbc_name`,`tbc_local_currency_kurs`) values (62,'JMD','Jamaican Dollar',1);
insert into `hrm`.`tb_currency`(`tbc_id`,`tbc_currency_id`,`tbc_name`,`tbc_local_currency_kurs`) values (63,'JOD','Jordanian Dinar',1);
insert into `hrm`.`tb_currency`(`tbc_id`,`tbc_currency_id`,`tbc_name`,`tbc_local_currency_kurs`) values (64,'JPY','Japanese Yen',1);
insert into `hrm`.`tb_currency`(`tbc_id`,`tbc_currency_id`,`tbc_name`,`tbc_local_currency_kurs`) values (65,'KES','Kenyan Shilling',1);
insert into `hrm`.`tb_currency`(`tbc_id`,`tbc_currency_id`,`tbc_name`,`tbc_local_currency_kurs`) values (66,'KHR','Kampuchean Riel',1);
insert into `hrm`.`tb_currency`(`tbc_id`,`tbc_currency_id`,`tbc_name`,`tbc_local_currency_kurs`) values (67,'KMF','Comoros Franc',1);
insert into `hrm`.`tb_currency`(`tbc_id`,`tbc_currency_id`,`tbc_name`,`tbc_local_currency_kurs`) values (68,'KPW','North Korean Won',1);
insert into `hrm`.`tb_currency`(`tbc_id`,`tbc_currency_id`,`tbc_name`,`tbc_local_currency_kurs`) values (69,'KRW','Korean Won',1);
insert into `hrm`.`tb_currency`(`tbc_id`,`tbc_currency_id`,`tbc_name`,`tbc_local_currency_kurs`) values (70,'KWD','Kuwaiti Dinar',1);
insert into `hrm`.`tb_currency`(`tbc_id`,`tbc_currency_id`,`tbc_name`,`tbc_local_currency_kurs`) values (71,'KYD','Cayman Islands Dollar',1);
insert into `hrm`.`tb_currency`(`tbc_id`,`tbc_currency_id`,`tbc_name`,`tbc_local_currency_kurs`) values (72,'KZT','Kazakhstan Tenge',1);
insert into `hrm`.`tb_currency`(`tbc_id`,`tbc_currency_id`,`tbc_name`,`tbc_local_currency_kurs`) values (73,'LAK','Lao Kip',1);
insert into `hrm`.`tb_currency`(`tbc_id`,`tbc_currency_id`,`tbc_name`,`tbc_local_currency_kurs`) values (74,'LBP','Lebanese Pound',1);
insert into `hrm`.`tb_currency`(`tbc_id`,`tbc_currency_id`,`tbc_name`,`tbc_local_currency_kurs`) values (75,'LKR','Sri Lanka Rupee',1);
insert into `hrm`.`tb_currency`(`tbc_id`,`tbc_currency_id`,`tbc_name`,`tbc_local_currency_kurs`) values (76,'LRD','Liberian Dollar',1);
insert into `hrm`.`tb_currency`(`tbc_id`,`tbc_currency_id`,`tbc_name`,`tbc_local_currency_kurs`) values (77,'LSL','Lesotho Loti',1);
insert into `hrm`.`tb_currency`(`tbc_id`,`tbc_currency_id`,`tbc_name`,`tbc_local_currency_kurs`) values (78,'LTL','Lithuanian Litas',1);
insert into `hrm`.`tb_currency`(`tbc_id`,`tbc_currency_id`,`tbc_name`,`tbc_local_currency_kurs`) values (79,'LVL','Latvian Lats',1);
insert into `hrm`.`tb_currency`(`tbc_id`,`tbc_currency_id`,`tbc_name`,`tbc_local_currency_kurs`) values (80,'LYD','Libyan Dinar',1);
insert into `hrm`.`tb_currency`(`tbc_id`,`tbc_currency_id`,`tbc_name`,`tbc_local_currency_kurs`) values (81,'MAD','Moroccan Dirham',1);
insert into `hrm`.`tb_currency`(`tbc_id`,`tbc_currency_id`,`tbc_name`,`tbc_local_currency_kurs`) values (82,'MGF','Malagasy Franc',1);
insert into `hrm`.`tb_currency`(`tbc_id`,`tbc_currency_id`,`tbc_name`,`tbc_local_currency_kurs`) values (83,'MMK','Myanmar Kyat',1);
insert into `hrm`.`tb_currency`(`tbc_id`,`tbc_currency_id`,`tbc_name`,`tbc_local_currency_kurs`) values (84,'MNT','Mongolian Tugrik',1);
insert into `hrm`.`tb_currency`(`tbc_id`,`tbc_currency_id`,`tbc_name`,`tbc_local_currency_kurs`) values (85,'MOP','Macau Pataca',1);
insert into `hrm`.`tb_currency`(`tbc_id`,`tbc_currency_id`,`tbc_name`,`tbc_local_currency_kurs`) values (86,'MRO','Mauritanian Ouguiya',1);
insert into `hrm`.`tb_currency`(`tbc_id`,`tbc_currency_id`,`tbc_name`,`tbc_local_currency_kurs`) values (87,'MTL','Maltese Lira',1);
insert into `hrm`.`tb_currency`(`tbc_id`,`tbc_currency_id`,`tbc_name`,`tbc_local_currency_kurs`) values (88,'MUR','Mauritius Rupee',1);
insert into `hrm`.`tb_currency`(`tbc_id`,`tbc_currency_id`,`tbc_name`,`tbc_local_currency_kurs`) values (89,'MVR','Maldive Rufiyaa',1);
insert into `hrm`.`tb_currency`(`tbc_id`,`tbc_currency_id`,`tbc_name`,`tbc_local_currency_kurs`) values (90,'MWK','Malawi Kwacha',1);
insert into `hrm`.`tb_currency`(`tbc_id`,`tbc_currency_id`,`tbc_name`,`tbc_local_currency_kurs`) values (91,'MXN','Mexican New Peso',1);
insert into `hrm`.`tb_currency`(`tbc_id`,`tbc_currency_id`,`tbc_name`,`tbc_local_currency_kurs`) values (92,'MXP','Mexican Peso',1);
insert into `hrm`.`tb_currency`(`tbc_id`,`tbc_currency_id`,`tbc_name`,`tbc_local_currency_kurs`) values (93,'MYR','Malaysian Ringgit',1);
insert into `hrm`.`tb_currency`(`tbc_id`,`tbc_currency_id`,`tbc_name`,`tbc_local_currency_kurs`) values (94,'MZM','Mozambique Metical',1);
insert into `hrm`.`tb_currency`(`tbc_id`,`tbc_currency_id`,`tbc_name`,`tbc_local_currency_kurs`) values (95,'NAD','Namibia Dollar',1);
insert into `hrm`.`tb_currency`(`tbc_id`,`tbc_currency_id`,`tbc_name`,`tbc_local_currency_kurs`) values (96,'NGN','Nigerian Naira',1);
insert into `hrm`.`tb_currency`(`tbc_id`,`tbc_currency_id`,`tbc_name`,`tbc_local_currency_kurs`) values (97,'NIO','Nicaraguan Cordoba Oro',1);
insert into `hrm`.`tb_currency`(`tbc_id`,`tbc_currency_id`,`tbc_name`,`tbc_local_currency_kurs`) values (98,'NOK','Norwegian Krona',1);
insert into `hrm`.`tb_currency`(`tbc_id`,`tbc_currency_id`,`tbc_name`,`tbc_local_currency_kurs`) values (99,'NPR','Nepalese Rupee',1);
insert into `hrm`.`tb_currency`(`tbc_id`,`tbc_currency_id`,`tbc_name`,`tbc_local_currency_kurs`) values (100,'NZD','New Zealand Dollar',1);
insert into `hrm`.`tb_currency`(`tbc_id`,`tbc_currency_id`,`tbc_name`,`tbc_local_currency_kurs`) values (101,'OMR','Omani Rial',1);
insert into `hrm`.`tb_currency`(`tbc_id`,`tbc_currency_id`,`tbc_name`,`tbc_local_currency_kurs`) values (102,'PAB','Panamanian Balboa',1);
insert into `hrm`.`tb_currency`(`tbc_id`,`tbc_currency_id`,`tbc_name`,`tbc_local_currency_kurs`) values (103,'PEN','Peruvian Nuevo Sol',1);
insert into `hrm`.`tb_currency`(`tbc_id`,`tbc_currency_id`,`tbc_name`,`tbc_local_currency_kurs`) values (104,'PGK','Papua New Guinea Kina',1);
insert into `hrm`.`tb_currency`(`tbc_id`,`tbc_currency_id`,`tbc_name`,`tbc_local_currency_kurs`) values (105,'PHP','Philippine Peso',1);
insert into `hrm`.`tb_currency`(`tbc_id`,`tbc_currency_id`,`tbc_name`,`tbc_local_currency_kurs`) values (106,'PKR','Pakistan Rupee',1);
insert into `hrm`.`tb_currency`(`tbc_id`,`tbc_currency_id`,`tbc_name`,`tbc_local_currency_kurs`) values (107,'PLN','Polish Zloty',1);
insert into `hrm`.`tb_currency`(`tbc_id`,`tbc_currency_id`,`tbc_name`,`tbc_local_currency_kurs`) values (108,'PYG','Paraguay Guarani',1);
insert into `hrm`.`tb_currency`(`tbc_id`,`tbc_currency_id`,`tbc_name`,`tbc_local_currency_kurs`) values (109,'QAR','Qatari Rial',1);
insert into `hrm`.`tb_currency`(`tbc_id`,`tbc_currency_id`,`tbc_name`,`tbc_local_currency_kurs`) values (110,'ROL','Romanian Leu',1);
insert into `hrm`.`tb_currency`(`tbc_id`,`tbc_currency_id`,`tbc_name`,`tbc_local_currency_kurs`) values (111,'RUB','Russian Rouble',1);
insert into `hrm`.`tb_currency`(`tbc_id`,`tbc_currency_id`,`tbc_name`,`tbc_local_currency_kurs`) values (112,'RUR','Russia Rubles',1);
insert into `hrm`.`tb_currency`(`tbc_id`,`tbc_currency_id`,`tbc_name`,`tbc_local_currency_kurs`) values (113,'SAR','South African Rand',1);
insert into `hrm`.`tb_currency`(`tbc_id`,`tbc_currency_id`,`tbc_name`,`tbc_local_currency_kurs`) values (114,'SBD','Solomon Islands Dollar',1);
insert into `hrm`.`tb_currency`(`tbc_id`,`tbc_currency_id`,`tbc_name`,`tbc_local_currency_kurs`) values (115,'SCR','Seychelles Rupee',1);
insert into `hrm`.`tb_currency`(`tbc_id`,`tbc_currency_id`,`tbc_name`,`tbc_local_currency_kurs`) values (116,'SDD','Sudanese Dinar',1);
insert into `hrm`.`tb_currency`(`tbc_id`,`tbc_currency_id`,`tbc_name`,`tbc_local_currency_kurs`) values (117,'SDP','Sudanese Pound',1);
insert into `hrm`.`tb_currency`(`tbc_id`,`tbc_currency_id`,`tbc_name`,`tbc_local_currency_kurs`) values (118,'SEK','Swedish Krona',1);
insert into `hrm`.`tb_currency`(`tbc_id`,`tbc_currency_id`,`tbc_name`,`tbc_local_currency_kurs`) values (119,'SGD','Singapore Dollar',1);
insert into `hrm`.`tb_currency`(`tbc_id`,`tbc_currency_id`,`tbc_name`,`tbc_local_currency_kurs`) values (120,'SHP','St. Helena Pound',1);
insert into `hrm`.`tb_currency`(`tbc_id`,`tbc_currency_id`,`tbc_name`,`tbc_local_currency_kurs`) values (121,'SKK','Slovak Koruna',1);
insert into `hrm`.`tb_currency`(`tbc_id`,`tbc_currency_id`,`tbc_name`,`tbc_local_currency_kurs`) values (122,'SLL','Sierra Leone Leone',1);
insert into `hrm`.`tb_currency`(`tbc_id`,`tbc_currency_id`,`tbc_name`,`tbc_local_currency_kurs`) values (123,'SOS','Somali Shilling',1);
insert into `hrm`.`tb_currency`(`tbc_id`,`tbc_currency_id`,`tbc_name`,`tbc_local_currency_kurs`) values (124,'SRG','Suriname Guilder',1);
insert into `hrm`.`tb_currency`(`tbc_id`,`tbc_currency_id`,`tbc_name`,`tbc_local_currency_kurs`) values (125,'STD','Sao Tome/Principe Dobra',1);
insert into `hrm`.`tb_currency`(`tbc_id`,`tbc_currency_id`,`tbc_name`,`tbc_local_currency_kurs`) values (126,'SVC','El Salvador Colon',1);
insert into `hrm`.`tb_currency`(`tbc_id`,`tbc_currency_id`,`tbc_name`,`tbc_local_currency_kurs`) values (127,'SYP','Syrian Pound',1);
insert into `hrm`.`tb_currency`(`tbc_id`,`tbc_currency_id`,`tbc_name`,`tbc_local_currency_kurs`) values (128,'SZL','Swaziland Lilangeni',1);
insert into `hrm`.`tb_currency`(`tbc_id`,`tbc_currency_id`,`tbc_name`,`tbc_local_currency_kurs`) values (129,'THB','Thai Baht',1);
insert into `hrm`.`tb_currency`(`tbc_id`,`tbc_currency_id`,`tbc_name`,`tbc_local_currency_kurs`) values (130,'TND','Tunisian Dinar',1);
insert into `hrm`.`tb_currency`(`tbc_id`,`tbc_currency_id`,`tbc_name`,`tbc_local_currency_kurs`) values (131,'TOP','Tongan Pa''anga',1);
insert into `hrm`.`tb_currency`(`tbc_id`,`tbc_currency_id`,`tbc_name`,`tbc_local_currency_kurs`) values (132,'TRL','Turkish Lira',1);
insert into `hrm`.`tb_currency`(`tbc_id`,`tbc_currency_id`,`tbc_name`,`tbc_local_currency_kurs`) values (133,'TTD','Trinidad/Tobago Dollar',1);
insert into `hrm`.`tb_currency`(`tbc_id`,`tbc_currency_id`,`tbc_name`,`tbc_local_currency_kurs`) values (134,'TWD','Taiwan Dollar',1);
insert into `hrm`.`tb_currency`(`tbc_id`,`tbc_currency_id`,`tbc_name`,`tbc_local_currency_kurs`) values (135,'TZS','Tanzanian Shilling',1);
insert into `hrm`.`tb_currency`(`tbc_id`,`tbc_currency_id`,`tbc_name`,`tbc_local_currency_kurs`) values (136,'UAH','Ukraine Hryvnia',1);
insert into `hrm`.`tb_currency`(`tbc_id`,`tbc_currency_id`,`tbc_name`,`tbc_local_currency_kurs`) values (137,'UGX','Uganda Shilling',1);
insert into `hrm`.`tb_currency`(`tbc_id`,`tbc_currency_id`,`tbc_name`,`tbc_local_currency_kurs`) values (138,'USD','United States Dollar',8900);
insert into `hrm`.`tb_currency`(`tbc_id`,`tbc_currency_id`,`tbc_name`,`tbc_local_currency_kurs`) values (139,'UYP','Uruguayan Peso',1);
insert into `hrm`.`tb_currency`(`tbc_id`,`tbc_currency_id`,`tbc_name`,`tbc_local_currency_kurs`) values (140,'VEB','Venezuelan Bolivar',1);
insert into `hrm`.`tb_currency`(`tbc_id`,`tbc_currency_id`,`tbc_name`,`tbc_local_currency_kurs`) values (141,'VND','Vietnamese Dong',1);
insert into `hrm`.`tb_currency`(`tbc_id`,`tbc_currency_id`,`tbc_name`,`tbc_local_currency_kurs`) values (142,'VUV','Vanuatu Vatu',1);
insert into `hrm`.`tb_currency`(`tbc_id`,`tbc_currency_id`,`tbc_name`,`tbc_local_currency_kurs`) values (143,'WST','Samoan Tala',1);
insert into `hrm`.`tb_currency`(`tbc_id`,`tbc_currency_id`,`tbc_name`,`tbc_local_currency_kurs`) values (144,'XAF','CFA Franc BEAC',1);
insert into `hrm`.`tb_currency`(`tbc_id`,`tbc_currency_id`,`tbc_name`,`tbc_local_currency_kurs`) values (145,'XAG','Silver (oz.)',1);
insert into `hrm`.`tb_currency`(`tbc_id`,`tbc_currency_id`,`tbc_name`,`tbc_local_currency_kurs`) values (146,'XAU','Gold (oz.)',1);
insert into `hrm`.`tb_currency`(`tbc_id`,`tbc_currency_id`,`tbc_name`,`tbc_local_currency_kurs`) values (147,'XCD','Eastern Caribbean Dollars',1);
insert into `hrm`.`tb_currency`(`tbc_id`,`tbc_currency_id`,`tbc_name`,`tbc_local_currency_kurs`) values (148,'XDR','IMF Special Drawing Right',1);
insert into `hrm`.`tb_currency`(`tbc_id`,`tbc_currency_id`,`tbc_name`,`tbc_local_currency_kurs`) values (149,'XOF','CFA Franc BCEAO',1);
insert into `hrm`.`tb_currency`(`tbc_id`,`tbc_currency_id`,`tbc_name`,`tbc_local_currency_kurs`) values (150,'XPD','Palladium (oz.)',1);
insert into `hrm`.`tb_currency`(`tbc_id`,`tbc_currency_id`,`tbc_name`,`tbc_local_currency_kurs`) values (151,'XPF','Franc des Comptoirs franÃ§ais du Pacifique',1);
insert into `hrm`.`tb_currency`(`tbc_id`,`tbc_currency_id`,`tbc_name`,`tbc_local_currency_kurs`) values (152,'XPT','Platinum (oz.)',1);
insert into `hrm`.`tb_currency`(`tbc_id`,`tbc_currency_id`,`tbc_name`,`tbc_local_currency_kurs`) values (153,'YER','Yemeni Riyal',1);
insert into `hrm`.`tb_currency`(`tbc_id`,`tbc_currency_id`,`tbc_name`,`tbc_local_currency_kurs`) values (154,'YUM','Yugoslavian Dinar',1);
insert into `hrm`.`tb_currency`(`tbc_id`,`tbc_currency_id`,`tbc_name`,`tbc_local_currency_kurs`) values (155,'YUN','Yugoslav Dinar',1);
insert into `hrm`.`tb_currency`(`tbc_id`,`tbc_currency_id`,`tbc_name`,`tbc_local_currency_kurs`) values (156,'ZAR','South African Rand',1);
insert into `hrm`.`tb_currency`(`tbc_id`,`tbc_currency_id`,`tbc_name`,`tbc_local_currency_kurs`) values (157,'ZMK','Zambian Kwacha',1);
insert into `hrm`.`tb_currency`(`tbc_id`,`tbc_currency_id`,`tbc_name`,`tbc_local_currency_kurs`) values (158,'ZRN','New Zaire',1);
insert into `hrm`.`tb_currency`(`tbc_id`,`tbc_currency_id`,`tbc_name`,`tbc_local_currency_kurs`) values (159,'ZWD','Zimbabwe Dollar',1);
