USE hrm;

CREATE TABLE `tb_currency` (
  `tbc_id` int(11) NOT NULL AUTO_INCREMENT,
  `tbc_currency_id` varchar(45) DEFAULT NULL COMMENT 'NAME+ID',
  `tbc_name` varchar(45) DEFAULT NULL,
  PRIMARY KEY (`tbc_id`)
) ENGINE=InnoDB AUTO_INCREMENT=160 DEFAULT CHARSET=latin1;


insert into `hrm`.`tb_currency`(`tbc_id`,`tbc_currency_id`,`tbc_name`) values (1,'AED','Utd. Arab Emir. Dirham');
insert into `hrm`.`tb_currency`(`tbc_id`,`tbc_currency_id`,`tbc_name`) values (2,'AFN','Afghanistan Afghani');
insert into `hrm`.`tb_currency`(`tbc_id`,`tbc_currency_id`,`tbc_name`) values (3,'ALL','Albanian Lek');
insert into `hrm`.`tb_currency`(`tbc_id`,`tbc_currency_id`,`tbc_name`) values (4,'ANG','NL Antillian Guilder');
insert into `hrm`.`tb_currency`(`tbc_id`,`tbc_currency_id`,`tbc_name`) values (5,'AOR','Angolan New Kwanza');
insert into `hrm`.`tb_currency`(`tbc_id`,`tbc_currency_id`,`tbc_name`) values (6,'ARP','Argentina Pesos');
insert into `hrm`.`tb_currency`(`tbc_id`,`tbc_currency_id`,`tbc_name`) values (7,'ARS','Argentine Peso');
insert into `hrm`.`tb_currency`(`tbc_id`,`tbc_currency_id`,`tbc_name`) values (8,'AUD','Australian Dollar');
insert into `hrm`.`tb_currency`(`tbc_id`,`tbc_currency_id`,`tbc_name`) values (9,'AWG','Aruban Florin');
insert into `hrm`.`tb_currency`(`tbc_id`,`tbc_currency_id`,`tbc_name`) values (10,'BBD','Barbados Dollar');
insert into `hrm`.`tb_currency`(`tbc_id`,`tbc_currency_id`,`tbc_name`) values (11,'BDT','Bangladeshi Taka');
insert into `hrm`.`tb_currency`(`tbc_id`,`tbc_currency_id`,`tbc_name`) values (12,'BGL','Bulgarian Lev');
insert into `hrm`.`tb_currency`(`tbc_id`,`tbc_currency_id`,`tbc_name`) values (13,'BHD','Bahraini Dinar');
insert into `hrm`.`tb_currency`(`tbc_id`,`tbc_currency_id`,`tbc_name`) values (14,'BIF','Burundi Franc');
insert into `hrm`.`tb_currency`(`tbc_id`,`tbc_currency_id`,`tbc_name`) values (15,'BMD','Bermudian Dollar');
insert into `hrm`.`tb_currency`(`tbc_id`,`tbc_currency_id`,`tbc_name`) values (16,'BND','Brunei Dollar');
insert into `hrm`.`tb_currency`(`tbc_id`,`tbc_currency_id`,`tbc_name`) values (17,'BOB','Bolivian Boliviano');
insert into `hrm`.`tb_currency`(`tbc_id`,`tbc_currency_id`,`tbc_name`) values (18,'BRL','Brazilian Real');
insert into `hrm`.`tb_currency`(`tbc_id`,`tbc_currency_id`,`tbc_name`) values (19,'BSD','Bahamian Dollar');
insert into `hrm`.`tb_currency`(`tbc_id`,`tbc_currency_id`,`tbc_name`) values (20,'BTN','Bhutan Ngultrum');
insert into `hrm`.`tb_currency`(`tbc_id`,`tbc_currency_id`,`tbc_name`) values (21,'BWP','Botswana Pula');
insert into `hrm`.`tb_currency`(`tbc_id`,`tbc_currency_id`,`tbc_name`) values (22,'BZD','Belize Dollar');
insert into `hrm`.`tb_currency`(`tbc_id`,`tbc_currency_id`,`tbc_name`) values (23,'CAD','Canadian Dollar');
insert into `hrm`.`tb_currency`(`tbc_id`,`tbc_currency_id`,`tbc_name`) values (24,'CHF','Swiss Franc');
insert into `hrm`.`tb_currency`(`tbc_id`,`tbc_currency_id`,`tbc_name`) values (25,'CLP','Chilean Peso');
insert into `hrm`.`tb_currency`(`tbc_id`,`tbc_currency_id`,`tbc_name`) values (26,'CNY','Chinese Yuan Renminbi');
insert into `hrm`.`tb_currency`(`tbc_id`,`tbc_currency_id`,`tbc_name`) values (27,'COP','Colombian Peso');
insert into `hrm`.`tb_currency`(`tbc_id`,`tbc_currency_id`,`tbc_name`) values (28,'CRC','Costa Rican Colon');
insert into `hrm`.`tb_currency`(`tbc_id`,`tbc_currency_id`,`tbc_name`) values (29,'CUP','Cuban Peso');
insert into `hrm`.`tb_currency`(`tbc_id`,`tbc_currency_id`,`tbc_name`) values (30,'CVE','Cape Verde Escudo');
insert into `hrm`.`tb_currency`(`tbc_id`,`tbc_currency_id`,`tbc_name`) values (31,'CYP','Cyprus Pound');
insert into `hrm`.`tb_currency`(`tbc_id`,`tbc_currency_id`,`tbc_name`) values (32,'CZK','Czech Koruna');
insert into `hrm`.`tb_currency`(`tbc_id`,`tbc_currency_id`,`tbc_name`) values (33,'DJF','Djibouti Franc');
insert into `hrm`.`tb_currency`(`tbc_id`,`tbc_currency_id`,`tbc_name`) values (34,'DKK','Danish Krona');
insert into `hrm`.`tb_currency`(`tbc_id`,`tbc_currency_id`,`tbc_name`) values (35,'DOP','Dominican Peso');
insert into `hrm`.`tb_currency`(`tbc_id`,`tbc_currency_id`,`tbc_name`) values (36,'DZD','Algerian Dinar');
insert into `hrm`.`tb_currency`(`tbc_id`,`tbc_currency_id`,`tbc_name`) values (37,'ECS','Ecuador Sucre');
insert into `hrm`.`tb_currency`(`tbc_id`,`tbc_currency_id`,`tbc_name`) values (38,'EEK','Estonian Krona');
insert into `hrm`.`tb_currency`(`tbc_id`,`tbc_currency_id`,`tbc_name`) values (39,'EGP','Egyptian Pound');
insert into `hrm`.`tb_currency`(`tbc_id`,`tbc_currency_id`,`tbc_name`) values (40,'ETB','Ethiopian Birr');
insert into `hrm`.`tb_currency`(`tbc_id`,`tbc_currency_id`,`tbc_name`) values (41,'EUR','Euro');
insert into `hrm`.`tb_currency`(`tbc_id`,`tbc_currency_id`,`tbc_name`) values (42,'FJD','Fiji Dollar');
insert into `hrm`.`tb_currency`(`tbc_id`,`tbc_currency_id`,`tbc_name`) values (43,'FKP','Falkland Islands Pound');
insert into `hrm`.`tb_currency`(`tbc_id`,`tbc_currency_id`,`tbc_name`) values (44,'GBP','Pound Sterling');
insert into `hrm`.`tb_currency`(`tbc_id`,`tbc_currency_id`,`tbc_name`) values (45,'GHC','Ghanaian Cedi');
insert into `hrm`.`tb_currency`(`tbc_id`,`tbc_currency_id`,`tbc_name`) values (46,'GIP','Gibraltar Pound');
insert into `hrm`.`tb_currency`(`tbc_id`,`tbc_currency_id`,`tbc_name`) values (47,'GMD','Gambian Dalasi');
insert into `hrm`.`tb_currency`(`tbc_id`,`tbc_currency_id`,`tbc_name`) values (48,'GNF','Guinea Franc');
insert into `hrm`.`tb_currency`(`tbc_id`,`tbc_currency_id`,`tbc_name`) values (49,'GTQ','Guatemalan Quetzal');
insert into `hrm`.`tb_currency`(`tbc_id`,`tbc_currency_id`,`tbc_name`) values (50,'GYD','Guyanan Dollar');
insert into `hrm`.`tb_currency`(`tbc_id`,`tbc_currency_id`,`tbc_name`) values (51,'HKD','Hong Kong Dollar');
insert into `hrm`.`tb_currency`(`tbc_id`,`tbc_currency_id`,`tbc_name`) values (52,'HNL','Honduran Lempira');
insert into `hrm`.`tb_currency`(`tbc_id`,`tbc_currency_id`,`tbc_name`) values (53,'HRK','Croatian Kuna');
insert into `hrm`.`tb_currency`(`tbc_id`,`tbc_currency_id`,`tbc_name`) values (54,'HTG','Haitian Gourde');
insert into `hrm`.`tb_currency`(`tbc_id`,`tbc_currency_id`,`tbc_name`) values (55,'HUF','Hungarian Forint');
insert into `hrm`.`tb_currency`(`tbc_id`,`tbc_currency_id`,`tbc_name`) values (56,'IDR','Indonesian Rupiah');
insert into `hrm`.`tb_currency`(`tbc_id`,`tbc_currency_id`,`tbc_name`) values (57,'ILS','Israeli New Shekel');
insert into `hrm`.`tb_currency`(`tbc_id`,`tbc_currency_id`,`tbc_name`) values (58,'INR','Indian Rupee');
insert into `hrm`.`tb_currency`(`tbc_id`,`tbc_currency_id`,`tbc_name`) values (59,'IQD','Iraqi Dinar');
insert into `hrm`.`tb_currency`(`tbc_id`,`tbc_currency_id`,`tbc_name`) values (60,'IRR','Iranian Rial');
insert into `hrm`.`tb_currency`(`tbc_id`,`tbc_currency_id`,`tbc_name`) values (61,'ISK','Iceland Krona');
insert into `hrm`.`tb_currency`(`tbc_id`,`tbc_currency_id`,`tbc_name`) values (62,'JMD','Jamaican Dollar');
insert into `hrm`.`tb_currency`(`tbc_id`,`tbc_currency_id`,`tbc_name`) values (63,'JOD','Jordanian Dinar');
insert into `hrm`.`tb_currency`(`tbc_id`,`tbc_currency_id`,`tbc_name`) values (64,'JPY','Japanese Yen');
insert into `hrm`.`tb_currency`(`tbc_id`,`tbc_currency_id`,`tbc_name`) values (65,'KES','Kenyan Shilling');
insert into `hrm`.`tb_currency`(`tbc_id`,`tbc_currency_id`,`tbc_name`) values (66,'KHR','Kampuchean Riel');
insert into `hrm`.`tb_currency`(`tbc_id`,`tbc_currency_id`,`tbc_name`) values (67,'KMF','Comoros Franc');
insert into `hrm`.`tb_currency`(`tbc_id`,`tbc_currency_id`,`tbc_name`) values (68,'KPW','North Korean Won');
insert into `hrm`.`tb_currency`(`tbc_id`,`tbc_currency_id`,`tbc_name`) values (69,'KRW','Korean Won');
insert into `hrm`.`tb_currency`(`tbc_id`,`tbc_currency_id`,`tbc_name`) values (70,'KWD','Kuwaiti Dinar');
insert into `hrm`.`tb_currency`(`tbc_id`,`tbc_currency_id`,`tbc_name`) values (71,'KYD','Cayman Islands Dollar');
insert into `hrm`.`tb_currency`(`tbc_id`,`tbc_currency_id`,`tbc_name`) values (72,'KZT','Kazakhstan Tenge');
insert into `hrm`.`tb_currency`(`tbc_id`,`tbc_currency_id`,`tbc_name`) values (73,'LAK','Lao Kip');
insert into `hrm`.`tb_currency`(`tbc_id`,`tbc_currency_id`,`tbc_name`) values (74,'LBP','Lebanese Pound');
insert into `hrm`.`tb_currency`(`tbc_id`,`tbc_currency_id`,`tbc_name`) values (75,'LKR','Sri Lanka Rupee');
insert into `hrm`.`tb_currency`(`tbc_id`,`tbc_currency_id`,`tbc_name`) values (76,'LRD','Liberian Dollar');
insert into `hrm`.`tb_currency`(`tbc_id`,`tbc_currency_id`,`tbc_name`) values (77,'LSL','Lesotho Loti');
insert into `hrm`.`tb_currency`(`tbc_id`,`tbc_currency_id`,`tbc_name`) values (78,'LTL','Lithuanian Litas');
insert into `hrm`.`tb_currency`(`tbc_id`,`tbc_currency_id`,`tbc_name`) values (79,'LVL','Latvian Lats');
insert into `hrm`.`tb_currency`(`tbc_id`,`tbc_currency_id`,`tbc_name`) values (80,'LYD','Libyan Dinar');
insert into `hrm`.`tb_currency`(`tbc_id`,`tbc_currency_id`,`tbc_name`) values (81,'MAD','Moroccan Dirham');
insert into `hrm`.`tb_currency`(`tbc_id`,`tbc_currency_id`,`tbc_name`) values (82,'MGF','Malagasy Franc');
insert into `hrm`.`tb_currency`(`tbc_id`,`tbc_currency_id`,`tbc_name`) values (83,'MMK','Myanmar Kyat');
insert into `hrm`.`tb_currency`(`tbc_id`,`tbc_currency_id`,`tbc_name`) values (84,'MNT','Mongolian Tugrik');
insert into `hrm`.`tb_currency`(`tbc_id`,`tbc_currency_id`,`tbc_name`) values (85,'MOP','Macau Pataca');
insert into `hrm`.`tb_currency`(`tbc_id`,`tbc_currency_id`,`tbc_name`) values (86,'MRO','Mauritanian Ouguiya');
insert into `hrm`.`tb_currency`(`tbc_id`,`tbc_currency_id`,`tbc_name`) values (87,'MTL','Maltese Lira');
insert into `hrm`.`tb_currency`(`tbc_id`,`tbc_currency_id`,`tbc_name`) values (88,'MUR','Mauritius Rupee');
insert into `hrm`.`tb_currency`(`tbc_id`,`tbc_currency_id`,`tbc_name`) values (89,'MVR','Maldive Rufiyaa');
insert into `hrm`.`tb_currency`(`tbc_id`,`tbc_currency_id`,`tbc_name`) values (90,'MWK','Malawi Kwacha');
insert into `hrm`.`tb_currency`(`tbc_id`,`tbc_currency_id`,`tbc_name`) values (91,'MXN','Mexican New Peso');
insert into `hrm`.`tb_currency`(`tbc_id`,`tbc_currency_id`,`tbc_name`) values (92,'MXP','Mexican Peso');
insert into `hrm`.`tb_currency`(`tbc_id`,`tbc_currency_id`,`tbc_name`) values (93,'MYR','Malaysian Ringgit');
insert into `hrm`.`tb_currency`(`tbc_id`,`tbc_currency_id`,`tbc_name`) values (94,'MZM','Mozambique Metical');
insert into `hrm`.`tb_currency`(`tbc_id`,`tbc_currency_id`,`tbc_name`) values (95,'NAD','Namibia Dollar');
insert into `hrm`.`tb_currency`(`tbc_id`,`tbc_currency_id`,`tbc_name`) values (96,'NGN','Nigerian Naira');
insert into `hrm`.`tb_currency`(`tbc_id`,`tbc_currency_id`,`tbc_name`) values (97,'NIO','Nicaraguan Cordoba Oro');
insert into `hrm`.`tb_currency`(`tbc_id`,`tbc_currency_id`,`tbc_name`) values (98,'NOK','Norwegian Krona');
insert into `hrm`.`tb_currency`(`tbc_id`,`tbc_currency_id`,`tbc_name`) values (99,'NPR','Nepalese Rupee');
insert into `hrm`.`tb_currency`(`tbc_id`,`tbc_currency_id`,`tbc_name`) values (100,'NZD','New Zealand Dollar');
insert into `hrm`.`tb_currency`(`tbc_id`,`tbc_currency_id`,`tbc_name`) values (101,'OMR','Omani Rial');
insert into `hrm`.`tb_currency`(`tbc_id`,`tbc_currency_id`,`tbc_name`) values (102,'PAB','Panamanian Balboa');
insert into `hrm`.`tb_currency`(`tbc_id`,`tbc_currency_id`,`tbc_name`) values (103,'PEN','Peruvian Nuevo Sol');
insert into `hrm`.`tb_currency`(`tbc_id`,`tbc_currency_id`,`tbc_name`) values (104,'PGK','Papua New Guinea Kina');
insert into `hrm`.`tb_currency`(`tbc_id`,`tbc_currency_id`,`tbc_name`) values (105,'PHP','Philippine Peso');
insert into `hrm`.`tb_currency`(`tbc_id`,`tbc_currency_id`,`tbc_name`) values (106,'PKR','Pakistan Rupee');
insert into `hrm`.`tb_currency`(`tbc_id`,`tbc_currency_id`,`tbc_name`) values (107,'PLN','Polish Zloty');
insert into `hrm`.`tb_currency`(`tbc_id`,`tbc_currency_id`,`tbc_name`) values (108,'PYG','Paraguay Guarani');
insert into `hrm`.`tb_currency`(`tbc_id`,`tbc_currency_id`,`tbc_name`) values (109,'QAR','Qatari Rial');
insert into `hrm`.`tb_currency`(`tbc_id`,`tbc_currency_id`,`tbc_name`) values (110,'ROL','Romanian Leu');
insert into `hrm`.`tb_currency`(`tbc_id`,`tbc_currency_id`,`tbc_name`) values (111,'RUB','Russian Rouble');
insert into `hrm`.`tb_currency`(`tbc_id`,`tbc_currency_id`,`tbc_name`) values (112,'RUR','Russia Rubles');
insert into `hrm`.`tb_currency`(`tbc_id`,`tbc_currency_id`,`tbc_name`) values (113,'SAR','South African Rand');
insert into `hrm`.`tb_currency`(`tbc_id`,`tbc_currency_id`,`tbc_name`) values (114,'SBD','Solomon Islands Dollar');
insert into `hrm`.`tb_currency`(`tbc_id`,`tbc_currency_id`,`tbc_name`) values (115,'SCR','Seychelles Rupee');
insert into `hrm`.`tb_currency`(`tbc_id`,`tbc_currency_id`,`tbc_name`) values (116,'SDD','Sudanese Dinar');
insert into `hrm`.`tb_currency`(`tbc_id`,`tbc_currency_id`,`tbc_name`) values (117,'SDP','Sudanese Pound');
insert into `hrm`.`tb_currency`(`tbc_id`,`tbc_currency_id`,`tbc_name`) values (118,'SEK','Swedish Krona');
insert into `hrm`.`tb_currency`(`tbc_id`,`tbc_currency_id`,`tbc_name`) values (119,'SGD','Singapore Dollar');
insert into `hrm`.`tb_currency`(`tbc_id`,`tbc_currency_id`,`tbc_name`) values (120,'SHP','St. Helena Pound');
insert into `hrm`.`tb_currency`(`tbc_id`,`tbc_currency_id`,`tbc_name`) values (121,'SKK','Slovak Koruna');
insert into `hrm`.`tb_currency`(`tbc_id`,`tbc_currency_id`,`tbc_name`) values (122,'SLL','Sierra Leone Leone');
insert into `hrm`.`tb_currency`(`tbc_id`,`tbc_currency_id`,`tbc_name`) values (123,'SOS','Somali Shilling');
insert into `hrm`.`tb_currency`(`tbc_id`,`tbc_currency_id`,`tbc_name`) values (124,'SRG','Suriname Guilder');
insert into `hrm`.`tb_currency`(`tbc_id`,`tbc_currency_id`,`tbc_name`) values (125,'STD','Sao Tome/Principe Dobra');
insert into `hrm`.`tb_currency`(`tbc_id`,`tbc_currency_id`,`tbc_name`) values (126,'SVC','El Salvador Colon');
insert into `hrm`.`tb_currency`(`tbc_id`,`tbc_currency_id`,`tbc_name`) values (127,'SYP','Syrian Pound');
insert into `hrm`.`tb_currency`(`tbc_id`,`tbc_currency_id`,`tbc_name`) values (128,'SZL','Swaziland Lilangeni');
insert into `hrm`.`tb_currency`(`tbc_id`,`tbc_currency_id`,`tbc_name`) values (129,'THB','Thai Baht');
insert into `hrm`.`tb_currency`(`tbc_id`,`tbc_currency_id`,`tbc_name`) values (130,'TND','Tunisian Dinar');
insert into `hrm`.`tb_currency`(`tbc_id`,`tbc_currency_id`,`tbc_name`) values (131,'TOP','Tongan Pa''anga');
insert into `hrm`.`tb_currency`(`tbc_id`,`tbc_currency_id`,`tbc_name`) values (132,'TRL','Turkish Lira');
insert into `hrm`.`tb_currency`(`tbc_id`,`tbc_currency_id`,`tbc_name`) values (133,'TTD','Trinidad/Tobago Dollar');
insert into `hrm`.`tb_currency`(`tbc_id`,`tbc_currency_id`,`tbc_name`) values (134,'TWD','Taiwan Dollar');
insert into `hrm`.`tb_currency`(`tbc_id`,`tbc_currency_id`,`tbc_name`) values (135,'TZS','Tanzanian Shilling');
insert into `hrm`.`tb_currency`(`tbc_id`,`tbc_currency_id`,`tbc_name`) values (136,'UAH','Ukraine Hryvnia');
insert into `hrm`.`tb_currency`(`tbc_id`,`tbc_currency_id`,`tbc_name`) values (137,'UGX','Uganda Shilling');
insert into `hrm`.`tb_currency`(`tbc_id`,`tbc_currency_id`,`tbc_name`) values (138,'USD','United States Dollar');
insert into `hrm`.`tb_currency`(`tbc_id`,`tbc_currency_id`,`tbc_name`) values (139,'UYP','Uruguayan Peso');
insert into `hrm`.`tb_currency`(`tbc_id`,`tbc_currency_id`,`tbc_name`) values (140,'VEB','Venezuelan Bolivar');
insert into `hrm`.`tb_currency`(`tbc_id`,`tbc_currency_id`,`tbc_name`) values (141,'VND','Vietnamese Dong');
insert into `hrm`.`tb_currency`(`tbc_id`,`tbc_currency_id`,`tbc_name`) values (142,'VUV','Vanuatu Vatu');
insert into `hrm`.`tb_currency`(`tbc_id`,`tbc_currency_id`,`tbc_name`) values (143,'WST','Samoan Tala');
insert into `hrm`.`tb_currency`(`tbc_id`,`tbc_currency_id`,`tbc_name`) values (144,'XAF','CFA Franc BEAC');
insert into `hrm`.`tb_currency`(`tbc_id`,`tbc_currency_id`,`tbc_name`) values (145,'XAG','Silver (oz.)');
insert into `hrm`.`tb_currency`(`tbc_id`,`tbc_currency_id`,`tbc_name`) values (146,'XAU','Gold (oz.)');
insert into `hrm`.`tb_currency`(`tbc_id`,`tbc_currency_id`,`tbc_name`) values (147,'XCD','Eastern Caribbean Dollars');
insert into `hrm`.`tb_currency`(`tbc_id`,`tbc_currency_id`,`tbc_name`) values (148,'XDR','IMF Special Drawing Right');
insert into `hrm`.`tb_currency`(`tbc_id`,`tbc_currency_id`,`tbc_name`) values (149,'XOF','CFA Franc BCEAO');
insert into `hrm`.`tb_currency`(`tbc_id`,`tbc_currency_id`,`tbc_name`) values (150,'XPD','Palladium (oz.)');
insert into `hrm`.`tb_currency`(`tbc_id`,`tbc_currency_id`,`tbc_name`) values (151,'XPF','Franc des Comptoirs franÃ§ais du Pacifique');
insert into `hrm`.`tb_currency`(`tbc_id`,`tbc_currency_id`,`tbc_name`) values (152,'XPT','Platinum (oz.)');
insert into `hrm`.`tb_currency`(`tbc_id`,`tbc_currency_id`,`tbc_name`) values (153,'YER','Yemeni Riyal');
insert into `hrm`.`tb_currency`(`tbc_id`,`tbc_currency_id`,`tbc_name`) values (154,'YUM','Yugoslavian Dinar');
insert into `hrm`.`tb_currency`(`tbc_id`,`tbc_currency_id`,`tbc_name`) values (155,'YUN','Yugoslav Dinar');
insert into `hrm`.`tb_currency`(`tbc_id`,`tbc_currency_id`,`tbc_name`) values (156,'ZAR','South African Rand');
insert into `hrm`.`tb_currency`(`tbc_id`,`tbc_currency_id`,`tbc_name`) values (157,'ZMK','Zambian Kwacha');
insert into `hrm`.`tb_currency`(`tbc_id`,`tbc_currency_id`,`tbc_name`) values (158,'ZRN','New Zaire');
insert into `hrm`.`tb_currency`(`tbc_id`,`tbc_currency_id`,`tbc_name`) values (159,'ZWD','Zimbabwe Dollar');
