USE hrm;

CREATE TABLE `tb_negara` (
  `tbn_id` int(11) NOT NULL AUTO_INCREMENT,
  `tbn_nama` varchar(45) DEFAULT NULL,
  PRIMARY KEY (`tbn_id`)
) ENGINE=InnoDB AUTO_INCREMENT=241 DEFAULT CHARSET=latin1;


insert into `tb_negara`(`tbn_id`,`tbn_nama`) values (1,'Afghanistan');
insert into `tb_negara`(`tbn_id`,`tbn_nama`) values (2,'Albania');
insert into `tb_negara`(`tbn_id`,`tbn_nama`) values (3,'Algeria');
insert into `tb_negara`(`tbn_id`,`tbn_nama`) values (4,'American Samoa');
insert into `tb_negara`(`tbn_id`,`tbn_nama`) values (5,'Andorra');
insert into `tb_negara`(`tbn_id`,`tbn_nama`) values (6,'Angola');
insert into `tb_negara`(`tbn_id`,`tbn_nama`) values (7,'Anguilla');
insert into `tb_negara`(`tbn_id`,`tbn_nama`) values (8,'Antarctica');
insert into `tb_negara`(`tbn_id`,`tbn_nama`) values (9,'Antigua and Barbuda');
insert into `tb_negara`(`tbn_id`,`tbn_nama`) values (10,'Argentina');
insert into `tb_negara`(`tbn_id`,`tbn_nama`) values (11,'Armenia');
insert into `tb_negara`(`tbn_id`,`tbn_nama`) values (12,'Aruba');
insert into `tb_negara`(`tbn_id`,`tbn_nama`) values (13,'Australia');
insert into `tb_negara`(`tbn_id`,`tbn_nama`) values (14,'Austria');
insert into `tb_negara`(`tbn_id`,`tbn_nama`) values (15,'Azerbaijan');
insert into `tb_negara`(`tbn_id`,`tbn_nama`) values (16,'Bahamas');
insert into `tb_negara`(`tbn_id`,`tbn_nama`) values (17,'Bahrain');
insert into `tb_negara`(`tbn_id`,`tbn_nama`) values (18,'Bangladesh');
insert into `tb_negara`(`tbn_id`,`tbn_nama`) values (19,'Barbados');
insert into `tb_negara`(`tbn_id`,`tbn_nama`) values (20,'Belarus');
insert into `tb_negara`(`tbn_id`,`tbn_nama`) values (21,'Belgium');
insert into `tb_negara`(`tbn_id`,`tbn_nama`) values (22,'Belize');
insert into `tb_negara`(`tbn_id`,`tbn_nama`) values (23,'Benin');
insert into `tb_negara`(`tbn_id`,`tbn_nama`) values (24,'Bermuda');
insert into `tb_negara`(`tbn_id`,`tbn_nama`) values (25,'Bhutan');
insert into `tb_negara`(`tbn_id`,`tbn_nama`) values (26,'Bolivia');
insert into `tb_negara`(`tbn_id`,`tbn_nama`) values (27,'Bosnia and Herzegowina');
insert into `tb_negara`(`tbn_id`,`tbn_nama`) values (28,'Botswana');
insert into `tb_negara`(`tbn_id`,`tbn_nama`) values (29,'Bouvet Island');
insert into `tb_negara`(`tbn_id`,`tbn_nama`) values (30,'Brazil');
insert into `tb_negara`(`tbn_id`,`tbn_nama`) values (31,'British Indian Ocean Territory');
insert into `tb_negara`(`tbn_id`,`tbn_nama`) values (32,'Brunei Darussalam');
insert into `tb_negara`(`tbn_id`,`tbn_nama`) values (33,'Bulgaria');
insert into `tb_negara`(`tbn_id`,`tbn_nama`) values (34,'Burkina Faso');
insert into `tb_negara`(`tbn_id`,`tbn_nama`) values (35,'Burundi');
insert into `tb_negara`(`tbn_id`,`tbn_nama`) values (36,'Cambodia');
insert into `tb_negara`(`tbn_id`,`tbn_nama`) values (37,'Cameroon');
insert into `tb_negara`(`tbn_id`,`tbn_nama`) values (38,'Canada');
insert into `tb_negara`(`tbn_id`,`tbn_nama`) values (39,'Cape Verde');
insert into `tb_negara`(`tbn_id`,`tbn_nama`) values (40,'Cayman Islands');
insert into `tb_negara`(`tbn_id`,`tbn_nama`) values (41,'Central African Republic');
insert into `tb_negara`(`tbn_id`,`tbn_nama`) values (42,'Chad');
insert into `tb_negara`(`tbn_id`,`tbn_nama`) values (43,'Chile');
insert into `tb_negara`(`tbn_id`,`tbn_nama`) values (44,'China');
insert into `tb_negara`(`tbn_id`,`tbn_nama`) values (45,'Christmas Island');
insert into `tb_negara`(`tbn_id`,`tbn_nama`) values (46,'Cocos (Keeling) Islands');
insert into `tb_negara`(`tbn_id`,`tbn_nama`) values (47,'Colombia');
insert into `tb_negara`(`tbn_id`,`tbn_nama`) values (48,'Comoros');
insert into `tb_negara`(`tbn_id`,`tbn_nama`) values (49,'Congo');
insert into `tb_negara`(`tbn_id`,`tbn_nama`) values (50,'Cook Islands');
insert into `tb_negara`(`tbn_id`,`tbn_nama`) values (51,'Costa Rica');
insert into `tb_negara`(`tbn_id`,`tbn_nama`) values (52,'Cote DIvoire');
insert into `tb_negara`(`tbn_id`,`tbn_nama`) values (53,'Croatia');
insert into `tb_negara`(`tbn_id`,`tbn_nama`) values (54,'Cuba');
insert into `tb_negara`(`tbn_id`,`tbn_nama`) values (55,'Cyprus');
insert into `tb_negara`(`tbn_id`,`tbn_nama`) values (56,'Czech Republic');
insert into `tb_negara`(`tbn_id`,`tbn_nama`) values (57,'Denmark');
insert into `tb_negara`(`tbn_id`,`tbn_nama`) values (58,'Djibouti');
insert into `tb_negara`(`tbn_id`,`tbn_nama`) values (59,'Dominica');
insert into `tb_negara`(`tbn_id`,`tbn_nama`) values (60,'Dominican Republic');
insert into `tb_negara`(`tbn_id`,`tbn_nama`) values (61,'East Timor');
insert into `tb_negara`(`tbn_id`,`tbn_nama`) values (62,'Ecuador');
insert into `tb_negara`(`tbn_id`,`tbn_nama`) values (63,'Egypt');
insert into `tb_negara`(`tbn_id`,`tbn_nama`) values (64,'El Salvador');
insert into `tb_negara`(`tbn_id`,`tbn_nama`) values (65,'Equatorial Guinea');
insert into `tb_negara`(`tbn_id`,`tbn_nama`) values (66,'Eritrea');
insert into `tb_negara`(`tbn_id`,`tbn_nama`) values (67,'Estonia');
insert into `tb_negara`(`tbn_id`,`tbn_nama`) values (68,'Ethiopia');
insert into `tb_negara`(`tbn_id`,`tbn_nama`) values (69,'Falkland Islands (Malvinas)');
insert into `tb_negara`(`tbn_id`,`tbn_nama`) values (70,'Faroe Islands');
insert into `tb_negara`(`tbn_id`,`tbn_nama`) values (71,'Fiji');
insert into `tb_negara`(`tbn_id`,`tbn_nama`) values (72,'Finland');
insert into `tb_negara`(`tbn_id`,`tbn_nama`) values (73,'France');
insert into `tb_negara`(`tbn_id`,`tbn_nama`) values (74,'France, Metropolitan');
insert into `tb_negara`(`tbn_id`,`tbn_nama`) values (75,'French Guiana');
insert into `tb_negara`(`tbn_id`,`tbn_nama`) values (76,'French Polynesia');
insert into `tb_negara`(`tbn_id`,`tbn_nama`) values (77,'French Southern Territories');
insert into `tb_negara`(`tbn_id`,`tbn_nama`) values (78,'Gabon');
insert into `tb_negara`(`tbn_id`,`tbn_nama`) values (79,'Gambia');
insert into `tb_negara`(`tbn_id`,`tbn_nama`) values (80,'Georgia');
insert into `tb_negara`(`tbn_id`,`tbn_nama`) values (81,'Germany');
insert into `tb_negara`(`tbn_id`,`tbn_nama`) values (82,'Ghana');
insert into `tb_negara`(`tbn_id`,`tbn_nama`) values (83,'Gibraltar');
insert into `tb_negara`(`tbn_id`,`tbn_nama`) values (84,'Greece');
insert into `tb_negara`(`tbn_id`,`tbn_nama`) values (85,'Greenland');
insert into `tb_negara`(`tbn_id`,`tbn_nama`) values (86,'Grenada');
insert into `tb_negara`(`tbn_id`,`tbn_nama`) values (87,'Guadeloupe');
insert into `tb_negara`(`tbn_id`,`tbn_nama`) values (88,'Guam');
insert into `tb_negara`(`tbn_id`,`tbn_nama`) values (89,'Guatemala');
insert into `tb_negara`(`tbn_id`,`tbn_nama`) values (90,'Guinea');
insert into `tb_negara`(`tbn_id`,`tbn_nama`) values (91,'Guinea-bissau');
insert into `tb_negara`(`tbn_id`,`tbn_nama`) values (92,'Guyana');
insert into `tb_negara`(`tbn_id`,`tbn_nama`) values (93,'Haiti');
insert into `tb_negara`(`tbn_id`,`tbn_nama`) values (94,'Heard and Mc Donald Islands');
insert into `tb_negara`(`tbn_id`,`tbn_nama`) values (95,'Honduras');
insert into `tb_negara`(`tbn_id`,`tbn_nama`) values (96,'Hong Kong');
insert into `tb_negara`(`tbn_id`,`tbn_nama`) values (97,'Hungary');
insert into `tb_negara`(`tbn_id`,`tbn_nama`) values (98,'Iceland');
insert into `tb_negara`(`tbn_id`,`tbn_nama`) values (99,'India');
insert into `tb_negara`(`tbn_id`,`tbn_nama`) values (100,'Indonesia');
insert into `tb_negara`(`tbn_id`,`tbn_nama`) values (101,'Iran (Islamic Republic of)');
insert into `tb_negara`(`tbn_id`,`tbn_nama`) values (102,'Iraq');
insert into `tb_negara`(`tbn_id`,`tbn_nama`) values (103,'Ireland');
insert into `tb_negara`(`tbn_id`,`tbn_nama`) values (104,'Israel');
insert into `tb_negara`(`tbn_id`,`tbn_nama`) values (105,'Italy');
insert into `tb_negara`(`tbn_id`,`tbn_nama`) values (106,'Jamaica');
insert into `tb_negara`(`tbn_id`,`tbn_nama`) values (107,'Japan');
insert into `tb_negara`(`tbn_id`,`tbn_nama`) values (108,'Jordan');
insert into `tb_negara`(`tbn_id`,`tbn_nama`) values (109,'Kazakhstan');
insert into `tb_negara`(`tbn_id`,`tbn_nama`) values (110,'Kenya');
insert into `tb_negara`(`tbn_id`,`tbn_nama`) values (111,'Kiribati');
insert into `tb_negara`(`tbn_id`,`tbn_nama`) values (112,'Korea, Democratic Peoples Republic of');
insert into `tb_negara`(`tbn_id`,`tbn_nama`) values (113,'Korea, Republic of');
insert into `tb_negara`(`tbn_id`,`tbn_nama`) values (114,'Kuwait');
insert into `tb_negara`(`tbn_id`,`tbn_nama`) values (115,'Kyrgyzstan');
insert into `tb_negara`(`tbn_id`,`tbn_nama`) values (116,'Lao Peoples Democratic Republic');
insert into `tb_negara`(`tbn_id`,`tbn_nama`) values (117,'Latvia');
insert into `tb_negara`(`tbn_id`,`tbn_nama`) values (118,'Lebanon');
insert into `tb_negara`(`tbn_id`,`tbn_nama`) values (119,'Lesotho');
insert into `tb_negara`(`tbn_id`,`tbn_nama`) values (120,'Liberia');
insert into `tb_negara`(`tbn_id`,`tbn_nama`) values (121,'Libyan Arab Jamahiriya');
insert into `tb_negara`(`tbn_id`,`tbn_nama`) values (122,'Liechtenstein');
insert into `tb_negara`(`tbn_id`,`tbn_nama`) values (123,'Lithuania');
insert into `tb_negara`(`tbn_id`,`tbn_nama`) values (124,'Luxembourg');
insert into `tb_negara`(`tbn_id`,`tbn_nama`) values (125,'Macau');
insert into `tb_negara`(`tbn_id`,`tbn_nama`) values (126,'Macedonia, The Former Yugoslav Republic of');
insert into `tb_negara`(`tbn_id`,`tbn_nama`) values (127,'Madagascar');
insert into `tb_negara`(`tbn_id`,`tbn_nama`) values (128,'Malawi');
insert into `tb_negara`(`tbn_id`,`tbn_nama`) values (129,'Malaysia');
insert into `tb_negara`(`tbn_id`,`tbn_nama`) values (130,'Maldives');
insert into `tb_negara`(`tbn_id`,`tbn_nama`) values (131,'Mali');
insert into `tb_negara`(`tbn_id`,`tbn_nama`) values (132,'Malta');
insert into `tb_negara`(`tbn_id`,`tbn_nama`) values (133,'Marshall Islands');
insert into `tb_negara`(`tbn_id`,`tbn_nama`) values (134,'Martinique');
insert into `tb_negara`(`tbn_id`,`tbn_nama`) values (135,'Mauritania');
insert into `tb_negara`(`tbn_id`,`tbn_nama`) values (136,'Mauritius');
insert into `tb_negara`(`tbn_id`,`tbn_nama`) values (137,'Mayotte');
insert into `tb_negara`(`tbn_id`,`tbn_nama`) values (138,'Mexico');
insert into `tb_negara`(`tbn_id`,`tbn_nama`) values (139,'Micronesia, Federated States of');
insert into `tb_negara`(`tbn_id`,`tbn_nama`) values (140,'Moldova, Republic of');
insert into `tb_negara`(`tbn_id`,`tbn_nama`) values (141,'Monaco');
insert into `tb_negara`(`tbn_id`,`tbn_nama`) values (142,'Mongolia');
insert into `tb_negara`(`tbn_id`,`tbn_nama`) values (143,'Montserrat');
insert into `tb_negara`(`tbn_id`,`tbn_nama`) values (144,'Morocco');
insert into `tb_negara`(`tbn_id`,`tbn_nama`) values (145,'Mozambique');
insert into `tb_negara`(`tbn_id`,`tbn_nama`) values (146,'Myanmar');
insert into `tb_negara`(`tbn_id`,`tbn_nama`) values (147,'Namibia');
insert into `tb_negara`(`tbn_id`,`tbn_nama`) values (148,'Nauru');
insert into `tb_negara`(`tbn_id`,`tbn_nama`) values (149,'Nepal');
insert into `tb_negara`(`tbn_id`,`tbn_nama`) values (150,'Netherlands');
insert into `tb_negara`(`tbn_id`,`tbn_nama`) values (151,'Netherlands Antilles');
insert into `tb_negara`(`tbn_id`,`tbn_nama`) values (152,'New Caledonia');
insert into `tb_negara`(`tbn_id`,`tbn_nama`) values (153,'New Zealand');
insert into `tb_negara`(`tbn_id`,`tbn_nama`) values (154,'Nicaragua');
insert into `tb_negara`(`tbn_id`,`tbn_nama`) values (155,'Niger');
insert into `tb_negara`(`tbn_id`,`tbn_nama`) values (156,'Nigeria');
insert into `tb_negara`(`tbn_id`,`tbn_nama`) values (157,'Niue');
insert into `tb_negara`(`tbn_id`,`tbn_nama`) values (158,'Norfolk Island');
insert into `tb_negara`(`tbn_id`,`tbn_nama`) values (159,'Northern Mariana Islands');
insert into `tb_negara`(`tbn_id`,`tbn_nama`) values (160,'Norway');
insert into `tb_negara`(`tbn_id`,`tbn_nama`) values (161,'Oman');
insert into `tb_negara`(`tbn_id`,`tbn_nama`) values (162,'Pakistan');
insert into `tb_negara`(`tbn_id`,`tbn_nama`) values (163,'Palau');
insert into `tb_negara`(`tbn_id`,`tbn_nama`) values (164,'Palestine');
insert into `tb_negara`(`tbn_id`,`tbn_nama`) values (165,'Panama');
insert into `tb_negara`(`tbn_id`,`tbn_nama`) values (166,'Papua New Guinea');
insert into `tb_negara`(`tbn_id`,`tbn_nama`) values (167,'Paraguay');
insert into `tb_negara`(`tbn_id`,`tbn_nama`) values (168,'Peru');
insert into `tb_negara`(`tbn_id`,`tbn_nama`) values (169,'Philippines');
insert into `tb_negara`(`tbn_id`,`tbn_nama`) values (170,'Pitcairn');
insert into `tb_negara`(`tbn_id`,`tbn_nama`) values (171,'Poland');
insert into `tb_negara`(`tbn_id`,`tbn_nama`) values (172,'Portugal');
insert into `tb_negara`(`tbn_id`,`tbn_nama`) values (173,'Puerto Rico');
insert into `tb_negara`(`tbn_id`,`tbn_nama`) values (174,'Qatar');
insert into `tb_negara`(`tbn_id`,`tbn_nama`) values (175,'Reunion');
insert into `tb_negara`(`tbn_id`,`tbn_nama`) values (176,'Romania');
insert into `tb_negara`(`tbn_id`,`tbn_nama`) values (177,'Russian Federation');
insert into `tb_negara`(`tbn_id`,`tbn_nama`) values (178,'Rwanda');
insert into `tb_negara`(`tbn_id`,`tbn_nama`) values (179,'Saint Kitts and Nevis');
insert into `tb_negara`(`tbn_id`,`tbn_nama`) values (180,'Saint Lucia');
insert into `tb_negara`(`tbn_id`,`tbn_nama`) values (181,'Saint Vincent and the Grenadines');
insert into `tb_negara`(`tbn_id`,`tbn_nama`) values (182,'Samoa');
insert into `tb_negara`(`tbn_id`,`tbn_nama`) values (183,'San Marino');
insert into `tb_negara`(`tbn_id`,`tbn_nama`) values (184,'Sao Tome and Principe');
insert into `tb_negara`(`tbn_id`,`tbn_nama`) values (185,'Saudi Arabia');
insert into `tb_negara`(`tbn_id`,`tbn_nama`) values (186,'Senegal');
insert into `tb_negara`(`tbn_id`,`tbn_nama`) values (187,'Seychelles');
insert into `tb_negara`(`tbn_id`,`tbn_nama`) values (188,'Sierra Leone');
insert into `tb_negara`(`tbn_id`,`tbn_nama`) values (189,'Singapore');
insert into `tb_negara`(`tbn_id`,`tbn_nama`) values (190,'Slovakia (Slovak Republic)');
insert into `tb_negara`(`tbn_id`,`tbn_nama`) values (191,'Slovenia');
insert into `tb_negara`(`tbn_id`,`tbn_nama`) values (192,'Solomon Islands');
insert into `tb_negara`(`tbn_id`,`tbn_nama`) values (193,'Somalia');
insert into `tb_negara`(`tbn_id`,`tbn_nama`) values (194,'South Africa');
insert into `tb_negara`(`tbn_id`,`tbn_nama`) values (195,'South Georgia and the South Sandwich Islands');
insert into `tb_negara`(`tbn_id`,`tbn_nama`) values (196,'Spain');
insert into `tb_negara`(`tbn_id`,`tbn_nama`) values (197,'Sri Lanka');
insert into `tb_negara`(`tbn_id`,`tbn_nama`) values (198,'St. Helena');
insert into `tb_negara`(`tbn_id`,`tbn_nama`) values (199,'St. Pierre and Miquelon');
insert into `tb_negara`(`tbn_id`,`tbn_nama`) values (200,'Sudan');
insert into `tb_negara`(`tbn_id`,`tbn_nama`) values (201,'Suriname');
insert into `tb_negara`(`tbn_id`,`tbn_nama`) values (202,'Svalbard and Jan Mayen Islands');
insert into `tb_negara`(`tbn_id`,`tbn_nama`) values (203,'Swaziland');
insert into `tb_negara`(`tbn_id`,`tbn_nama`) values (204,'Sweden');
insert into `tb_negara`(`tbn_id`,`tbn_nama`) values (205,'Switzerland');
insert into `tb_negara`(`tbn_id`,`tbn_nama`) values (206,'Syrian Arab Republic');
insert into `tb_negara`(`tbn_id`,`tbn_nama`) values (207,'Taiwan');
insert into `tb_negara`(`tbn_id`,`tbn_nama`) values (208,'Tajikistan');
insert into `tb_negara`(`tbn_id`,`tbn_nama`) values (209,'Tanzania, United Republic of');
insert into `tb_negara`(`tbn_id`,`tbn_nama`) values (210,'Thailand');
insert into `tb_negara`(`tbn_id`,`tbn_nama`) values (211,'Togo');
insert into `tb_negara`(`tbn_id`,`tbn_nama`) values (212,'Tokelau');
insert into `tb_negara`(`tbn_id`,`tbn_nama`) values (213,'Tonga');
insert into `tb_negara`(`tbn_id`,`tbn_nama`) values (214,'Trinidad and Tobago');
insert into `tb_negara`(`tbn_id`,`tbn_nama`) values (215,'Tunisia');
insert into `tb_negara`(`tbn_id`,`tbn_nama`) values (216,'Turkey');
insert into `tb_negara`(`tbn_id`,`tbn_nama`) values (217,'Turkmenistan');
insert into `tb_negara`(`tbn_id`,`tbn_nama`) values (218,'Turks and Caicos Islands');
insert into `tb_negara`(`tbn_id`,`tbn_nama`) values (219,'Tuvalu');
insert into `tb_negara`(`tbn_id`,`tbn_nama`) values (220,'Uganda');
insert into `tb_negara`(`tbn_id`,`tbn_nama`) values (221,'Ukraine');
insert into `tb_negara`(`tbn_id`,`tbn_nama`) values (222,'United Arab Emirates');
insert into `tb_negara`(`tbn_id`,`tbn_nama`) values (223,'United Kingdom');
insert into `tb_negara`(`tbn_id`,`tbn_nama`) values (224,'United States');
insert into `tb_negara`(`tbn_id`,`tbn_nama`) values (225,'United States Minor Outlying Islands');
insert into `tb_negara`(`tbn_id`,`tbn_nama`) values (226,'Uruguay');
insert into `tb_negara`(`tbn_id`,`tbn_nama`) values (227,'Uzbekistan');
insert into `tb_negara`(`tbn_id`,`tbn_nama`) values (228,'Vanuatu');
insert into `tb_negara`(`tbn_id`,`tbn_nama`) values (229,'Vatican City State (Holy See)');
insert into `tb_negara`(`tbn_id`,`tbn_nama`) values (230,'Venezuela');
insert into `tb_negara`(`tbn_id`,`tbn_nama`) values (231,'Viet Nam');
insert into `tb_negara`(`tbn_id`,`tbn_nama`) values (232,'Virgin Islands (British)');
insert into `tb_negara`(`tbn_id`,`tbn_nama`) values (233,'Virgin Islands (U.S.)');
insert into `tb_negara`(`tbn_id`,`tbn_nama`) values (234,'Wallis and Futuna Islands');
insert into `tb_negara`(`tbn_id`,`tbn_nama`) values (235,'Western Sahara');
insert into `tb_negara`(`tbn_id`,`tbn_nama`) values (236,'Yemen');
insert into `tb_negara`(`tbn_id`,`tbn_nama`) values (237,'Yugoslavia');
insert into `tb_negara`(`tbn_id`,`tbn_nama`) values (238,'Zaire');
insert into `tb_negara`(`tbn_id`,`tbn_nama`) values (239,'Zambia');
insert into `tb_negara`(`tbn_id`,`tbn_nama`) values (240,'Zimbabwe');
