USE hrm;

utf8_general_ci;


insert into `hrm`.`view_timesheet_project`(`tbe_id`,`tbe_name`,`tbc_id`,`tbc_name`,`tbc_customer_id`,`tbp_id`,`tbp_project_id`,`tbp_name`,`tbpag_id`,`tbpag_project_activities_group_id`,`tbpag_name`,`tbpa_id`,`tbpa_name`,`tbt_start_of_week`,`sum_tbt_total_hour`) values (2,'Nurul Ana',1,'PT. Sampoerna Telekomunikasi Indonesia','CUS1',7,'PRJ7','Implementasi SAP All Division',16,'PAG16','Sales',23,'Sales Proposal','2012-04-02 00:00:00',12);
insert into `hrm`.`view_timesheet_project`(`tbe_id`,`tbe_name`,`tbc_id`,`tbc_name`,`tbc_customer_id`,`tbp_id`,`tbp_project_id`,`tbp_name`,`tbpag_id`,`tbpag_project_activities_group_id`,`tbpag_name`,`tbpa_id`,`tbpa_name`,`tbt_start_of_week`,`sum_tbt_total_hour`) values (2,'Nurul Ana',1,'PT. Sampoerna Telekomunikasi Indonesia','CUS1',7,'PRJ7','Implementasi SAP All Division',16,'PAG16','Sales',23,'Sales Proposal','2012-04-02 16:17:28',1);
insert into `hrm`.`view_timesheet_project`(`tbe_id`,`tbe_name`,`tbc_id`,`tbc_name`,`tbc_customer_id`,`tbp_id`,`tbp_project_id`,`tbp_name`,`tbpag_id`,`tbpag_project_activities_group_id`,`tbpag_name`,`tbpa_id`,`tbpa_name`,`tbt_start_of_week`,`sum_tbt_total_hour`) values (2,'Nurul Ana',1,'PT. Sampoerna Telekomunikasi Indonesia','CUS1',7,'PRJ7','Implementasi SAP All Division',16,'PAG16','Sales',23,'Sales Proposal','2012-04-02 16:17:39',1);
insert into `hrm`.`view_timesheet_project`(`tbe_id`,`tbe_name`,`tbc_id`,`tbc_name`,`tbc_customer_id`,`tbp_id`,`tbp_project_id`,`tbp_name`,`tbpag_id`,`tbpag_project_activities_group_id`,`tbpag_name`,`tbpa_id`,`tbpa_name`,`tbt_start_of_week`,`sum_tbt_total_hour`) values (2,'Nurul Ana',1,'PT. Sampoerna Telekomunikasi Indonesia','CUS1',7,'PRJ7','Implementasi SAP All Division',16,'PAG16','Sales',23,'Sales Proposal','2012-04-02 16:17:48',1);
insert into `hrm`.`view_timesheet_project`(`tbe_id`,`tbe_name`,`tbc_id`,`tbc_name`,`tbc_customer_id`,`tbp_id`,`tbp_project_id`,`tbp_name`,`tbpag_id`,`tbpag_project_activities_group_id`,`tbpag_name`,`tbpa_id`,`tbpa_name`,`tbt_start_of_week`,`sum_tbt_total_hour`) values (2,'Nurul Ana',1,'PT. Sampoerna Telekomunikasi Indonesia','CUS1',7,'PRJ7','Implementasi SAP All Division',18,'PAG18','Development',29,'Analyze','2012-04-16 16:10:12',8);
insert into `hrm`.`view_timesheet_project`(`tbe_id`,`tbe_name`,`tbc_id`,`tbc_name`,`tbc_customer_id`,`tbp_id`,`tbp_project_id`,`tbp_name`,`tbpag_id`,`tbpag_project_activities_group_id`,`tbpag_name`,`tbpa_id`,`tbpa_name`,`tbt_start_of_week`,`sum_tbt_total_hour`) values (2,'Nurul Ana',1,'PT. Sampoerna Telekomunikasi Indonesia','CUS1',7,'PRJ7','Implementasi SAP All Division',16,'PAG16','Sales',23,'Sales Proposal','2012-04-16 16:10:33',32);
insert into `hrm`.`view_timesheet_project`(`tbe_id`,`tbe_name`,`tbc_id`,`tbc_name`,`tbc_customer_id`,`tbp_id`,`tbp_project_id`,`tbp_name`,`tbpag_id`,`tbpag_project_activities_group_id`,`tbpag_name`,`tbpa_id`,`tbpa_name`,`tbt_start_of_week`,`sum_tbt_total_hour`) values (2,'Nurul Ana',1,'PT. Sampoerna Telekomunikasi Indonesia','CUS1',7,'PRJ7','Implementasi SAP All Division',16,'PAG16','Sales',23,'Sales Proposal','2012-05-28 11:41:06',8);
insert into `hrm`.`view_timesheet_project`(`tbe_id`,`tbe_name`,`tbc_id`,`tbc_name`,`tbc_customer_id`,`tbp_id`,`tbp_project_id`,`tbp_name`,`tbpag_id`,`tbpag_project_activities_group_id`,`tbpag_name`,`tbpa_id`,`tbpa_name`,`tbt_start_of_week`,`sum_tbt_total_hour`) values (2,'Nurul Ana',1,'PT. Sampoerna Telekomunikasi Indonesia','CUS1',7,'PRJ7','Implementasi SAP All Division',19,'PAG19','Vacation',32,'Annual Leave','2012-05-28 11:41:25',40);
insert into `hrm`.`view_timesheet_project`(`tbe_id`,`tbe_name`,`tbc_id`,`tbc_name`,`tbc_customer_id`,`tbp_id`,`tbp_project_id`,`tbp_name`,`tbpag_id`,`tbpag_project_activities_group_id`,`tbpag_name`,`tbpa_id`,`tbpa_name`,`tbt_start_of_week`,`sum_tbt_total_hour`) values (2,'Nurul Ana',1,'PT. Sampoerna Telekomunikasi Indonesia','CUS1',7,'PRJ7','Implementasi SAP All Division',16,'PAG16','Sales',23,'Sales Proposal','2012-06-11 14:28:40',15);
insert into `hrm`.`view_timesheet_project`(`tbe_id`,`tbe_name`,`tbc_id`,`tbc_name`,`tbc_customer_id`,`tbp_id`,`tbp_project_id`,`tbp_name`,`tbpag_id`,`tbpag_project_activities_group_id`,`tbpag_name`,`tbpa_id`,`tbpa_name`,`tbt_start_of_week`,`sum_tbt_total_hour`) values (1,'Achmad Amri',6,'PT. Kliring Penjaminan Efek Indonesia','CUS6',8,'PRJ8','Middleware Implementation',18,'PAG18','Development',29,'Analyze','2012-07-02 00:10:04',32);
insert into `hrm`.`view_timesheet_project`(`tbe_id`,`tbe_name`,`tbc_id`,`tbc_name`,`tbc_customer_id`,`tbp_id`,`tbp_project_id`,`tbp_name`,`tbpag_id`,`tbpag_project_activities_group_id`,`tbpag_name`,`tbpa_id`,`tbpa_name`,`tbt_start_of_week`,`sum_tbt_total_hour`) values (1,'Achmad Amri',6,'PT. Kliring Penjaminan Efek Indonesia','CUS6',8,'PRJ8','Middleware Implementation',16,'PAG16','Sales',25,'Letter Of Intent','2012-07-02 00:10:25',8);
insert into `hrm`.`view_timesheet_project`(`tbe_id`,`tbe_name`,`tbc_id`,`tbc_name`,`tbc_customer_id`,`tbp_id`,`tbp_project_id`,`tbp_name`,`tbpag_id`,`tbpag_project_activities_group_id`,`tbpag_name`,`tbpa_id`,`tbpa_name`,`tbt_start_of_week`,`sum_tbt_total_hour`) values (1,'Achmad Amri',1,'PT. Sampoerna Telekomunikasi Indonesia','CUS1',7,'PRJ7','Implementasi SAP All Division',16,'PAG16','Sales',23,'Sales Proposal','2012-07-02 06:49:52',40);
insert into `hrm`.`view_timesheet_project`(`tbe_id`,`tbe_name`,`tbc_id`,`tbc_name`,`tbc_customer_id`,`tbp_id`,`tbp_project_id`,`tbp_name`,`tbpag_id`,`tbpag_project_activities_group_id`,`tbpag_name`,`tbpa_id`,`tbpa_name`,`tbt_start_of_week`,`sum_tbt_total_hour`) values (2,'Nurul Ana',1,'PT. Sampoerna Telekomunikasi Indonesia','CUS1',7,'PRJ7','Implementasi SAP All Division',16,'PAG16','Sales',23,'Sales Proposal','2012-07-02 06:50:23',40);
insert into `hrm`.`view_timesheet_project`(`tbe_id`,`tbe_name`,`tbc_id`,`tbc_name`,`tbc_customer_id`,`tbp_id`,`tbp_project_id`,`tbp_name`,`tbpag_id`,`tbpag_project_activities_group_id`,`tbpag_name`,`tbpa_id`,`tbpa_name`,`tbt_start_of_week`,`sum_tbt_total_hour`) values (2,'Nurul Ana',1,'PT. Sampoerna Telekomunikasi Indonesia','CUS1',7,'PRJ7','Implementasi SAP All Division',16,'PAG16','Sales',23,'Sales Proposal','2012-07-02 07:24:14',40);
insert into `hrm`.`view_timesheet_project`(`tbe_id`,`tbe_name`,`tbc_id`,`tbc_name`,`tbc_customer_id`,`tbp_id`,`tbp_project_id`,`tbp_name`,`tbpag_id`,`tbpag_project_activities_group_id`,`tbpag_name`,`tbpa_id`,`tbpa_name`,`tbt_start_of_week`,`sum_tbt_total_hour`) values (1,'Achmad Amri',1,'PT. Sampoerna Telekomunikasi Indonesia','CUS1',7,'PRJ7','Implementasi SAP All Division',16,'PAG16','Sales',23,'Sales Proposal','2012-07-16 22:36:56',40);
