USE hrm;

utf8_general_ci;


insert into `hrm`.`view_employee_information`(`tbe_id`,`tbe_employee_id`,`tbe_first_name`,`tbe_middle_name`,`tbe_last_name`,`tbe_nick_name`,`tbe_name`,`tbe_photo_file_name`,`tbe_id_no`,`tbe_dob`,`tbe_marital_status`,`tbe_smoker`,`tbe_gender`,`tbe_driver_license_no`,`tbe_driver_license_expiry`,`tbj_joined_date`,`tbjt_id`,`tbjt_job_title_id`,`tbjt_name`,`tbjt_description`,`tbjt_comments`,`tbjs_id`,`tbp_id`,`tbes_id`,`tbes_employment_status_id`,`tbes_name`,`tbo_id`,`tbo_parent_id`,`tbo_nama`) values (6,'EMP12030006','abc','','def','','abc def',null,'',null,null,null,null,'',null,'2012-06-29 15:16:51',241,'JOB001','Job Direktur','Job Direktur Description','Job Direktur Comments',1,1,242,'EST002','Contract',16,0,'IT Division');
insert into `hrm`.`view_employee_information`(`tbe_id`,`tbe_employee_id`,`tbe_first_name`,`tbe_middle_name`,`tbe_last_name`,`tbe_nick_name`,`tbe_name`,`tbe_photo_file_name`,`tbe_id_no`,`tbe_dob`,`tbe_marital_status`,`tbe_smoker`,`tbe_gender`,`tbe_driver_license_no`,`tbe_driver_license_expiry`,`tbj_joined_date`,`tbjt_id`,`tbjt_job_title_id`,`tbjt_name`,`tbjt_description`,`tbjt_comments`,`tbjs_id`,`tbp_id`,`tbes_id`,`tbes_employment_status_id`,`tbes_name`,`tbo_id`,`tbo_parent_id`,`tbo_nama`) values (1,'EMP12010001','Achmad','','Amri','Aan','Achmad Amri','k3uzw7x3vju2mjn08d58dgdm0.jpg
','','1981-08-19 00:00:00',0,1,0,'',null,'2012-07-06 13:37:45',241,'JOB001','Job Direktur','Job Direktur Description','Job Direktur Comments',1,1,241,'EST001','Permanent',16,0,'IT Division');
insert into `hrm`.`view_employee_information`(`tbe_id`,`tbe_employee_id`,`tbe_first_name`,`tbe_middle_name`,`tbe_last_name`,`tbe_nick_name`,`tbe_name`,`tbe_photo_file_name`,`tbe_id_no`,`tbe_dob`,`tbe_marital_status`,`tbe_smoker`,`tbe_gender`,`tbe_driver_license_no`,`tbe_driver_license_expiry`,`tbj_joined_date`,`tbjt_id`,`tbjt_job_title_id`,`tbjt_name`,`tbjt_description`,`tbjt_comments`,`tbjs_id`,`tbp_id`,`tbes_id`,`tbes_employment_status_id`,`tbes_name`,`tbo_id`,`tbo_parent_id`,`tbo_nama`) values (7,'EMP12070007','ghi','','jkl','','ghi jkl',null,'',null,null,null,null,'',null,'2012-01-01 17:25:46',242,'JOB242','Job Manager','Job Manager Description','Job Manager Comments',2,11,241,'EST001','Permanent',16,0,'IT Division');
insert into `hrm`.`view_employee_information`(`tbe_id`,`tbe_employee_id`,`tbe_first_name`,`tbe_middle_name`,`tbe_last_name`,`tbe_nick_name`,`tbe_name`,`tbe_photo_file_name`,`tbe_id_no`,`tbe_dob`,`tbe_marital_status`,`tbe_smoker`,`tbe_gender`,`tbe_driver_license_no`,`tbe_driver_license_expiry`,`tbj_joined_date`,`tbjt_id`,`tbjt_job_title_id`,`tbjt_name`,`tbjt_description`,`tbjt_comments`,`tbjs_id`,`tbp_id`,`tbes_id`,`tbes_employment_status_id`,`tbes_name`,`tbo_id`,`tbo_parent_id`,`tbo_nama`) values (5,'EMP12010005','Miykaal','','Abrar','','Miykaal Abrar','tqkmyh4nw9jueuxw4hgqs7ofs.jpg
','','2008-10-29 00:00:00',1,1,0,'',null,'2012-06-26 12:31:35',242,'JOB242','Job Manager','Job Manager Description','Job Manager Comments',2,11,241,'EST001','Permanent',20,19,'Sales 1 Team');
insert into `hrm`.`view_employee_information`(`tbe_id`,`tbe_employee_id`,`tbe_first_name`,`tbe_middle_name`,`tbe_last_name`,`tbe_nick_name`,`tbe_name`,`tbe_photo_file_name`,`tbe_id_no`,`tbe_dob`,`tbe_marital_status`,`tbe_smoker`,`tbe_gender`,`tbe_driver_license_no`,`tbe_driver_license_expiry`,`tbj_joined_date`,`tbjt_id`,`tbjt_job_title_id`,`tbjt_name`,`tbjt_description`,`tbjt_comments`,`tbjs_id`,`tbp_id`,`tbes_id`,`tbes_employment_status_id`,`tbes_name`,`tbo_id`,`tbo_parent_id`,`tbo_nama`) values (2,'EMP12010002','Nurul','','Ana','Ana','Nurul Ana','r5xbcpzsrnvuxsm9y80iyt00i.jpg
','',null,0,1,1,'',null,'2012-07-06 13:42:33',241,'JOB001','Job Direktur','Job Direktur Description','Job Direktur Comments',1,1,241,'EST001','Permanent',19,0,'Marketing Division');
insert into `hrm`.`view_employee_information`(`tbe_id`,`tbe_employee_id`,`tbe_first_name`,`tbe_middle_name`,`tbe_last_name`,`tbe_nick_name`,`tbe_name`,`tbe_photo_file_name`,`tbe_id_no`,`tbe_dob`,`tbe_marital_status`,`tbe_smoker`,`tbe_gender`,`tbe_driver_license_no`,`tbe_driver_license_expiry`,`tbj_joined_date`,`tbjt_id`,`tbjt_job_title_id`,`tbjt_name`,`tbjt_description`,`tbjt_comments`,`tbjs_id`,`tbp_id`,`tbes_id`,`tbes_employment_status_id`,`tbes_name`,`tbo_id`,`tbo_parent_id`,`tbo_nama`) values (8,'EMP12010008','user1','user','satu','','user1 satu',null,'',null,null,null,null,'',null,'2012-01-01 23:23:58',242,'JOB242','Job Manager','Job Manager Description','Job Manager Comments',2,11,241,'EST001','Permanent',16,0,'IT Division');
