USE hrm;

utf8_general_ci;


insert into `view_kpi_assign`(`tbe_id`,`tbe_name`,`tbkg_id`,`tbkg_kpi_group_id`,`tbkg_name`,`tbk_id`,`tbk_description`,`tbk_target_nilai_1`,`tbk_target_nilai_2`,`tbk_target_nilai_3`,`tbk_target_nilai_4`,`tbk_target_nilai_5`,`tbk_bobot`,`tbka_id`,`tbka_evaluasi`,`tbka_action`,`tbka_poin`,`tbka_status`) values (5,'m m',3,'KPG3','Implementation',4,'Penyelesaian projek sesuai dengan alokasi mandays berdasarkan Project Assignment Letter','Rata-rata projek diselesaikan melebihi 130% dari alokasi mandays yang telah ditetapkan','Rata-rata projek diselesaikan dalam batas sampai 130% dari alokasi mandays yang telah ditetapkan ','Rata-rata projek diselesaikan sampai batas  120% dari alokasi mandays yang telah ditetapkan ','Rata-rata projek diselesaikan dalam batas 100% dari alokasi mandays yang telah ditetapkan ','Rata-rata projek diselesaikan dalam batas kurang dari 100% dari alokasi mandays ',25,2,'lorem ipsum dolor sit amet lorem ipsum dolor sit amet lorem ipsum dolor sit amet','amet sit dolor ipsum lorem amet sit dolor ipsum lorem amet sit dolor ipsum lorem',5,4);
insert into `view_kpi_assign`(`tbe_id`,`tbe_name`,`tbkg_id`,`tbkg_kpi_group_id`,`tbkg_name`,`tbk_id`,`tbk_description`,`tbk_target_nilai_1`,`tbk_target_nilai_2`,`tbk_target_nilai_3`,`tbk_target_nilai_4`,`tbk_target_nilai_5`,`tbk_bobot`,`tbka_id`,`tbka_evaluasi`,`tbka_action`,`tbka_poin`,`tbka_status`) values (6,'abc def',3,'KPG3','Implementation',4,'Penyelesaian projek sesuai dengan alokasi mandays berdasarkan Project Assignment Letter','Rata-rata projek diselesaikan melebihi 130% dari alokasi mandays yang telah ditetapkan','Rata-rata projek diselesaikan dalam batas sampai 130% dari alokasi mandays yang telah ditetapkan ','Rata-rata projek diselesaikan sampai batas  120% dari alokasi mandays yang telah ditetapkan ','Rata-rata projek diselesaikan dalam batas 100% dari alokasi mandays yang telah ditetapkan ','Rata-rata projek diselesaikan dalam batas kurang dari 100% dari alokasi mandays ',25,10,null,null,null,1);
insert into `view_kpi_assign`(`tbe_id`,`tbe_name`,`tbkg_id`,`tbkg_kpi_group_id`,`tbkg_name`,`tbk_id`,`tbk_description`,`tbk_target_nilai_1`,`tbk_target_nilai_2`,`tbk_target_nilai_3`,`tbk_target_nilai_4`,`tbk_target_nilai_5`,`tbk_bobot`,`tbka_id`,`tbka_evaluasi`,`tbka_action`,`tbka_poin`,`tbka_status`) values (5,'m m',3,'KPG3','Implementation',9,'Qualitas / Metodologi Pekerjaan yang dihasilkan termasuk Dokumentasi','Tidak ada metodologi yang diterapkan','Tidak konsisten dalam menerapkan metodologi','Konsisten mengikuti Metodologi Pekerjaan dibuktikan melalui pembuatan dokumentasi yang memenuhi standar','Syarat sebelumnya ditambah semua dokumentasi diupload ke Intranet','Membuat standar kerangka untuk dokumentasi pekerjaan',15,3,'qweqwe qweqw qweq wqeqwe qweqw qeqweqw qwe','asdas asda asda  asdasd asdas dasdasd asdadas asdasdasdas asdasdas',2,4);
insert into `view_kpi_assign`(`tbe_id`,`tbe_name`,`tbkg_id`,`tbkg_kpi_group_id`,`tbkg_name`,`tbk_id`,`tbk_description`,`tbk_target_nilai_1`,`tbk_target_nilai_2`,`tbk_target_nilai_3`,`tbk_target_nilai_4`,`tbk_target_nilai_5`,`tbk_bobot`,`tbka_id`,`tbka_evaluasi`,`tbka_action`,`tbka_poin`,`tbka_status`) values (6,'abc def',3,'KPG3','Implementation',9,'Qualitas / Metodologi Pekerjaan yang dihasilkan termasuk Dokumentasi','Tidak ada metodologi yang diterapkan','Tidak konsisten dalam menerapkan metodologi','Konsisten mengikuti Metodologi Pekerjaan dibuktikan melalui pembuatan dokumentasi yang memenuhi standar','Syarat sebelumnya ditambah semua dokumentasi diupload ke Intranet','Membuat standar kerangka untuk dokumentasi pekerjaan',15,11,null,null,null,1);
insert into `view_kpi_assign`(`tbe_id`,`tbe_name`,`tbkg_id`,`tbkg_kpi_group_id`,`tbkg_name`,`tbk_id`,`tbk_description`,`tbk_target_nilai_1`,`tbk_target_nilai_2`,`tbk_target_nilai_3`,`tbk_target_nilai_4`,`tbk_target_nilai_5`,`tbk_bobot`,`tbka_id`,`tbka_evaluasi`,`tbka_action`,`tbka_poin`,`tbka_status`) values (5,'m m',3,'KPG3','Implementation',10,'Customer Satisfaction','Complain Resmi tertulis atau Feedback dari customer rata-rata 1','Ada complain atau Feedback dari customer rata-rata 2','No Complain atau Feedback dari customer minimum 3','Feedback rata-rata dari customer >=3.5','Ada Written Complement Letter dari Customer',10,4,'1','1',1,4);
insert into `view_kpi_assign`(`tbe_id`,`tbe_name`,`tbkg_id`,`tbkg_kpi_group_id`,`tbkg_name`,`tbk_id`,`tbk_description`,`tbk_target_nilai_1`,`tbk_target_nilai_2`,`tbk_target_nilai_3`,`tbk_target_nilai_4`,`tbk_target_nilai_5`,`tbk_bobot`,`tbka_id`,`tbka_evaluasi`,`tbka_action`,`tbka_poin`,`tbka_status`) values (6,'abc def',3,'KPG3','Implementation',10,'Customer Satisfaction','Complain Resmi tertulis atau Feedback dari customer rata-rata 1','Ada complain atau Feedback dari customer rata-rata 2','No Complain atau Feedback dari customer minimum 3','Feedback rata-rata dari customer >=3.5','Ada Written Complement Letter dari Customer',10,12,null,null,null,1);
insert into `view_kpi_assign`(`tbe_id`,`tbe_name`,`tbkg_id`,`tbkg_kpi_group_id`,`tbkg_name`,`tbk_id`,`tbk_description`,`tbk_target_nilai_1`,`tbk_target_nilai_2`,`tbk_target_nilai_3`,`tbk_target_nilai_4`,`tbk_target_nilai_5`,`tbk_bobot`,`tbka_id`,`tbka_evaluasi`,`tbka_action`,`tbka_poin`,`tbka_status`) values (5,'m m',4,'KPG4','Pre Sales',12,'Melakukan: (1) Identifikasi Kebutuhan Pelanggan; (2) Architecting Solution; (3) Presentation; (4) Proposal Preparation; (5) POC/Demo; (6) Handover to Delivery (7) Project Closing Review.  Pengukuran berdasarkan feedback form untuk setiap opportunity baik ','Feedback rata-rata dari tim Sales atau tim Delivery adalah < 2','Feedback rata-rata dari tim Sales atau tim Delivery adalah <3','Feedback rata-rata atas aktifitas yang sudah dilakukan dari tim sales dan tim delivery adalah => 3 dan <4','Feedback rata-rata atas aktifitas yang sudah dilakukan dari tim sales dan tim delivery adalah >=4','Feedback 4 + compliment letter dari DM Sales',10,8,'10','10',10,3);
insert into `view_kpi_assign`(`tbe_id`,`tbe_name`,`tbkg_id`,`tbkg_kpi_group_id`,`tbkg_name`,`tbk_id`,`tbk_description`,`tbk_target_nilai_1`,`tbk_target_nilai_2`,`tbk_target_nilai_3`,`tbk_target_nilai_4`,`tbk_target_nilai_5`,`tbk_bobot`,`tbka_id`,`tbka_evaluasi`,`tbka_action`,`tbka_poin`,`tbka_status`) values (6,'abc def',4,'KPG4','Pre Sales',12,'Melakukan: (1) Identifikasi Kebutuhan Pelanggan; (2) Architecting Solution; (3) Presentation; (4) Proposal Preparation; (5) POC/Demo; (6) Handover to Delivery (7) Project Closing Review.  Pengukuran berdasarkan feedback form untuk setiap opportunity baik ','Feedback rata-rata dari tim Sales atau tim Delivery adalah < 2','Feedback rata-rata dari tim Sales atau tim Delivery adalah <3','Feedback rata-rata atas aktifitas yang sudah dilakukan dari tim sales dan tim delivery adalah => 3 dan <4','Feedback rata-rata atas aktifitas yang sudah dilakukan dari tim sales dan tim delivery adalah >=4','Feedback 4 + compliment letter dari DM Sales',10,16,null,null,null,1);
insert into `view_kpi_assign`(`tbe_id`,`tbe_name`,`tbkg_id`,`tbkg_kpi_group_id`,`tbkg_name`,`tbk_id`,`tbk_description`,`tbk_target_nilai_1`,`tbk_target_nilai_2`,`tbk_target_nilai_3`,`tbk_target_nilai_4`,`tbk_target_nilai_5`,`tbk_bobot`,`tbka_id`,`tbka_evaluasi`,`tbka_action`,`tbka_poin`,`tbka_status`) values (5,'m m',5,'KPG5','Personal Development',13,'Soft-Skill
- Problem solving
','','','- mencari alternatif jawaban
- mencari hal-hal baru
- mendaya gunakan berbagai resource','* point sebelumnya +
- mencipta cara baru yg lebih baik
- menimbang pros dan cons dari alternatif','* point sebelumnya +
- menjadi tempat bertanya tim
- membuat dan merumuskan konsep"',10,5,null,null,null,1);
insert into `view_kpi_assign`(`tbe_id`,`tbe_name`,`tbkg_id`,`tbkg_kpi_group_id`,`tbkg_name`,`tbk_id`,`tbk_description`,`tbk_target_nilai_1`,`tbk_target_nilai_2`,`tbk_target_nilai_3`,`tbk_target_nilai_4`,`tbk_target_nilai_5`,`tbk_bobot`,`tbka_id`,`tbka_evaluasi`,`tbka_action`,`tbka_poin`,`tbka_status`) values (6,'abc def',5,'KPG5','Personal Development',13,'Soft-Skill
- Problem solving
','','','- mencari alternatif jawaban
- mencari hal-hal baru
- mendaya gunakan berbagai resource','* point sebelumnya +
- mencipta cara baru yg lebih baik
- menimbang pros dan cons dari alternatif','* point sebelumnya +
- menjadi tempat bertanya tim
- membuat dan merumuskan konsep"',10,13,null,null,null,1);
insert into `view_kpi_assign`(`tbe_id`,`tbe_name`,`tbkg_id`,`tbkg_kpi_group_id`,`tbkg_name`,`tbk_id`,`tbk_description`,`tbk_target_nilai_1`,`tbk_target_nilai_2`,`tbk_target_nilai_3`,`tbk_target_nilai_4`,`tbk_target_nilai_5`,`tbk_bobot`,`tbka_id`,`tbka_evaluasi`,`tbka_action`,`tbka_poin`,`tbka_status`) values (5,'m m',5,'KPG5','Personal Development',14,'Hard-Skill
- OSB & ADF','','tidak berhasil ','','bisa digunakan untuk development','bisa demo dengan memuaskan',5,6,null,null,null,1);
insert into `view_kpi_assign`(`tbe_id`,`tbe_name`,`tbkg_id`,`tbkg_kpi_group_id`,`tbkg_name`,`tbk_id`,`tbk_description`,`tbk_target_nilai_1`,`tbk_target_nilai_2`,`tbk_target_nilai_3`,`tbk_target_nilai_4`,`tbk_target_nilai_5`,`tbk_bobot`,`tbka_id`,`tbka_evaluasi`,`tbka_action`,`tbka_poin`,`tbka_status`) values (6,'abc def',5,'KPG5','Personal Development',14,'Hard-Skill
- OSB & ADF','','tidak berhasil ','','bisa digunakan untuk development','bisa demo dengan memuaskan',5,14,null,null,null,1);
insert into `view_kpi_assign`(`tbe_id`,`tbe_name`,`tbkg_id`,`tbkg_kpi_group_id`,`tbkg_name`,`tbk_id`,`tbk_description`,`tbk_target_nilai_1`,`tbk_target_nilai_2`,`tbk_target_nilai_3`,`tbk_target_nilai_4`,`tbk_target_nilai_5`,`tbk_bobot`,`tbka_id`,`tbka_evaluasi`,`tbka_action`,`tbka_poin`,`tbka_status`) values (5,'m m',5,'KPG5','Personal Development',15,'Certification- SOA Implementer Certified','','Tidak diambil','<= Des 2011','<= Agustus 2011','<= Juni 2011',10,7,null,null,null,1);
insert into `view_kpi_assign`(`tbe_id`,`tbe_name`,`tbkg_id`,`tbkg_kpi_group_id`,`tbkg_name`,`tbk_id`,`tbk_description`,`tbk_target_nilai_1`,`tbk_target_nilai_2`,`tbk_target_nilai_3`,`tbk_target_nilai_4`,`tbk_target_nilai_5`,`tbk_bobot`,`tbka_id`,`tbka_evaluasi`,`tbka_action`,`tbka_poin`,`tbka_status`) values (6,'abc def',5,'KPG5','Personal Development',15,'Certification- SOA Implementer Certified','','Tidak diambil','<= Des 2011','<= Agustus 2011','<= Juni 2011',10,15,null,null,null,1);
insert into `view_kpi_assign`(`tbe_id`,`tbe_name`,`tbkg_id`,`tbkg_kpi_group_id`,`tbkg_name`,`tbk_id`,`tbk_description`,`tbk_target_nilai_1`,`tbk_target_nilai_2`,`tbk_target_nilai_3`,`tbk_target_nilai_4`,`tbk_target_nilai_5`,`tbk_bobot`,`tbka_id`,`tbka_evaluasi`,`tbka_action`,`tbka_poin`,`tbka_status`) values (5,'m m',9,'KPG9','Administration',11,'Pengisian Time Report','Missing 20%','Missing 10%','Tidak ada missing','-','-',15,1,'qwe','asd',4,4);
insert into `view_kpi_assign`(`tbe_id`,`tbe_name`,`tbkg_id`,`tbkg_kpi_group_id`,`tbkg_name`,`tbk_id`,`tbk_description`,`tbk_target_nilai_1`,`tbk_target_nilai_2`,`tbk_target_nilai_3`,`tbk_target_nilai_4`,`tbk_target_nilai_5`,`tbk_bobot`,`tbka_id`,`tbka_evaluasi`,`tbka_action`,`tbka_poin`,`tbka_status`) values (6,'abc def',9,'KPG9','Administration',11,'Pengisian Time Report','Missing 20%','Missing 10%','Tidak ada missing','-','-',15,9,null,null,null,1);
