USE hrm;

utf8_general_ci;


insert into `hrm`.`view_report_employee_information`(`tbe_id`,`tbe_employee_id`,`tbe_name`,`tbe_id_no`,`tbe_tax_no`,`tbe_dob`,`tbe_marital_status`,`tbe_smoker`,`tbe_gender`,`tbe_driver_license_no`,`tbe_driver_license_expiry`,`tbcd_street`,`tbcd_city`,`tbcd_province`,`tbcd_zip_code`,`tbcd_home_phone`,`tbcd_mobile_phone`,`tbcd_work_phone`,`tbn_nama`,`tbjt_name`,`tbj_joined_date`,`tbo_nama`,`tbes_name`,`tbes_basic_salary`,`tbes_pay_frequency`,`tbes_currency_name`,`tbp_name`,`tbe_name_report_to`,`tbae_major`,`tbl_name`,`tbs_name`) values (1,'EMP12010001','Achmad Amri','','12345','1981-08-19 00:00:00',0,1,0,'',null,'Jl. Gunung Gede V Blok C No 79. Kel. Kayuringin Jaya Kec. Bekasi Selatan','Depok','Jawa Barat','','0218844467','085881398697','','Indonesia','Job Direktur','2012-07-06 13:37:45','IT Division','Permanent',100000000,3,'Indonesian Rupiah (IDR)','Salary Grade 001',null,'2012,Universitas Gunadarma Sistem Informasi (S1),SMP Negeri 1 Palembang,SMU Negeri 10 Palembang','Bahasa,English','Java,Php');
insert into `hrm`.`view_report_employee_information`(`tbe_id`,`tbe_employee_id`,`tbe_name`,`tbe_id_no`,`tbe_tax_no`,`tbe_dob`,`tbe_marital_status`,`tbe_smoker`,`tbe_gender`,`tbe_driver_license_no`,`tbe_driver_license_expiry`,`tbcd_street`,`tbcd_city`,`tbcd_province`,`tbcd_zip_code`,`tbcd_home_phone`,`tbcd_mobile_phone`,`tbcd_work_phone`,`tbn_nama`,`tbjt_name`,`tbj_joined_date`,`tbo_nama`,`tbes_name`,`tbes_basic_salary`,`tbes_pay_frequency`,`tbes_currency_name`,`tbp_name`,`tbe_name_report_to`,`tbae_major`,`tbl_name`,`tbs_name`) values (2,'EMP12010002','Nurul Ana','','',null,0,1,1,'',null,null,null,null,null,null,null,null,null,'Job Direktur','2012-07-06 13:42:33','Marketing Division','Permanent',50000000,3,'Indonesian Rupiah','Salary Grade 001','Achmad Amri',null,null,null);
insert into `hrm`.`view_report_employee_information`(`tbe_id`,`tbe_employee_id`,`tbe_name`,`tbe_id_no`,`tbe_tax_no`,`tbe_dob`,`tbe_marital_status`,`tbe_smoker`,`tbe_gender`,`tbe_driver_license_no`,`tbe_driver_license_expiry`,`tbcd_street`,`tbcd_city`,`tbcd_province`,`tbcd_zip_code`,`tbcd_home_phone`,`tbcd_mobile_phone`,`tbcd_work_phone`,`tbn_nama`,`tbjt_name`,`tbj_joined_date`,`tbo_nama`,`tbes_name`,`tbes_basic_salary`,`tbes_pay_frequency`,`tbes_currency_name`,`tbp_name`,`tbe_name_report_to`,`tbae_major`,`tbl_name`,`tbs_name`) values (5,'EMP12010005','Miykaal Abrar','','','2008-10-29 00:00:00',1,1,0,'',null,null,null,null,null,null,null,null,null,'Job Direktur',null,null,null,100000000,3,'Indonesian Rupiah','Salary Grade 001','Nurul Ana,Achmad Amri',null,null,null);
insert into `hrm`.`view_report_employee_information`(`tbe_id`,`tbe_employee_id`,`tbe_name`,`tbe_id_no`,`tbe_tax_no`,`tbe_dob`,`tbe_marital_status`,`tbe_smoker`,`tbe_gender`,`tbe_driver_license_no`,`tbe_driver_license_expiry`,`tbcd_street`,`tbcd_city`,`tbcd_province`,`tbcd_zip_code`,`tbcd_home_phone`,`tbcd_mobile_phone`,`tbcd_work_phone`,`tbn_nama`,`tbjt_name`,`tbj_joined_date`,`tbo_nama`,`tbes_name`,`tbes_basic_salary`,`tbes_pay_frequency`,`tbes_currency_name`,`tbp_name`,`tbe_name_report_to`,`tbae_major`,`tbl_name`,`tbs_name`) values (6,'EMP12030006','abc def','','12345',null,null,null,null,'',null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,'Nurul Ana',null,null,null);
insert into `hrm`.`view_report_employee_information`(`tbe_id`,`tbe_employee_id`,`tbe_name`,`tbe_id_no`,`tbe_tax_no`,`tbe_dob`,`tbe_marital_status`,`tbe_smoker`,`tbe_gender`,`tbe_driver_license_no`,`tbe_driver_license_expiry`,`tbcd_street`,`tbcd_city`,`tbcd_province`,`tbcd_zip_code`,`tbcd_home_phone`,`tbcd_mobile_phone`,`tbcd_work_phone`,`tbn_nama`,`tbjt_name`,`tbj_joined_date`,`tbo_nama`,`tbes_name`,`tbes_basic_salary`,`tbes_pay_frequency`,`tbes_currency_name`,`tbp_name`,`tbe_name_report_to`,`tbae_major`,`tbl_name`,`tbs_name`) values (7,'EMP12070007','ghi jkl','','12345',null,null,null,null,'',null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null);
insert into `hrm`.`view_report_employee_information`(`tbe_id`,`tbe_employee_id`,`tbe_name`,`tbe_id_no`,`tbe_tax_no`,`tbe_dob`,`tbe_marital_status`,`tbe_smoker`,`tbe_gender`,`tbe_driver_license_no`,`tbe_driver_license_expiry`,`tbcd_street`,`tbcd_city`,`tbcd_province`,`tbcd_zip_code`,`tbcd_home_phone`,`tbcd_mobile_phone`,`tbcd_work_phone`,`tbn_nama`,`tbjt_name`,`tbj_joined_date`,`tbo_nama`,`tbes_name`,`tbes_basic_salary`,`tbes_pay_frequency`,`tbes_currency_name`,`tbp_name`,`tbe_name_report_to`,`tbae_major`,`tbl_name`,`tbs_name`) values (8,'EMP12010008','user1 satu','','21345',null,null,null,null,'',null,null,null,null,null,null,null,null,null,'Job Manager','2012-01-01 23:23:58','IT Division','Permanent',25000000,3,'Indonesian Rupiah (IDR)','Salary Grade 002',null,null,null,null);
