USE hrm;

utf8_general_ci;


insert into `hrm`.`view_timesheet`(`tbe_id`,`tbe_name`,`tbc_id`,`tbc_name`,`tbc_customer_id`,`tbp_id`,`tbp_project_id`,`tbp_name`,`tbpag_id`,`tbpag_project_activities_group_id`,`tbpag_name`,`tbpa_id`,`tbpa_name`,`tbt_id`,`tbt_update_time`,`tbt_start_of_week`,`tbt_day_1_hour`,`tbt_day_2_hour`,`tbt_day_3_hour`,`tbt_day_4_hour`,`tbt_day_5_hour`,`tbt_day_6_hour`,`tbt_day_7_hour`,`tbt_total_hour`,`tbt_grand_total_hour`,`tbt_approval_status`) values (2,'Nurul Ana',1,'PT. Sampoerna Telekomunikasi Indonesia','CUS1',7,'PRJ7','Implementasi SAP All Division',16,'PAG16','Sales',23,'Sales Proposal',1,'2012-04-08 16:17:28','2012-04-02',1,0,0,0,0,0,0,1,3,1);
insert into `hrm`.`view_timesheet`(`tbe_id`,`tbe_name`,`tbc_id`,`tbc_name`,`tbc_customer_id`,`tbp_id`,`tbp_project_id`,`tbp_name`,`tbpag_id`,`tbpag_project_activities_group_id`,`tbpag_name`,`tbpa_id`,`tbpa_name`,`tbt_id`,`tbt_update_time`,`tbt_start_of_week`,`tbt_day_1_hour`,`tbt_day_2_hour`,`tbt_day_3_hour`,`tbt_day_4_hour`,`tbt_day_5_hour`,`tbt_day_6_hour`,`tbt_day_7_hour`,`tbt_total_hour`,`tbt_grand_total_hour`,`tbt_approval_status`) values (2,'Nurul Ana',1,'PT. Sampoerna Telekomunikasi Indonesia','CUS1',7,'PRJ7','Implementasi SAP All Division',16,'PAG16','Sales',23,'Sales Proposal',2,'2012-04-08 16:17:39','2012-04-02',1,0,0,0,0,0,0,1,3,1);
insert into `hrm`.`view_timesheet`(`tbe_id`,`tbe_name`,`tbc_id`,`tbc_name`,`tbc_customer_id`,`tbp_id`,`tbp_project_id`,`tbp_name`,`tbpag_id`,`tbpag_project_activities_group_id`,`tbpag_name`,`tbpa_id`,`tbpa_name`,`tbt_id`,`tbt_update_time`,`tbt_start_of_week`,`tbt_day_1_hour`,`tbt_day_2_hour`,`tbt_day_3_hour`,`tbt_day_4_hour`,`tbt_day_5_hour`,`tbt_day_6_hour`,`tbt_day_7_hour`,`tbt_total_hour`,`tbt_grand_total_hour`,`tbt_approval_status`) values (2,'Nurul Ana',1,'PT. Sampoerna Telekomunikasi Indonesia','CUS1',7,'PRJ7','Implementasi SAP All Division',16,'PAG16','Sales',23,'Sales Proposal',3,'2012-04-08 16:17:48','2012-04-02',1,0,0,0,0,0,0,1,3,1);
insert into `hrm`.`view_timesheet`(`tbe_id`,`tbe_name`,`tbc_id`,`tbc_name`,`tbc_customer_id`,`tbp_id`,`tbp_project_id`,`tbp_name`,`tbpag_id`,`tbpag_project_activities_group_id`,`tbpag_name`,`tbpa_id`,`tbpa_name`,`tbt_id`,`tbt_update_time`,`tbt_start_of_week`,`tbt_day_1_hour`,`tbt_day_2_hour`,`tbt_day_3_hour`,`tbt_day_4_hour`,`tbt_day_5_hour`,`tbt_day_6_hour`,`tbt_day_7_hour`,`tbt_total_hour`,`tbt_grand_total_hour`,`tbt_approval_status`) values (2,'Nurul Ana',1,'PT. Sampoerna Telekomunikasi Indonesia','CUS1',7,'PRJ7','Implementasi SAP All Division',16,'PAG16','Sales',23,'Sales Proposal',4,'2012-07-08 07:23:21','2012-04-02',1,0,0,11,0,0,0,12,4,0);
insert into `hrm`.`view_timesheet`(`tbe_id`,`tbe_name`,`tbc_id`,`tbc_name`,`tbc_customer_id`,`tbp_id`,`tbp_project_id`,`tbp_name`,`tbpag_id`,`tbpag_project_activities_group_id`,`tbpag_name`,`tbpa_id`,`tbpa_name`,`tbt_id`,`tbt_update_time`,`tbt_start_of_week`,`tbt_day_1_hour`,`tbt_day_2_hour`,`tbt_day_3_hour`,`tbt_day_4_hour`,`tbt_day_5_hour`,`tbt_day_6_hour`,`tbt_day_7_hour`,`tbt_total_hour`,`tbt_grand_total_hour`,`tbt_approval_status`) values (2,'Nurul Ana',1,'PT. Sampoerna Telekomunikasi Indonesia','CUS1',7,'PRJ7','Implementasi SAP All Division',16,'PAG16','Sales',23,'Sales Proposal',11,'2012-04-16 16:10:33','2012-04-16',8,8,8,8,0,0,0,32,47,1);
insert into `hrm`.`view_timesheet`(`tbe_id`,`tbe_name`,`tbc_id`,`tbc_name`,`tbc_customer_id`,`tbp_id`,`tbp_project_id`,`tbp_name`,`tbpag_id`,`tbpag_project_activities_group_id`,`tbpag_name`,`tbpa_id`,`tbpa_name`,`tbt_id`,`tbt_update_time`,`tbt_start_of_week`,`tbt_day_1_hour`,`tbt_day_2_hour`,`tbt_day_3_hour`,`tbt_day_4_hour`,`tbt_day_5_hour`,`tbt_day_6_hour`,`tbt_day_7_hour`,`tbt_total_hour`,`tbt_grand_total_hour`,`tbt_approval_status`) values (2,'Nurul Ana',1,'PT. Sampoerna Telekomunikasi Indonesia','CUS1',7,'PRJ7','Implementasi SAP All Division',18,'PAG18','Development',29,'Analyze',12,'2012-04-16 16:10:12','2012-04-16',0,0,0,0,8,0,0,8,47,1);
insert into `hrm`.`view_timesheet`(`tbe_id`,`tbe_name`,`tbc_id`,`tbc_name`,`tbc_customer_id`,`tbp_id`,`tbp_project_id`,`tbp_name`,`tbpag_id`,`tbpag_project_activities_group_id`,`tbpag_name`,`tbpa_id`,`tbpa_name`,`tbt_id`,`tbt_update_time`,`tbt_start_of_week`,`tbt_day_1_hour`,`tbt_day_2_hour`,`tbt_day_3_hour`,`tbt_day_4_hour`,`tbt_day_5_hour`,`tbt_day_6_hour`,`tbt_day_7_hour`,`tbt_total_hour`,`tbt_grand_total_hour`,`tbt_approval_status`) values (2,'Nurul Ana',1,'PT. Sampoerna Telekomunikasi Indonesia','CUS1',7,'PRJ7','Implementasi SAP All Division',16,'PAG16','Sales',23,'Sales Proposal',13,'2012-06-15 14:28:40','2012-06-11',1,1,1,1,1,1,9,15,15,1);
insert into `hrm`.`view_timesheet`(`tbe_id`,`tbe_name`,`tbc_id`,`tbc_name`,`tbc_customer_id`,`tbp_id`,`tbp_project_id`,`tbp_name`,`tbpag_id`,`tbpag_project_activities_group_id`,`tbpag_name`,`tbpa_id`,`tbpa_name`,`tbt_id`,`tbt_update_time`,`tbt_start_of_week`,`tbt_day_1_hour`,`tbt_day_2_hour`,`tbt_day_3_hour`,`tbt_day_4_hour`,`tbt_day_5_hour`,`tbt_day_6_hour`,`tbt_day_7_hour`,`tbt_total_hour`,`tbt_grand_total_hour`,`tbt_approval_status`) values (1,'Achmad Amri',1,'PT. Sampoerna Telekomunikasi Indonesia','CUS1',7,'PRJ7','Implementasi SAP All Division',16,'PAG16','Sales',23,'Sales Proposal',14,'2012-01-02 10:08:54','2012-07-02',8,8,8,8,8,0,0,40,80,0);
insert into `hrm`.`view_timesheet`(`tbe_id`,`tbe_name`,`tbc_id`,`tbc_name`,`tbc_customer_id`,`tbp_id`,`tbp_project_id`,`tbp_name`,`tbpag_id`,`tbpag_project_activities_group_id`,`tbpag_name`,`tbpa_id`,`tbpa_name`,`tbt_id`,`tbt_update_time`,`tbt_start_of_week`,`tbt_day_1_hour`,`tbt_day_2_hour`,`tbt_day_3_hour`,`tbt_day_4_hour`,`tbt_day_5_hour`,`tbt_day_6_hour`,`tbt_day_7_hour`,`tbt_total_hour`,`tbt_grand_total_hour`,`tbt_approval_status`) values (1,'Achmad Amri',6,'PT. Kliring Penjaminan Efek Indonesia','CUS6',8,'PRJ8','Middleware Implementation',18,'PAG18','Development',29,'Analyze',15,'2012-07-08 00:10:04','2012-07-02',8,8,8,8,0,0,0,32,80,0);
insert into `hrm`.`view_timesheet`(`tbe_id`,`tbe_name`,`tbc_id`,`tbc_name`,`tbc_customer_id`,`tbp_id`,`tbp_project_id`,`tbp_name`,`tbpag_id`,`tbpag_project_activities_group_id`,`tbpag_name`,`tbpa_id`,`tbpa_name`,`tbt_id`,`tbt_update_time`,`tbt_start_of_week`,`tbt_day_1_hour`,`tbt_day_2_hour`,`tbt_day_3_hour`,`tbt_day_4_hour`,`tbt_day_5_hour`,`tbt_day_6_hour`,`tbt_day_7_hour`,`tbt_total_hour`,`tbt_grand_total_hour`,`tbt_approval_status`) values (1,'Achmad Amri',6,'PT. Kliring Penjaminan Efek Indonesia','CUS6',8,'PRJ8','Middleware Implementation',16,'PAG16','Sales',25,'Letter Of Intent',16,'2012-07-08 00:10:25','2012-07-02',0,0,0,0,8,0,0,8,80,0);
insert into `hrm`.`view_timesheet`(`tbe_id`,`tbe_name`,`tbc_id`,`tbc_name`,`tbc_customer_id`,`tbp_id`,`tbp_project_id`,`tbp_name`,`tbpag_id`,`tbpag_project_activities_group_id`,`tbpag_name`,`tbpa_id`,`tbpa_name`,`tbt_id`,`tbt_update_time`,`tbt_start_of_week`,`tbt_day_1_hour`,`tbt_day_2_hour`,`tbt_day_3_hour`,`tbt_day_4_hour`,`tbt_day_5_hour`,`tbt_day_6_hour`,`tbt_day_7_hour`,`tbt_total_hour`,`tbt_grand_total_hour`,`tbt_approval_status`) values (2,'Nurul Ana',1,'PT. Sampoerna Telekomunikasi Indonesia','CUS1',7,'PRJ7','Implementasi SAP All Division',16,'PAG16','Sales',23,'Sales Proposal',17,'2012-05-31 11:41:06','2012-05-28',8,0,0,0,0,0,0,8,40,1);
insert into `hrm`.`view_timesheet`(`tbe_id`,`tbe_name`,`tbc_id`,`tbc_name`,`tbc_customer_id`,`tbp_id`,`tbp_project_id`,`tbp_name`,`tbpag_id`,`tbpag_project_activities_group_id`,`tbpag_name`,`tbpa_id`,`tbpa_name`,`tbt_id`,`tbt_update_time`,`tbt_start_of_week`,`tbt_day_1_hour`,`tbt_day_2_hour`,`tbt_day_3_hour`,`tbt_day_4_hour`,`tbt_day_5_hour`,`tbt_day_6_hour`,`tbt_day_7_hour`,`tbt_total_hour`,`tbt_grand_total_hour`,`tbt_approval_status`) values (2,'Nurul Ana',1,'PT. Sampoerna Telekomunikasi Indonesia','CUS1',7,'PRJ7','Implementasi SAP All Division',19,'PAG19','Vacation',32,'Annual Leave',18,'2012-07-08 07:23:48','2012-05-28',8,8,8,8,8,0,0,40,40,0);
insert into `hrm`.`view_timesheet`(`tbe_id`,`tbe_name`,`tbc_id`,`tbc_name`,`tbc_customer_id`,`tbp_id`,`tbp_project_id`,`tbp_name`,`tbpag_id`,`tbpag_project_activities_group_id`,`tbpag_name`,`tbpa_id`,`tbpa_name`,`tbt_id`,`tbt_update_time`,`tbt_start_of_week`,`tbt_day_1_hour`,`tbt_day_2_hour`,`tbt_day_3_hour`,`tbt_day_4_hour`,`tbt_day_5_hour`,`tbt_day_6_hour`,`tbt_day_7_hour`,`tbt_total_hour`,`tbt_grand_total_hour`,`tbt_approval_status`) values (2,'Nurul Ana',1,'PT. Sampoerna Telekomunikasi Indonesia','CUS1',7,'PRJ7','Implementasi SAP All Division',16,'PAG16','Sales',23,'Sales Proposal',19,'2012-07-08 06:50:23','2012-07-02',8,8,8,8,8,0,0,40,80,0);
insert into `hrm`.`view_timesheet`(`tbe_id`,`tbe_name`,`tbc_id`,`tbc_name`,`tbc_customer_id`,`tbp_id`,`tbp_project_id`,`tbp_name`,`tbpag_id`,`tbpag_project_activities_group_id`,`tbpag_name`,`tbpa_id`,`tbpa_name`,`tbt_id`,`tbt_update_time`,`tbt_start_of_week`,`tbt_day_1_hour`,`tbt_day_2_hour`,`tbt_day_3_hour`,`tbt_day_4_hour`,`tbt_day_5_hour`,`tbt_day_6_hour`,`tbt_day_7_hour`,`tbt_total_hour`,`tbt_grand_total_hour`,`tbt_approval_status`) values (2,'Nurul Ana',1,'PT. Sampoerna Telekomunikasi Indonesia','CUS1',7,'PRJ7','Implementasi SAP All Division',16,'PAG16','Sales',23,'Sales Proposal',20,'2012-07-08 07:24:14','2012-07-02',8,8,8,8,8,0,0,40,80,0);
insert into `hrm`.`view_timesheet`(`tbe_id`,`tbe_name`,`tbc_id`,`tbc_name`,`tbc_customer_id`,`tbp_id`,`tbp_project_id`,`tbp_name`,`tbpag_id`,`tbpag_project_activities_group_id`,`tbpag_name`,`tbpa_id`,`tbpa_name`,`tbt_id`,`tbt_update_time`,`tbt_start_of_week`,`tbt_day_1_hour`,`tbt_day_2_hour`,`tbt_day_3_hour`,`tbt_day_4_hour`,`tbt_day_5_hour`,`tbt_day_6_hour`,`tbt_day_7_hour`,`tbt_total_hour`,`tbt_grand_total_hour`,`tbt_approval_status`) values (1,'Achmad Amri',1,'PT. Sampoerna Telekomunikasi Indonesia','CUS1',7,'PRJ7','Implementasi SAP All Division',16,'PAG16','Sales',23,'Sales Proposal',21,'2012-07-16 22:37:09','2012-07-16',8,8,8,8,0,0,8,40,40,0);
