USE hrm;

utf8_general_ci;


insert into `hrm`.`view_employee_renumeration`(`tbe_id`,`tbe_name`,`tbjt_id`,`tbjt_job_title_id`,`tbjt_name`,`tbr_id`,`tbr_renumeration_id`,`tbr_name`,`tbr_nominal`,`tbc_id`,`tbc_currency_id`,`tbc_name`,`tbc_local_currency_kurs`) values (1,'Achmad Amri',241,'JOB001','Job Direktur',5,'REN5','Tunjangan 1',10000,56,'IDR','Indonesian Rupiah',1);
insert into `hrm`.`view_employee_renumeration`(`tbe_id`,`tbe_name`,`tbjt_id`,`tbjt_job_title_id`,`tbjt_name`,`tbr_id`,`tbr_renumeration_id`,`tbr_name`,`tbr_nominal`,`tbc_id`,`tbc_currency_id`,`tbc_name`,`tbc_local_currency_kurs`) values (2,'Nurul Ana',241,'JOB001','Job Direktur',5,'REN5','Tunjangan 1',10000,56,'IDR','Indonesian Rupiah',1);
insert into `hrm`.`view_employee_renumeration`(`tbe_id`,`tbe_name`,`tbjt_id`,`tbjt_job_title_id`,`tbjt_name`,`tbr_id`,`tbr_renumeration_id`,`tbr_name`,`tbr_nominal`,`tbc_id`,`tbc_currency_id`,`tbc_name`,`tbc_local_currency_kurs`) values (6,'abc def',241,'JOB001','Job Direktur',5,'REN5','Tunjangan 1',10000,56,'IDR','Indonesian Rupiah',1);
insert into `hrm`.`view_employee_renumeration`(`tbe_id`,`tbe_name`,`tbjt_id`,`tbjt_job_title_id`,`tbjt_name`,`tbr_id`,`tbr_renumeration_id`,`tbr_name`,`tbr_nominal`,`tbc_id`,`tbc_currency_id`,`tbc_name`,`tbc_local_currency_kurs`) values (1,'Achmad Amri',241,'JOB001','Job Direktur',6,'REN6','Tunjangan 2',100000,56,'IDR','Indonesian Rupiah',1);
insert into `hrm`.`view_employee_renumeration`(`tbe_id`,`tbe_name`,`tbjt_id`,`tbjt_job_title_id`,`tbjt_name`,`tbr_id`,`tbr_renumeration_id`,`tbr_name`,`tbr_nominal`,`tbc_id`,`tbc_currency_id`,`tbc_name`,`tbc_local_currency_kurs`) values (2,'Nurul Ana',241,'JOB001','Job Direktur',6,'REN6','Tunjangan 2',100000,56,'IDR','Indonesian Rupiah',1);
insert into `hrm`.`view_employee_renumeration`(`tbe_id`,`tbe_name`,`tbjt_id`,`tbjt_job_title_id`,`tbjt_name`,`tbr_id`,`tbr_renumeration_id`,`tbr_name`,`tbr_nominal`,`tbc_id`,`tbc_currency_id`,`tbc_name`,`tbc_local_currency_kurs`) values (6,'abc def',241,'JOB001','Job Direktur',6,'REN6','Tunjangan 2',100000,56,'IDR','Indonesian Rupiah',1);
insert into `hrm`.`view_employee_renumeration`(`tbe_id`,`tbe_name`,`tbjt_id`,`tbjt_job_title_id`,`tbjt_name`,`tbr_id`,`tbr_renumeration_id`,`tbr_name`,`tbr_nominal`,`tbc_id`,`tbc_currency_id`,`tbc_name`,`tbc_local_currency_kurs`) values (5,'Miykaal Abrar',242,'JOB242','Job Manager',5,'REN5','Tunjangan 1',10000,56,'IDR','Indonesian Rupiah',1);
insert into `hrm`.`view_employee_renumeration`(`tbe_id`,`tbe_name`,`tbjt_id`,`tbjt_job_title_id`,`tbjt_name`,`tbr_id`,`tbr_renumeration_id`,`tbr_name`,`tbr_nominal`,`tbc_id`,`tbc_currency_id`,`tbc_name`,`tbc_local_currency_kurs`) values (7,'ghi jkl',242,'JOB242','Job Manager',5,'REN5','Tunjangan 1',10000,56,'IDR','Indonesian Rupiah',1);
insert into `hrm`.`view_employee_renumeration`(`tbe_id`,`tbe_name`,`tbjt_id`,`tbjt_job_title_id`,`tbjt_name`,`tbr_id`,`tbr_renumeration_id`,`tbr_name`,`tbr_nominal`,`tbc_id`,`tbc_currency_id`,`tbc_name`,`tbc_local_currency_kurs`) values (8,'user1 satu',242,'JOB242','Job Manager',5,'REN5','Tunjangan 1',10000,56,'IDR','Indonesian Rupiah',1);
