USE hrm;

utf8_general_ci;


insert into `hrm`.`view_menu`(`tbm_id`,`tbm_parent_id`,`tbm_nama`,`tbm_index`,`tbm_disabled`,`tbm_nama_parent`) values (1,null,'Admin','1',0,null);
insert into `hrm`.`view_menu`(`tbm_id`,`tbm_parent_id`,`tbm_nama`,`tbm_index`,`tbm_disabled`,`tbm_nama_parent`) values (112,78,'KPI','1',0,'Performance');
insert into `hrm`.`view_menu`(`tbm_id`,`tbm_parent_id`,`tbm_nama`,`tbm_index`,`tbm_disabled`,`tbm_nama_parent`) values (109,107,'Approval Loan','1',0,'Loan');
insert into `hrm`.`view_menu`(`tbm_id`,`tbm_parent_id`,`tbm_nama`,`tbm_index`,`tbm_disabled`,`tbm_nama_parent`) values (122,121,'PTKP','1',0,'Tax');
insert into `hrm`.`view_menu`(`tbm_id`,`tbm_parent_id`,`tbm_nama`,`tbm_index`,`tbm_disabled`,`tbm_nama_parent`) values (2,1,'Company Info','111',0,'Admin');
insert into `hrm`.`view_menu`(`tbm_id`,`tbm_parent_id`,`tbm_nama`,`tbm_index`,`tbm_disabled`,`tbm_nama_parent`) values (3,2,'General','1111',0,'Company Info');
insert into `hrm`.`view_menu`(`tbm_id`,`tbm_parent_id`,`tbm_nama`,`tbm_index`,`tbm_disabled`,`tbm_nama_parent`) values (4,2,'Locations','1112',0,'Company Info');
insert into `hrm`.`view_menu`(`tbm_id`,`tbm_parent_id`,`tbm_nama`,`tbm_index`,`tbm_disabled`,`tbm_nama_parent`) values (5,2,'Company Structure','1113',0,'Company Info');
insert into `hrm`.`view_menu`(`tbm_id`,`tbm_parent_id`,`tbm_nama`,`tbm_index`,`tbm_disabled`,`tbm_nama_parent`) values (6,2,'Company Property','1114',0,'Company Info');
insert into `hrm`.`view_menu`(`tbm_id`,`tbm_parent_id`,`tbm_nama`,`tbm_index`,`tbm_disabled`,`tbm_nama_parent`) values (7,1,'Job','112',0,'Admin');
insert into `hrm`.`view_menu`(`tbm_id`,`tbm_parent_id`,`tbm_nama`,`tbm_index`,`tbm_disabled`,`tbm_nama_parent`) values (8,7,'Job Titles','1121',0,'Job');
insert into `hrm`.`view_menu`(`tbm_id`,`tbm_parent_id`,`tbm_nama`,`tbm_index`,`tbm_disabled`,`tbm_nama_parent`) values (9,7,'Job Specifications','1122',0,'Job');
insert into `hrm`.`view_menu`(`tbm_id`,`tbm_parent_id`,`tbm_nama`,`tbm_index`,`tbm_disabled`,`tbm_nama_parent`) values (10,7,'Salary Grades','1123',0,'Job');
insert into `hrm`.`view_menu`(`tbm_id`,`tbm_parent_id`,`tbm_nama`,`tbm_index`,`tbm_disabled`,`tbm_nama_parent`) values (11,7,'Employment Status','1125',0,'Job');
insert into `hrm`.`view_menu`(`tbm_id`,`tbm_parent_id`,`tbm_nama`,`tbm_index`,`tbm_disabled`,`tbm_nama_parent`) values (12,7,'EEO Job Categories','1126',0,'Job');
insert into `hrm`.`view_menu`(`tbm_id`,`tbm_parent_id`,`tbm_nama`,`tbm_index`,`tbm_disabled`,`tbm_nama_parent`) values (13,1,'Qualification','113',0,'Admin');
insert into `hrm`.`view_menu`(`tbm_id`,`tbm_parent_id`,`tbm_nama`,`tbm_index`,`tbm_disabled`,`tbm_nama_parent`) values (14,13,'Education','1131',0,'Qualification');
insert into `hrm`.`view_menu`(`tbm_id`,`tbm_parent_id`,`tbm_nama`,`tbm_index`,`tbm_disabled`,`tbm_nama_parent`) values (15,13,'Licenses','1132',0,'Qualification');
insert into `hrm`.`view_menu`(`tbm_id`,`tbm_parent_id`,`tbm_nama`,`tbm_index`,`tbm_disabled`,`tbm_nama_parent`) values (16,1,'Skills','114',0,'Admin');
insert into `hrm`.`view_menu`(`tbm_id`,`tbm_parent_id`,`tbm_nama`,`tbm_index`,`tbm_disabled`,`tbm_nama_parent`) values (17,16,'Skills','1141',0,'Skills');
insert into `hrm`.`view_menu`(`tbm_id`,`tbm_parent_id`,`tbm_nama`,`tbm_index`,`tbm_disabled`,`tbm_nama_parent`) values (18,16,'Languages','1142',0,'Skills');
insert into `hrm`.`view_menu`(`tbm_id`,`tbm_parent_id`,`tbm_nama`,`tbm_index`,`tbm_disabled`,`tbm_nama_parent`) values (19,1,'Memberships','115',1,'Admin');
insert into `hrm`.`view_menu`(`tbm_id`,`tbm_parent_id`,`tbm_nama`,`tbm_index`,`tbm_disabled`,`tbm_nama_parent`) values (20,19,'Membership Types','1151',1,'Memberships');
insert into `hrm`.`view_menu`(`tbm_id`,`tbm_parent_id`,`tbm_nama`,`tbm_index`,`tbm_disabled`,`tbm_nama_parent`) values (21,19,'Memberships','1152',1,'Memberships');
insert into `hrm`.`view_menu`(`tbm_id`,`tbm_parent_id`,`tbm_nama`,`tbm_index`,`tbm_disabled`,`tbm_nama_parent`) values (22,1,'Nationality & Race','116',0,'Admin');
insert into `hrm`.`view_menu`(`tbm_id`,`tbm_parent_id`,`tbm_nama`,`tbm_index`,`tbm_disabled`,`tbm_nama_parent`) values (23,22,'Nationality','1161',0,'Nationality & Race');
insert into `hrm`.`view_menu`(`tbm_id`,`tbm_parent_id`,`tbm_nama`,`tbm_index`,`tbm_disabled`,`tbm_nama_parent`) values (24,22,'Ethnic Races','1162',0,'Nationality & Race');
insert into `hrm`.`view_menu`(`tbm_id`,`tbm_parent_id`,`tbm_nama`,`tbm_index`,`tbm_disabled`,`tbm_nama_parent`) values (25,1,'Users','117',0,'Admin');
insert into `hrm`.`view_menu`(`tbm_id`,`tbm_parent_id`,`tbm_nama`,`tbm_index`,`tbm_disabled`,`tbm_nama_parent`) values (26,25,'HR Admin Users','1171',0,'Users');
insert into `hrm`.`view_menu`(`tbm_id`,`tbm_parent_id`,`tbm_nama`,`tbm_index`,`tbm_disabled`,`tbm_nama_parent`) values (27,25,'ESS Users','1172',0,'Users');
insert into `hrm`.`view_menu`(`tbm_id`,`tbm_parent_id`,`tbm_nama`,`tbm_index`,`tbm_disabled`,`tbm_nama_parent`) values (28,25,'Admin User Groups','1173',0,'Users');
insert into `hrm`.`view_menu`(`tbm_id`,`tbm_parent_id`,`tbm_nama`,`tbm_index`,`tbm_disabled`,`tbm_nama_parent`) values (103,1,'Leave','118',0,'Admin');
insert into `hrm`.`view_menu`(`tbm_id`,`tbm_parent_id`,`tbm_nama`,`tbm_index`,`tbm_disabled`,`tbm_nama_parent`) values (33,32,'Customers','1181',0,'Project Info');
insert into `hrm`.`view_menu`(`tbm_id`,`tbm_parent_id`,`tbm_nama`,`tbm_index`,`tbm_disabled`,`tbm_nama_parent`) values (34,32,'Projects','1182',0,'Project Info');
insert into `hrm`.`view_menu`(`tbm_id`,`tbm_parent_id`,`tbm_nama`,`tbm_index`,`tbm_disabled`,`tbm_nama_parent`) values (94,32,'Activity Groups','1183',0,'Project Info');
insert into `hrm`.`view_menu`(`tbm_id`,`tbm_parent_id`,`tbm_nama`,`tbm_index`,`tbm_disabled`,`tbm_nama_parent`) values (95,32,'Activities','1184',0,'Project Info');
insert into `hrm`.`view_menu`(`tbm_id`,`tbm_parent_id`,`tbm_nama`,`tbm_index`,`tbm_disabled`,`tbm_nama_parent`) values (32,1,'Project Info','119',0,'Admin');
insert into `hrm`.`view_menu`(`tbm_id`,`tbm_parent_id`,`tbm_nama`,`tbm_index`,`tbm_disabled`,`tbm_nama_parent`) values (64,104,'Shifts','1191',0,'Time');
insert into `hrm`.`view_menu`(`tbm_id`,`tbm_parent_id`,`tbm_nama`,`tbm_index`,`tbm_disabled`,`tbm_nama_parent`) values (91,92,'Menu','1191',0,'System Settings');
insert into `hrm`.`view_menu`(`tbm_id`,`tbm_parent_id`,`tbm_nama`,`tbm_index`,`tbm_disabled`,`tbm_nama_parent`) values (104,1,'Time','119b',0,'Admin');
insert into `hrm`.`view_menu`(`tbm_id`,`tbm_parent_id`,`tbm_nama`,`tbm_index`,`tbm_disabled`,`tbm_nama_parent`) values (113,1,'Performance','119c',0,'Admin');
insert into `hrm`.`view_menu`(`tbm_id`,`tbm_parent_id`,`tbm_nama`,`tbm_index`,`tbm_disabled`,`tbm_nama_parent`) values (121,1,'Tax','119d',0,'Admin');
insert into `hrm`.`view_menu`(`tbm_id`,`tbm_parent_id`,`tbm_nama`,`tbm_index`,`tbm_disabled`,`tbm_nama_parent`) values (92,1,'System Settings','119e',0,'Admin');
insert into `hrm`.`view_menu`(`tbm_id`,`tbm_parent_id`,`tbm_nama`,`tbm_index`,`tbm_disabled`,`tbm_nama_parent`) values (42,null,'PIM','2',0,null);
insert into `hrm`.`view_menu`(`tbm_id`,`tbm_parent_id`,`tbm_nama`,`tbm_index`,`tbm_disabled`,`tbm_nama_parent`) values (123,121,'Tax Rate','2',0,'Tax');
insert into `hrm`.`view_menu`(`tbm_id`,`tbm_parent_id`,`tbm_nama`,`tbm_index`,`tbm_disabled`,`tbm_nama_parent`) values (108,107,'Loan List','2',0,'Loan');
insert into `hrm`.`view_menu`(`tbm_id`,`tbm_parent_id`,`tbm_nama`,`tbm_index`,`tbm_disabled`,`tbm_nama_parent`) values (114,78,'KPI Assign','2',0,'Performance');
insert into `hrm`.`view_menu`(`tbm_id`,`tbm_parent_id`,`tbm_nama`,`tbm_index`,`tbm_disabled`,`tbm_nama_parent`) values (43,42,'Employee List','21',0,'PIM');
insert into `hrm`.`view_menu`(`tbm_id`,`tbm_parent_id`,`tbm_nama`,`tbm_index`,`tbm_disabled`,`tbm_nama_parent`) values (44,42,'Add Employee','22',0,'PIM');
insert into `hrm`.`view_menu`(`tbm_id`,`tbm_parent_id`,`tbm_nama`,`tbm_index`,`tbm_disabled`,`tbm_nama_parent`) values (115,78,'KPI Approval','3',0,'Performance');
insert into `hrm`.`view_menu`(`tbm_id`,`tbm_parent_id`,`tbm_nama`,`tbm_index`,`tbm_disabled`,`tbm_nama_parent`) values (45,null,'Leave','3',0,null);
insert into `hrm`.`view_menu`(`tbm_id`,`tbm_parent_id`,`tbm_nama`,`tbm_index`,`tbm_disabled`,`tbm_nama_parent`) values (47,45,'Employee Leave Summary','31',0,'Leave');
insert into `hrm`.`view_menu`(`tbm_id`,`tbm_parent_id`,`tbm_nama`,`tbm_index`,`tbm_disabled`,`tbm_nama_parent`) values (50,103,'Holidays','32',0,'Leave');
insert into `hrm`.`view_menu`(`tbm_id`,`tbm_parent_id`,`tbm_nama`,`tbm_index`,`tbm_disabled`,`tbm_nama_parent`) values (51,103,'Leave Types','33',0,'Leave');
insert into `hrm`.`view_menu`(`tbm_id`,`tbm_parent_id`,`tbm_nama`,`tbm_index`,`tbm_disabled`,`tbm_nama_parent`) values (52,45,'Approval Leave','34',0,'Leave');
insert into `hrm`.`view_menu`(`tbm_id`,`tbm_parent_id`,`tbm_nama`,`tbm_index`,`tbm_disabled`,`tbm_nama_parent`) values (53,45,'Leave List','35',0,'Leave');
insert into `hrm`.`view_menu`(`tbm_id`,`tbm_parent_id`,`tbm_nama`,`tbm_index`,`tbm_disabled`,`tbm_nama_parent`) values (107,null,'Loan','3a',0,null);
insert into `hrm`.`view_menu`(`tbm_id`,`tbm_parent_id`,`tbm_nama`,`tbm_index`,`tbm_disabled`,`tbm_nama_parent`) values (54,null,'Time','4',0,null);
insert into `hrm`.`view_menu`(`tbm_id`,`tbm_parent_id`,`tbm_nama`,`tbm_index`,`tbm_disabled`,`tbm_nama_parent`) values (116,78,'KPI Employee','4',0,'Performance');
insert into `hrm`.`view_menu`(`tbm_id`,`tbm_parent_id`,`tbm_nama`,`tbm_index`,`tbm_disabled`,`tbm_nama_parent`) values (56,54,'Timesheets','42',0,'Time');
insert into `hrm`.`view_menu`(`tbm_id`,`tbm_parent_id`,`tbm_nama`,`tbm_index`,`tbm_disabled`,`tbm_nama_parent`) values (99,56,'Timesheet','421',0,'Timesheets');
insert into `hrm`.`view_menu`(`tbm_id`,`tbm_parent_id`,`tbm_nama`,`tbm_index`,`tbm_disabled`,`tbm_nama_parent`) values (98,59,'Attendance','421',0,'Attendance');
insert into `hrm`.`view_menu`(`tbm_id`,`tbm_parent_id`,`tbm_nama`,`tbm_index`,`tbm_disabled`,`tbm_nama_parent`) values (97,59,'Punch In/Out','422',0,'Attendance');
insert into `hrm`.`view_menu`(`tbm_id`,`tbm_parent_id`,`tbm_nama`,`tbm_index`,`tbm_disabled`,`tbm_nama_parent`) values (100,56,'Approval Timesheet','422',0,'Timesheets');
insert into `hrm`.`view_menu`(`tbm_id`,`tbm_parent_id`,`tbm_nama`,`tbm_index`,`tbm_disabled`,`tbm_nama_parent`) values (30,29,'Configuration','422',0,'Email Notifications');
insert into `hrm`.`view_menu`(`tbm_id`,`tbm_parent_id`,`tbm_nama`,`tbm_index`,`tbm_disabled`,`tbm_nama_parent`) values (101,56,'Project Timesheet','423',0,'Timesheets');
insert into `hrm`.`view_menu`(`tbm_id`,`tbm_parent_id`,`tbm_nama`,`tbm_index`,`tbm_disabled`,`tbm_nama_parent`) values (59,54,'Attendance','43',0,'Time');
insert into `hrm`.`view_menu`(`tbm_id`,`tbm_parent_id`,`tbm_nama`,`tbm_index`,`tbm_disabled`,`tbm_nama_parent`) values (66,65,'Health Saving Plan','51',0,'Benefits');
insert into `hrm`.`view_menu`(`tbm_id`,`tbm_parent_id`,`tbm_nama`,`tbm_index`,`tbm_disabled`,`tbm_nama_parent`) values (67,66,'Define HSP','511',0,'Health Saving Plan');
insert into `hrm`.`view_menu`(`tbm_id`,`tbm_parent_id`,`tbm_nama`,`tbm_index`,`tbm_disabled`,`tbm_nama_parent`) values (68,66,'Employee HSP Summary','512',0,'Health Saving Plan');
insert into `hrm`.`view_menu`(`tbm_id`,`tbm_parent_id`,`tbm_nama`,`tbm_index`,`tbm_disabled`,`tbm_nama_parent`) values (69,66,'HSP Payments Due','513',0,'Health Saving Plan');
insert into `hrm`.`view_menu`(`tbm_id`,`tbm_parent_id`,`tbm_nama`,`tbm_index`,`tbm_disabled`,`tbm_nama_parent`) values (70,66,'HSP Expenditures','514',0,'Health Saving Plan');
insert into `hrm`.`view_menu`(`tbm_id`,`tbm_parent_id`,`tbm_nama`,`tbm_index`,`tbm_disabled`,`tbm_nama_parent`) values (71,66,'HSP Used','515',0,'Health Saving Plan');
insert into `hrm`.`view_menu`(`tbm_id`,`tbm_parent_id`,`tbm_nama`,`tbm_index`,`tbm_disabled`,`tbm_nama_parent`) values (72,65,'Payroll Schedule','52',0,'Benefits');
insert into `hrm`.`view_menu`(`tbm_id`,`tbm_parent_id`,`tbm_nama`,`tbm_index`,`tbm_disabled`,`tbm_nama_parent`) values (73,72,'View Payroll Schedule','521',0,'Payroll Schedule');
insert into `hrm`.`view_menu`(`tbm_id`,`tbm_parent_id`,`tbm_nama`,`tbm_index`,`tbm_disabled`,`tbm_nama_parent`) values (74,72,'Add Pay Period','522',0,'Payroll Schedule');
insert into `hrm`.`view_menu`(`tbm_id`,`tbm_parent_id`,`tbm_nama`,`tbm_index`,`tbm_disabled`,`tbm_nama_parent`) values (76,75,'Job Vacancies','61',0,'Recruitment');
insert into `hrm`.`view_menu`(`tbm_id`,`tbm_parent_id`,`tbm_nama`,`tbm_index`,`tbm_disabled`,`tbm_nama_parent`) values (77,75,'Applicants','62',0,'Recruitment');
insert into `hrm`.`view_menu`(`tbm_id`,`tbm_parent_id`,`tbm_nama`,`tbm_index`,`tbm_disabled`,`tbm_nama_parent`) values (78,null,'Performance','7',0,null);
insert into `hrm`.`view_menu`(`tbm_id`,`tbm_parent_id`,`tbm_nama`,`tbm_index`,`tbm_disabled`,`tbm_nama_parent`) values (89,null,'ESS','8',0,null);
insert into `hrm`.`view_menu`(`tbm_id`,`tbm_parent_id`,`tbm_nama`,`tbm_index`,`tbm_disabled`,`tbm_nama_parent`) values (90,89,'ESS','81',0,'ESS');
insert into `hrm`.`view_menu`(`tbm_id`,`tbm_parent_id`,`tbm_nama`,`tbm_index`,`tbm_disabled`,`tbm_nama_parent`) values (84,null,'Reports','9',0,null);
insert into `hrm`.`view_menu`(`tbm_id`,`tbm_parent_id`,`tbm_nama`,`tbm_index`,`tbm_disabled`,`tbm_nama_parent`) values (106,7,'Renumeration','999',0,'Job');
insert into `hrm`.`view_menu`(`tbm_id`,`tbm_parent_id`,`tbm_nama`,`tbm_index`,`tbm_disabled`,`tbm_nama_parent`) values (105,104,'Employee Shift','999',0,'Time');
insert into `hrm`.`view_menu`(`tbm_id`,`tbm_parent_id`,`tbm_nama`,`tbm_index`,`tbm_disabled`,`tbm_nama_parent`) values (102,null,'System','999',0,null);
insert into `hrm`.`view_menu`(`tbm_id`,`tbm_parent_id`,`tbm_nama`,`tbm_index`,`tbm_disabled`,`tbm_nama_parent`) values (111,113,'KPI Groups','999',0,'Performance');
insert into `hrm`.`view_menu`(`tbm_id`,`tbm_parent_id`,`tbm_nama`,`tbm_index`,`tbm_disabled`,`tbm_nama_parent`) values (120,84,'Employee Information','999',0,'Reports');
insert into `hrm`.`view_menu`(`tbm_id`,`tbm_parent_id`,`tbm_nama`,`tbm_index`,`tbm_disabled`,`tbm_nama_parent`) values (125,121,'PTT','999',0,'Tax');
insert into `hrm`.`view_menu`(`tbm_id`,`tbm_parent_id`,`tbm_nama`,`tbm_index`,`tbm_disabled`,`tbm_nama_parent`) values (88,102,'Logout','999',0,'System');
insert into `hrm`.`view_menu`(`tbm_id`,`tbm_parent_id`,`tbm_nama`,`tbm_index`,`tbm_disabled`,`tbm_nama_parent`) values (40,36,'Import','9999',1,'Data Import/Export');
insert into `hrm`.`view_menu`(`tbm_id`,`tbm_parent_id`,`tbm_nama`,`tbm_index`,`tbm_disabled`,`tbm_nama_parent`) values (62,54,'Employee Reports','9999',1,'Time');
insert into `hrm`.`view_menu`(`tbm_id`,`tbm_parent_id`,`tbm_nama`,`tbm_index`,`tbm_disabled`,`tbm_nama_parent`) values (48,45,'Define Days Off','9999',1,'Leave');
insert into `hrm`.`view_menu`(`tbm_id`,`tbm_parent_id`,`tbm_nama`,`tbm_index`,`tbm_disabled`,`tbm_nama_parent`) values (126,121,'Employee PTT','9999',0,'Tax');
insert into `hrm`.`view_menu`(`tbm_id`,`tbm_parent_id`,`tbm_nama`,`tbm_index`,`tbm_disabled`,`tbm_nama_parent`) values (65,null,'Benefits','9999',1,null);
insert into `hrm`.`view_menu`(`tbm_id`,`tbm_parent_id`,`tbm_nama`,`tbm_index`,`tbm_disabled`,`tbm_nama_parent`) values (46,45,'Leave Summary','9999',1,'Leave');
insert into `hrm`.`view_menu`(`tbm_id`,`tbm_parent_id`,`tbm_nama`,`tbm_index`,`tbm_disabled`,`tbm_nama_parent`) values (39,36,'Define Custome Import','9999',1,'Data Import/Export');
insert into `hrm`.`view_menu`(`tbm_id`,`tbm_parent_id`,`tbm_nama`,`tbm_index`,`tbm_disabled`,`tbm_nama_parent`) values (29,1,'Email Notifications','9999',1,'Admin');
insert into `hrm`.`view_menu`(`tbm_id`,`tbm_parent_id`,`tbm_nama`,`tbm_index`,`tbm_disabled`,`tbm_nama_parent`) values (41,1,'Custom Fields','9999',1,'Admin');
insert into `hrm`.`view_menu`(`tbm_id`,`tbm_parent_id`,`tbm_nama`,`tbm_index`,`tbm_disabled`,`tbm_nama_parent`) values (57,56,'Print Timesheets','9999',1,'Timesheets');
insert into `hrm`.`view_menu`(`tbm_id`,`tbm_parent_id`,`tbm_nama`,`tbm_index`,`tbm_disabled`,`tbm_nama_parent`) values (58,56,'Employee Timesheets','9999',1,'Timesheets');
insert into `hrm`.`view_menu`(`tbm_id`,`tbm_parent_id`,`tbm_nama`,`tbm_index`,`tbm_disabled`,`tbm_nama_parent`) values (36,1,'Data Import/Export','9999',1,'Admin');
insert into `hrm`.`view_menu`(`tbm_id`,`tbm_parent_id`,`tbm_nama`,`tbm_index`,`tbm_disabled`,`tbm_nama_parent`) values (37,36,'Define Custome Export','9999',1,'Data Import/Export');
insert into `hrm`.`view_menu`(`tbm_id`,`tbm_parent_id`,`tbm_nama`,`tbm_index`,`tbm_disabled`,`tbm_nama_parent`) values (86,84,'Define Reports','9999',1,'Reports');
insert into `hrm`.`view_menu`(`tbm_id`,`tbm_parent_id`,`tbm_nama`,`tbm_index`,`tbm_disabled`,`tbm_nama_parent`) values (85,84,'View Reports','9999',1,'Reports');
insert into `hrm`.`view_menu`(`tbm_id`,`tbm_parent_id`,`tbm_nama`,`tbm_index`,`tbm_disabled`,`tbm_nama_parent`) values (63,54,'Project Reports','9999',1,'Time');
insert into `hrm`.`view_menu`(`tbm_id`,`tbm_parent_id`,`tbm_nama`,`tbm_index`,`tbm_disabled`,`tbm_nama_parent`) values (75,null,'Recruitment','9999',1,null);
insert into `hrm`.`view_menu`(`tbm_id`,`tbm_parent_id`,`tbm_nama`,`tbm_index`,`tbm_disabled`,`tbm_nama_parent`) values (31,29,'Subscribe','9999',1,'Email Notifications');
insert into `hrm`.`view_menu`(`tbm_id`,`tbm_parent_id`,`tbm_nama`,`tbm_index`,`tbm_disabled`,`tbm_nama_parent`) values (38,36,'Export','9999',1,'Data Import/Export');
insert into `hrm`.`view_menu`(`tbm_id`,`tbm_parent_id`,`tbm_nama`,`tbm_index`,`tbm_disabled`,`tbm_nama_parent`) values (55,54,'Beginning Of The Week','9999',1,'Time');
insert into `hrm`.`view_menu`(`tbm_id`,`tbm_parent_id`,`tbm_nama`,`tbm_index`,`tbm_disabled`,`tbm_nama_parent`) values (49,48,'Days Off','9999',1,'Define Days Off');
insert into `hrm`.`view_menu`(`tbm_id`,`tbm_parent_id`,`tbm_nama`,`tbm_index`,`tbm_disabled`,`tbm_nama_parent`) values (127,92,'Currency','9999',0,'System Settings');
