USE hrm;

utf8_general_ci;


insert into `view_kpi`(`tbkg_id`,`tbkg_kpi_group_id`,`tbkg_name`,`tbe_name`,`tbk_id`,`tbk_description`,`tbk_target_nilai_1`,`tbk_target_nilai_2`,`tbk_target_nilai_3`,`tbk_target_nilai_4`,`tbk_target_nilai_5`,`tbk_bobot`,`tbe_id`) values (3,'KPG3','Implementation','n n',4,'Penyelesaian projek sesuai dengan alokasi mandays berdasarkan Project Assignment Letter','Rata-rata projek diselesaikan melebihi 130% dari alokasi mandays yang telah ditetapkan','Rata-rata projek diselesaikan dalam batas sampai 130% dari alokasi mandays yang telah ditetapkan ','Rata-rata projek diselesaikan sampai batas  120% dari alokasi mandays yang telah ditetapkan ','Rata-rata projek diselesaikan dalam batas 100% dari alokasi mandays yang telah ditetapkan ','Rata-rata projek diselesaikan dalam batas kurang dari 100% dari alokasi mandays ',25,2);
insert into `view_kpi`(`tbkg_id`,`tbkg_kpi_group_id`,`tbkg_name`,`tbe_name`,`tbk_id`,`tbk_description`,`tbk_target_nilai_1`,`tbk_target_nilai_2`,`tbk_target_nilai_3`,`tbk_target_nilai_4`,`tbk_target_nilai_5`,`tbk_bobot`,`tbe_id`) values (3,'KPG3','Implementation','n n',9,'Qualitas / Metodologi Pekerjaan yang dihasilkan termasuk Dokumentasi','Tidak ada metodologi yang diterapkan','Tidak konsisten dalam menerapkan metodologi','Konsisten mengikuti Metodologi Pekerjaan dibuktikan melalui pembuatan dokumentasi yang memenuhi standar','Syarat sebelumnya ditambah semua dokumentasi diupload ke Intranet','Membuat standar kerangka untuk dokumentasi pekerjaan',15,2);
insert into `view_kpi`(`tbkg_id`,`tbkg_kpi_group_id`,`tbkg_name`,`tbe_name`,`tbk_id`,`tbk_description`,`tbk_target_nilai_1`,`tbk_target_nilai_2`,`tbk_target_nilai_3`,`tbk_target_nilai_4`,`tbk_target_nilai_5`,`tbk_bobot`,`tbe_id`) values (3,'KPG3','Implementation','n n',10,'Customer Satisfaction','Complain Resmi tertulis atau Feedback dari customer rata-rata 1','Ada complain atau Feedback dari customer rata-rata 2','No Complain atau Feedback dari customer minimum 3','Feedback rata-rata dari customer >=3.5','Ada Written Complement Letter dari Customer',10,2);
insert into `view_kpi`(`tbkg_id`,`tbkg_kpi_group_id`,`tbkg_name`,`tbe_name`,`tbk_id`,`tbk_description`,`tbk_target_nilai_1`,`tbk_target_nilai_2`,`tbk_target_nilai_3`,`tbk_target_nilai_4`,`tbk_target_nilai_5`,`tbk_bobot`,`tbe_id`) values (4,'KPG4','Pre Sales','n n',12,'Melakukan: (1) Identifikasi Kebutuhan Pelanggan; (2) Architecting Solution; (3) Presentation; (4) Proposal Preparation; (5) POC/Demo; (6) Handover to Delivery (7) Project Closing Review.  Pengukuran berdasarkan feedback form untuk setiap opportunity baik ','Feedback rata-rata dari tim Sales atau tim Delivery adalah < 2','Feedback rata-rata dari tim Sales atau tim Delivery adalah <3','Feedback rata-rata atas aktifitas yang sudah dilakukan dari tim sales dan tim delivery adalah => 3 dan <4','Feedback rata-rata atas aktifitas yang sudah dilakukan dari tim sales dan tim delivery adalah >=4','Feedback 4 + compliment letter dari DM Sales',10,2);
insert into `view_kpi`(`tbkg_id`,`tbkg_kpi_group_id`,`tbkg_name`,`tbe_name`,`tbk_id`,`tbk_description`,`tbk_target_nilai_1`,`tbk_target_nilai_2`,`tbk_target_nilai_3`,`tbk_target_nilai_4`,`tbk_target_nilai_5`,`tbk_bobot`,`tbe_id`) values (5,'KPG5','Personal Development','n n',13,'Soft-Skill
- Problem solving
','','','- mencari alternatif jawaban
- mencari hal-hal baru
- mendaya gunakan berbagai resource','* point sebelumnya +
- mencipta cara baru yg lebih baik
- menimbang pros dan cons dari alternatif','* point sebelumnya +
- menjadi tempat bertanya tim
- membuat dan merumuskan konsep"',10,2);
insert into `view_kpi`(`tbkg_id`,`tbkg_kpi_group_id`,`tbkg_name`,`tbe_name`,`tbk_id`,`tbk_description`,`tbk_target_nilai_1`,`tbk_target_nilai_2`,`tbk_target_nilai_3`,`tbk_target_nilai_4`,`tbk_target_nilai_5`,`tbk_bobot`,`tbe_id`) values (5,'KPG5','Personal Development','n n',14,'Hard-Skill
- OSB & ADF','','tidak berhasil ','','bisa digunakan untuk development','bisa demo dengan memuaskan',5,2);
insert into `view_kpi`(`tbkg_id`,`tbkg_kpi_group_id`,`tbkg_name`,`tbe_name`,`tbk_id`,`tbk_description`,`tbk_target_nilai_1`,`tbk_target_nilai_2`,`tbk_target_nilai_3`,`tbk_target_nilai_4`,`tbk_target_nilai_5`,`tbk_bobot`,`tbe_id`) values (5,'KPG5','Personal Development','n n',15,'Certification- SOA Implementer Certified','','Tidak diambil','<= Des 2011','<= Agustus 2011','<= Juni 2011',10,2);
insert into `view_kpi`(`tbkg_id`,`tbkg_kpi_group_id`,`tbkg_name`,`tbe_name`,`tbk_id`,`tbk_description`,`tbk_target_nilai_1`,`tbk_target_nilai_2`,`tbk_target_nilai_3`,`tbk_target_nilai_4`,`tbk_target_nilai_5`,`tbk_bobot`,`tbe_id`) values (9,'KPG9','Administration','n n',11,'Pengisian Time Report','Missing 20%','Missing 10%','Tidak ada missing','-','-',15,2);
