USE hrm;

utf8_general_ci;


insert into `hrm`.`view_employee_leaves`(`tbe_id`,`tbe_employee_id`,`tbe_first_name`,`tbe_middle_name`,`tbe_last_name`,`tbe_nick_name`,`tbe_name`,`tbale_id`,`tbale_start_date`,`tbale_end_date`,`tbale_comments`,`tbale_status`,`tbale_leave_taken`,`tblt_id`,`tblt_leave_types_id`,`tblt_name`) values (6,'EMP12030006','abc','','def','','abc def',11,null,null,null,1,0,2,'LVT2','Medical');
insert into `hrm`.`view_employee_leaves`(`tbe_id`,`tbe_employee_id`,`tbe_first_name`,`tbe_middle_name`,`tbe_last_name`,`tbe_nick_name`,`tbe_name`,`tbale_id`,`tbale_start_date`,`tbale_end_date`,`tbale_comments`,`tbale_status`,`tbale_leave_taken`,`tblt_id`,`tblt_leave_types_id`,`tblt_name`) values (6,'EMP12030006','abc','','def','','abc def',4,null,null,null,1,0,1,'LVT1','Casual');
insert into `hrm`.`view_employee_leaves`(`tbe_id`,`tbe_employee_id`,`tbe_first_name`,`tbe_middle_name`,`tbe_last_name`,`tbe_nick_name`,`tbe_name`,`tbale_id`,`tbale_start_date`,`tbale_end_date`,`tbale_comments`,`tbale_status`,`tbale_leave_taken`,`tblt_id`,`tblt_leave_types_id`,`tblt_name`) values (1,'EMP12010001','Achmad','','Amri','Aan','Achmad Amri',8,null,null,null,1,0,2,'LVT2','Medical');
insert into `hrm`.`view_employee_leaves`(`tbe_id`,`tbe_employee_id`,`tbe_first_name`,`tbe_middle_name`,`tbe_last_name`,`tbe_nick_name`,`tbe_name`,`tbale_id`,`tbale_start_date`,`tbale_end_date`,`tbale_comments`,`tbale_status`,`tbale_leave_taken`,`tblt_id`,`tblt_leave_types_id`,`tblt_name`) values (1,'EMP12010001','Achmad','','Amri','Aan','Achmad Amri',1,null,null,null,1,0,1,'LVT1','Casual');
insert into `hrm`.`view_employee_leaves`(`tbe_id`,`tbe_employee_id`,`tbe_first_name`,`tbe_middle_name`,`tbe_last_name`,`tbe_nick_name`,`tbe_name`,`tbale_id`,`tbale_start_date`,`tbale_end_date`,`tbale_comments`,`tbale_status`,`tbale_leave_taken`,`tblt_id`,`tblt_leave_types_id`,`tblt_name`) values (5,'EMP12010005','Miykaal','','Abrar','','Miykaal Abrar',10,null,null,null,1,0,2,'LVT2','Medical');
insert into `hrm`.`view_employee_leaves`(`tbe_id`,`tbe_employee_id`,`tbe_first_name`,`tbe_middle_name`,`tbe_last_name`,`tbe_nick_name`,`tbe_name`,`tbale_id`,`tbale_start_date`,`tbale_end_date`,`tbale_comments`,`tbale_status`,`tbale_leave_taken`,`tblt_id`,`tblt_leave_types_id`,`tblt_name`) values (5,'EMP12010005','Miykaal','','Abrar','','Miykaal Abrar',3,null,null,null,1,0,1,'LVT1','Casual');
insert into `hrm`.`view_employee_leaves`(`tbe_id`,`tbe_employee_id`,`tbe_first_name`,`tbe_middle_name`,`tbe_last_name`,`tbe_nick_name`,`tbe_name`,`tbale_id`,`tbale_start_date`,`tbale_end_date`,`tbale_comments`,`tbale_status`,`tbale_leave_taken`,`tblt_id`,`tblt_leave_types_id`,`tblt_name`) values (2,'EMP12010002','Nurul','','Ana','Ana','Nurul Ana',9,null,null,null,1,0,2,'LVT2','Medical');
insert into `hrm`.`view_employee_leaves`(`tbe_id`,`tbe_employee_id`,`tbe_first_name`,`tbe_middle_name`,`tbe_last_name`,`tbe_nick_name`,`tbe_name`,`tbale_id`,`tbale_start_date`,`tbale_end_date`,`tbale_comments`,`tbale_status`,`tbale_leave_taken`,`tblt_id`,`tblt_leave_types_id`,`tblt_name`) values (2,'EMP12010002','Nurul','','Ana','Ana','Nurul Ana',2,null,null,null,1,0,1,'LVT1','Casual');
